-- ============================================================
-- Language-specific story rules: es, it, nl, bs, sl
-- Adds rows to age_rules, theme_rules, difficulty_rules.
-- Content is language-specific (not copied from EN); ensures
-- correct grammar guidance (e.g. pro-drop for es/it/bs/sl).
-- Idempotent: ON CONFLICT DO NOTHING.
-- ============================================================

-- ============================================================
-- 1. age_rules (4 bands per language: 6-7, 8-9, 10-11, 12-13)
-- ============================================================

-- ---------- SPANISH (es): pro-drop, subjunctive, diminutives (-ito/-ita), ¿¡ ----------
INSERT INTO age_rules (
  min_age, max_age, language,
  max_sentence_length, allowed_tenses, sentence_structures,
  min_word_count, max_word_count,
  paragraph_length, dialogue_ratio, narrative_perspective,
  narrative_guidelines, example_sentences
) VALUES
(6, 7, 'es', 10,
  '{"presente de indicativo", "pretérito perfecto simple", "perífrasis ir a + infinitivo"}',
  'Frases simples. NO repitas el pronombre sujeto (español es pro-drop: "corría" no "él corría"). Máximo 2 proposiciones por oración. Conectores: cuando, porque.',
  250, 400,
  '2-3 oraciones por párrafo',
  '35-45% diálogo. En diálogo usa ¿ y ¡ (¿Qué pasa? ¡Mira!)',
  'Tercera persona (evitar él/ella si el verbo ya indica la persona)',
  'Vocabulario cotidiano y concreto. NUNCA uses pronombres sujeto redundantes (no "él fue, él vio"; usa "fue, vio"). Emociones simples (contento, triste, enfadado). Un problema y su solución. Conectores temporales (primero, luego, al final). Diálogo con ¿ y ¡. Descripciones sensoriales sencillas. Ser/estar correctos en las descripciones.',
  '{"Mía encontró un gatito en el jardín.", "— ¿Lo puedo quedarme? preguntó Mía.", "Al día siguiente fue a buscar comida para el gato.", "Cuando ronroneaba, Mía estaba muy contenta."}'),
(8, 9, 'es', 14,
  '{"presente", "pretérito indefinido", "pretérito imperfecto", "futuro simple", "subjuntivo presente (introducción)"}',
  'Mezcla de oraciones simples y subordinadas con que, cuando, porque, si, como. Pro-drop obligatorio: omite yo/él/ella cuando el verbo ya lo indica. Máximo tres proposiciones.',
  400, 600,
  '3-4 oraciones por párrafo',
  '30-40% diálogo. Siempre ¿ ¡ en preguntas y exclamaciones.',
  'Tercera persona; primera persona posible. Pro-drop.',
  'Vocabulario más rico; sigue omitiendo pronombres sujeto. Subjuntivo apropiado en oraciones subordinadas (ej. "quería que viniera"). Diminutivos (-ito, -ita) para calidez. Ser/estar en descripciones. Varias peripecias antes del desenlace. Inferencias sencillas. Humor adecuado.',
  '{"Mientras los demás dormían, Luna miraba las estrellas desde la ventana.", "Siempre había soñado con volar como los pájaros.", "Si pudiera encontrar el mapa que el abuelo había escondido...", "— No me rendiré nunca, susurró apretando el medallón."}'),
(10, 11, 'es', 18,
  '{"presente", "pretérito indefinido", "imperfecto", "pluscuamperfecto", "futuro", "condicional", "subjuntivo presente e imperfecto"}',
  'Oraciones complejas con subordinadas. Pro-drop: no repitas sujetos. Subjuntivo en deseos, dudas, valoraciones. Estilo directo e indirecto.',
  600, 900,
  '4-5 oraciones por párrafo',
  '25-35% diálogo. ¿ ¡ en diálogo.',
  'Tercera o primera persona. Pro-drop consistente.',
  'Vocabulario rico y matizado. Subjuntivo natural en literatura infantil. Figuras retóricas sencillas. Personajes con dilemas morales. Descripciones con ser/estar correctos. Ritmo narrativo variable. Temas profundos. Finales abiertos posibles.',
  '{"Aunque la tormenta rugía fuera, Leo no pensaba abandonar la expedición.", "De pronto entendió que el verdadero tesoro eran los amigos del camino.", "— ¿Crees que podemos cambiar las cosas? preguntó Sara.", "El anciano sonrió como si hubiera esperado esa pregunta."}'),
(12, 13, 'es', 18,
  '{"presente", "pretérito indefinido", "imperfecto", "pluscuamperfecto", "futuro", "condicional", "subjuntivo presente e imperfecto"}',
  'Oraciones complejas con subordinadas. Pro-drop. Subjuntivo en deseos, dudas, valoraciones. Estilo directo e indirecto.',
  600, 900,
  '4-5 oraciones por párrafo',
  '25-35% diálogo.',
  'Tercera o primera persona. Pro-drop.',
  'Igual que 10-11 con mayor profundidad. Subjuntivo y pro-drop naturales. Diminutivos para cercanía. Ser/estar precisos.',
  '{"Aunque la tormenta rugía fuera, Leo no pensaba abandonar la expedición.", "Comprendió que el verdadero tesoro eran los amigos.", "— ¿Crees que podemos cambiar las cosas? preguntó Sara.", "El anciano sonrió como si hubiera esperado esa pregunta."}')
ON CONFLICT (min_age, max_age, language) DO NOTHING;

-- ---------- ITALIAN (it): pro-drop, passato prossimo vs imperfetto, diminutives (-ino/-etto) ----------
INSERT INTO age_rules (
  min_age, max_age, language,
  max_sentence_length, allowed_tenses, sentence_structures,
  min_word_count, max_word_count,
  paragraph_length, dialogue_ratio, narrative_perspective,
  narrative_guidelines, example_sentences
) VALUES
(6, 7, 'it', 10,
  '{"presente indicativo", "passato prossimo", "futuro con andare a + infinito"}',
  'Frasi semplici. Pro-drop: non ripetere il pronome soggetto ("correva" non "lui correva"). Al massimo 2 proposizioni per frase. Connettivi: quando, perché.',
  250, 400,
  '2-3 frasi per paragrafo',
  '35-45% dialogo',
  'Terza persona (evitare lui/lei se il verbo è già coniugato)',
  'Vocabolario quotidiano e concreto. Pro-drop: non usare pronomi soggetto ridondanti. Emozioni semplici (felice, triste, arrabbiato). Un problema e la sua soluzione. Passato prossimo per azioni puntuali, imperfetto per descrizioni. Lessico gestuale/emotivo tipico. Diminutivi (-ino, -ina, -etto, -etta) per registro infantile.',
  '{"Mia ha trovato un gattino nel giardino.", "— Posso tenerlo? chiede Mia.", "Il giorno dopo va a cercare cibo per il gatto.", "Quando fa le fusa, Mia è molto felice."}'),
(8, 9, 'it', 14,
  '{"presente", "passato prossimo", "imperfetto", "futuro semplice", "condizionale presente (introduzione)"}',
  'Misto di frasi semplici e complesse. Pro-drop. Subordinate con che, quando, perché, se. Distinguere passato prossimo (azione) da imperfetto (contesto).',
  400, 600,
  '3-4 frasi per paragrafo',
  '30-40% dialogo',
  'Terza persona; prima persona possibile. Pro-drop.',
  'Vocabolario più ricco. Passato prossimo vs imperfetto per narrazione fluida. Diminutivi per calore. Descrizioni d''atmosfera. Più colpi di scena. Inferenze semplici. Umorismo adatto all''età.',
  '{"Mentre gli altri dormivano, Luna guardava le stelle dalla finestra.", "Aveva sempre sognato di volare come gli uccelli.", "Se solo potesse trovare la mappa che nonno aveva nascosto...", "— Non mi arrenderò mai, sussurrò stringendo il medaglione."}'),
(10, 11, 'it', 18,
  '{"presente", "passato prossimo", "imperfetto", "trapassato prossimo", "futuro", "condizionale", "congiuntivo presente (introduzione)"}',
  'Frasi complesse con subordinate. Pro-drop. Congiuntivo dove appropriato. Discorso diretto e indiretto.',
  600, 900,
  '4-5 frasi per paragrafo',
  '25-35% dialogo',
  'Terza o prima persona. Pro-drop.',
  'Vocabolario ricco. Passato prossimo/imperfetto/trapassato per coerenza narrativa. Congiuntivo in subordinate. Figure retoriche semplici. Personaggi multidimensionali. Finali aperti possibili.',
  '{"Anche se la tempesta infuriava fuori, Leo non intendeva abbandonare l''impresa.", "Capì che il vero tesoro erano gli amici fatti lungo la strada.", "— Credi davvero che possiamo cambiare le cose? chiese Sara.", "L''anziano sorrise, come se avesse aspettato quella domanda da sempre."}'),
(12, 13, 'it', 18,
  '{"presente", "passato prossimo", "imperfetto", "trapassato", "futuro", "condizionale", "congiuntivo"}',
  'Frasi complesse. Pro-drop. Congiuntivo. Discorso diretto e indiretto.',
  600, 900,
  '4-5 frasi per paragrafo',
  '25-35% dialogo',
  'Terza o prima persona. Pro-drop.',
  'Come 10-11 con maggiore profondità. Congiuntivo e pro-drop naturali. Diminutivi per registro.',
  '{"Anche se la tempesta infuriava, Leo non intendeva abbandonare.", "Capì che il vero tesoro erano gli amici.", "— Credi che possiamo cambiare le cose? chiese Sara.", "L''anziano sorrise come se avesse aspettato quella domanda."}')
ON CONFLICT (min_age, max_age, language) DO NOTHING;

-- ---------- DUTCH (nl): NOT pro-drop; V2 main, SOV subclauses; diminutives (-je, -tje) ----------
INSERT INTO age_rules (
  min_age, max_age, language,
  max_sentence_length, allowed_tenses, sentence_structures,
  min_word_count, max_word_count,
  paragraph_length, dialogue_ratio, narrative_perspective,
  narrative_guidelines, example_sentences
) VALUES
(6, 7, 'nl', 10,
  '{"onvoltooid tegenwoordige tijd", "voltooid tegenwoordige tijd", "gaan + infinitief (toekomst)"}',
  'Eenvoudige zinnen. Onderwerp is VERPLICHT (Nederlands is geen pro-drop). V2 in hoofdzin: persoonsvorm op tweede positie. Bijzin: SOV (subject aan het eind vóór de werkwoorden). Max. 2 zinsdelen.',
  250, 400,
  '2-3 zinnen per alinea',
  '35-45% dialoog',
  'Derde persoon (hij/zij – altijd uitgeschreven waar nodig)',
  'Dagelijks woordenschat. Onderwerp altijd uitdrukken (geen pro-drop). Verkleinwoorden (-je, -tje, -pje) passen goed bij kindertaal. Eén probleem en oplossing. Tijdconnectoren (eerst, toen, daarna, eindelijk). Eenvoudige zintuiglijke beschrijvingen. "Er/daar" voor existentiële zinnen waar natuurlijk.',
  '{"Mia vond een katje in de tuin.", "— Mag ik het houden? vraagt Mia.", "De volgende dag zoekt ze eten voor de kat.", "Als de kat spint, is Mia heel blij."}'),
(8, 9, 'nl', 14,
  '{"OTTT", "VTT", "onvoltooid verleden tijd", "gaan + inf.", "zou + inf. (conditioneel)"}',
  'Mix van eenvoudige en bijzinnen. V2 in hoofdzin; in bijzin (dat, omdat, toen, als) werkwoorden aan het eind (SOV). Onderwerp verplicht.',
  400, 600,
  '3-4 zinnen per alinea',
  '30-40% dialoog',
  'Derde persoon; ik-perspectief mogelijk. Onderwerp altijd uitgeschreven.',
  'Rijkere woordenschat. Verkleinwoorden voor warmte. V2 en SOV correct. Er/daar constructies waar passend. Sfeerbeschrijvingen. Meerdere wendingen. Eenvoudige inferenties. Leeftijdsadequate humor.',
  '{"Terwijl de anderen sliepen, keek Luna naar de sterren.", "Ze had altijd al gedroomd om te vliegen als de vogels.", "Als ze nu eens de kaart kon vinden die opa had verstopt...", "— Ik geef nooit op, fluisterde ze en kneep het medaillon in haar hand."}'),
(10, 11, 'nl', 18,
  '{"OTTT", "VTT", "OVT", "voltooid verleden tijd", "toekomende tijd", "conditioneel", "aanvoegende wijze (indirecte rede)"}',
  'Complexe zinnen met bijzinnen. V2/SOV. Onderwerp verplicht. Directe en indirecte rede.',
  600, 900,
  '4-5 zinnen per alinea',
  '25-35% dialoog',
  'Derde of eerste persoon. Onderwerp altijd aanwezig.',
  'Rijke, genuanceerde woordenschat. Verkleinwoorden waar natuurlijk. Stijlfiguren (metafoor, vergelijking). Meer dimensionale personages. Tempo wisselt. Open eindes mogelijk.',
  '{"Hoewel de storm buiten raasde, was Leo niet van plan zijn expeditie op te geven.", "Hij besefte opeens dat de echte schat de vrienden onderweg waren.", "— Geloof je echt dat we iets kunnen veranderen? vroeg Sara.", "De oude man glimlachte alsof hij op die vraag had gewacht."}'),
(12, 13, 'nl', 18,
  '{"OTTT", "VTT", "OVT", "VVT", "toekomend", "conditioneel", "indirecte rede"}',
  'Complexe zinnen. V2/SOV. Onderwerp verplicht.',
  600, 900,
  '4-5 zinnen per alinea',
  '25-35% dialoog',
  'Derde of eerste persoon.',
  'Zelfde als 10-11, meer diepgang. Verkleinwoorden en er/daar natuurlijk.',
  '{"Hoewel de storm raasde, gaf Leo zijn expeditie niet op.", "Hij besefte dat de echte schat de vrienden waren.", "— Geloof je dat we iets kunnen veranderen? vroeg Sara.", "De oude man glimlachte alsof hij op die vraag had gewacht."}')
ON CONFLICT (min_age, max_age, language) DO NOTHING;

-- ---------- BOSNIAN (bs): pro-drop; 7 cases (keep simple); aspect pairs; Latin script; Ijekavian ----------
INSERT INTO age_rules (
  min_age, max_age, language,
  max_sentence_length, allowed_tenses, sentence_structures,
  min_word_count, max_word_count,
  paragraph_length, dialogue_ratio, narrative_perspective,
  narrative_guidelines, example_sentences
) VALUES
(6, 7, 'bs', 10,
  '{"prezent", "perfekt", "futur I (bit ću + glagol)"}',
  'Jednostavne rečenice. Pro-drop: izostavi lične zamjenice kad je glagol dovoljan. Padeži: koristi osnovne oblike (nominativ, akuzativ); izbjegavaj komplikovane konstrukcije. Maksimalno 2 klauze. Latinica (ne ćirilica). Ijekavski.',
  250, 400,
  '2-3 rečenice po pasusu',
  '35-45% dijalog',
  'Treće lice (on/ona – izostavi kad je jasno iz glagola)',
  'Svakodnevni vokabular. Pro-drop. Aspekt: perfektiv za završenu radnju, imperfektiv za trajanje – drži dosljedno. Padeži jednostavni (djeci prikladno). Latinica. Jedan problem i rješenje. Vremenski konektori (prvo, zatim, na kraju).',
  '{"Mia je pronašla mačića u vrtu.", "— Mogu li ga zadržati? pita Mia.", "Sutradan je otišla po hranu za mačku.", "Kad je prela, Mia je bila vrlo sretna."}'),
(8, 9, 'bs', 14,
  '{"prezent", "perfekt", "imperfekt", "futur I", "kondicional (uvod)"}',
  'Mješavina jednostavnih i zavisnih rečenica. Pro-drop. Aspekt parovi: pažljivo biraj perfektiv/imperfektiv za tok pripovijesti. Padeži ostaju relativno jednostavni. Do tri klauze.',
  400, 600,
  '3-4 rečenice po pasusu',
  '30-40% dijalog',
  'Treće lice; prvo lice moguće. Pro-drop.',
  'Bogatiji vokabular. Aspekt za narativni ritam. Padeži jasni. Latinica, ijekavski. Više zapleta. Jednostavne inferencije.',
  '{"Dok su ostali spavali, Luna je gledala zvijezde kroz prozor.", "Oduvijek je sanjala da leti kao ptice.", "Kad bi samo mogla naći kartu koju je djed sakrio...", "— Nikad se neću predati, šapnula je stisnuvši medaljon."}'),
(10, 11, 'bs', 18,
  '{"prezent", "perfekt", "imperfekt", "pluskvamperfekt", "futur I/II", "kondicional", "konjunktiv (uvod)"}',
  'Složenije rečenice. Pro-drop. Aspekt dosljedan. Padeži točni ali ne previše složeni. Direktan i indirektan govor.',
  600, 900,
  '4-5 rečenica po pasusu',
  '25-35% dijalog',
  'Treće ili prvo lice. Pro-drop.',
  'Bogat, nijansiran vokabular. Aspekt i padeži prirodni. Figure stilа. Likovi s dilemama. Otvoreni završeci mogući.',
  '{"Iako je oluja bjesnila vani, Leo nije namjeravao odustati.", "Shvatio je da je pravo blago bilo u prijateljima na putu.", "— Vjeruješ li da možemo nešto promijeniti? upitala je Sara.", "Starac se nasmiješio kao da je čekao to pitanje."}'),
(12, 13, 'bs', 18,
  '{"prezent", "perfekt", "imperfekt", "pluskvamperfekt", "futur", "kondicional", "konjunktiv"}',
  'Složene rečenice. Pro-drop. Aspekt i padeži prirodni.',
  600, 900,
  '4-5 rečenica po pasusu',
  '25-35% dijalog',
  'Treće ili prvo lice.',
  'Kao 10-11 s većom dubinom. Latinica, ijekavski. Aspekt za flow.',
  '{"Iako je oluja bjesnila, Leo nije odustajao.", "Shvatio je da je blago bilo u prijateljima.", "— Vjeruješ li da možemo promijeniti nešto? upitala je Sara.", "Starac se nasmiješio kao da je čekao to pitanje."}')
ON CONFLICT (min_age, max_age, language) DO NOTHING;

-- ---------- SLOVENIAN (sl): pro-drop; compound vs separate words; dual; 6 cases ----------
INSERT INTO age_rules (
  min_age, max_age, language,
  max_sentence_length, allowed_tenses, sentence_structures,
  min_word_count, max_word_count,
  paragraph_length, dialogue_ratio, narrative_perspective,
  narrative_guidelines, example_sentences
) VALUES
(6, 7, 'sl', 10,
  '{"prezenčni čas", "preteklik (perfekt)", "povzetek (futur: bom + glagol)"}',
  'Preproste povedi. Pro-drop: izpusti osebni zaimek, če je glagol že jasen. POMEMBNO: v slovenščini veliko besed, ki so v nemščini sestavljene, pišemo ločeno (npr. ne zlivaj besed, ki morajo biti ločene). Dvojina: za točno dve osebi/stvari uporabi dvojinski oblik. Maksimalno 2 deli povedi.',
  250, 400,
  '2-3 povedi na odstavek',
  '35-45% dialog',
  'Tretja oseba (on/ona – izpusti, kjer je jasno)',
  'Vsakdanja beseda. Pro-drop. Pazljivo na sestavljanke: mnoge nemške sestavljene besede so v slovenščini dve ločeni besedi – ne združuj napačno. Dvojina za par (dva otroka, dve roki). Padeži preprosti (otrokom primerno). En problem in rešitev. Časovni konektorji (najprej, nato, na koncu).',
  '{"Mia je v vrtu našla mucka.", "— Lahko ga obdržim? vpraša Mia.", "Naslednji dan gre po hrano za mačko.", "Ko predi, je Mia zelo srečna."}'),
(8, 9, 'sl', 14,
  '{"prezenčni", "preteklik", "povzetek", "pogojnik (uvod)"}',
  'Mešanica preprostih in odvisnih povedi. Pro-drop. Sestavljanke: besede, ki so v nemščini ena beseda, so pogosto v slovenščini dve – preveri. Dvojina za 2. Do tri klauze.',
  400, 600,
  '3-4 povedi na odstavek',
  '30-40% dialog',
  'Tretja oseba; prva oseba mogoča. Pro-drop.',
  'Bogatejši besednjak. Eksplicitno: v slovenščini bodi previden pri sestavljankah; mnoge besede, ki so v nemščini združene, se pišejo ločeno. Dvojina. Padeži jasni. Več zapletov. Enostavne inference.',
  '{"Medtem ko so drugi spali, je Luna gledala zvezde.", "Vedno je sanjala, da leti kot ptice.", "Ko bi le našla zemljevid, ki ga je ded skril...", "— Ne bom se nikoli predala, je šepnila in stisnila medaljon."}'),
(10, 11, 'sl', 18,
  '{"prezenčni", "preteklik", "pluskvamperfekt", "povzetek", "pogojnik", "konjunktiv (uvod)"}',
  'Zapletene povedi. Pro-drop. Sestavljanke: ločene besede kjer je v slovenščini običajno. Dvojina. Padeži. Direkten in posreden govor.',
  600, 900,
  '4-5 povedi na odstavek',
  '25-35% dialog',
  'Tretja ali prva oseba. Pro-drop.',
  'Bogat, niansiran besednjak. Navodilo: v slovenščini bodi zelo previden pri sestavljenih besedah; mnoge, ki so v nemščini ena beseda, so v slovenščini dve ločeni. Dvojina in padeži naravno. Figurativni jezik. Odprti konci možni.',
  '{"Čeprav je vihar divjal zunaj, Leo ni nameraval opustiti odprave.", "Spoznál je, da je pravi zaklad v prijateljih na poti.", "— Res verjameš, da lahko kaj spremenimo? je vprašala Sara.", "Starec se je nasmehnil, kot da je na to vprašanje čakal."}'),
(12, 13, 'sl', 18,
  '{"prezenčni", "preteklik", "pluskvamperfekt", "povzetek", "pogojnik", "konjunktiv"}',
  'Zapletene povedi. Pro-drop. Sestavljanke ločeno. Dvojina. Padeži.',
  600, 900,
  '4-5 povedi na odstavek',
  '25-35% dialog',
  'Tretja ali prva oseba.',
  'Kot 10-11 z večjo globino. Sestavljanke: ločene besede kjer velja. Dvojina in sklanjatev naravna.',
  '{"Čeprav je vihar divjal, Leo ni opustil odprave.", "Spoznál je, da je zaklad v prijateljih.", "— Verjameš, da lahko kaj spremenimo? je vprašala Sara.", "Starec se je nasmehnil, kot da je čakal na to vprašanje."}')
ON CONFLICT (min_age, max_age, language) DO NOTHING;

-- Note: max_characters, max_plot_twists, plot_complexity are only present if
-- 20260209_age_rules_complexity_fields.sql was applied. If needed, run that
-- migration first, then run an extra UPDATE for language IN ('es','it','nl','bs','sl').

-- ============================================================
-- 2. theme_rules (6 themes × 5 languages)
-- ============================================================

INSERT INTO theme_rules (theme_key, language, labels, plot_templates, setting_descriptions, character_archetypes, sensory_details, typical_conflicts) VALUES
-- Spanish (es)
('fantasy', 'es', '{"de": "Märchen & Fantasie", "fr": "Contes & Fantaisie", "en": "Fairy Tales & Fantasy", "es": "Cuentos y fantasía"}',
  '{"Un niño descubre un objeto mágico que lo lleva a un mundo encantado", "Una criatura mágica necesita ayuda y solo el niño puede salvar su reino", "Un hechizo debe romperse antes del atardecer con tres pruebas", "El niño encuentra una puerta secreta a un mundo donde los animales hablan"}',
  'Bosques encantados con árboles luminosos, castillos flotantes en las nubes, aldeas bajo setas, cuevas de cristal, islas unidas por puentes de arcoíris.',
  '{"El aprendiz de mago torpe", "El hada traviesa", "El dragón bondadoso", "El rey/la reina en apuros", "El animal guía que habla", "El guardián misterioso"}',
  'Destellos dorados, polvo de estrellas, olor a flores mágicas, sonido de campanillas, texturas de musgo y seda.',
  '{"La magia desaparece y hay que restaurarla", "Un brujo malvado amenaza el mundo encantado", "El niño debe elegir entre volver a casa o quedarse", "Un malentendido entre criaturas mágicas causa caos"}'),
('action', 'es', '{"de": "Abenteuer & Action", "fr": "Aventure & Action", "en": "Adventure & Action", "es": "Aventura y acción"}',
  '{"El niño encuentra un mapa del tesoro y sale de expedición con amigos", "Un misterio en el barrio debe resolverse antes de que acaben las vacaciones", "El niño vive una aventura inesperada en una excursión escolar", "Una carrera contra reloj para salvar algo o a alguien"}',
  'Junglas frondosas, cuevas con antorchas, barcos pirata, montañas nevadas, ruinas con pasadizos secretos.',
  '{"El explorador valiente", "El mejor amigo leal", "El rival que se vuelve aliado", "El mentor sabio", "El personaje cómico"}',
  'Viento en el pelo, corazón acelerado, olor a tierra mojada, pasos apresurados, sol abrasador.',
  '{"Un obstáculo natural bloquea el camino", "Un rival quiere llegar primero", "El grupo debe separarse y reunirse", "Una traición aparente esconde buena intención"}'),
('animals', 'es', '{"de": "Tiergeschichten", "fr": "Histoires d''animaux", "en": "Animal Stories", "es": "Historias de animales"}',
  '{"Un animal perdido busca el camino de vuelta a su familia", "Un grupo de animales distintos debe cooperar para superar un reto", "Un animal joven debe demostrar su valía", "La amistad inesperada entre dos especies muy distintas"}',
  'Granjas tranquilas al amanecer, bosques con madrigueras y nidos, océanos y arrecifes, sabana africana, jardines secretos con estanques.',
  '{"El animalito valiente", "El anciano sabio del grupo", "El animal desconfiado que aprende a confiar", "El compañero torpe pero entrañable"}',
  'Pelo suave, canto de pájaros, hojas que crujen, olor a tierra y hierba, sol en el pelaje.',
  '{"Un depredador amenaza al grupo", "Las estaciones cambian y hay que migrar o adaptarse", "Una cría se separa de su madre", "Dos grupos reclaman el mismo territorio"}'),
('everyday', 'es', '{"de": "Alltag & Gefühle", "fr": "Quotidien & Émotions", "en": "Everyday & Feelings", "es": "Día a día y sentimientos"}',
  '{"Un niño se enfrenta a un cambio y aprende a adaptarse", "Un malentendido entre amigos que se resuelve hablando", "El niño descubre una pasión o un talento inesperado", "El primer día en un entorno nuevo (colegio, barrio, actividad)"}',
  'Casas acogedoras, patios de recreo, parques, aulas, habitaciones infantiles, cocinas a la hora de la merienda.',
  '{"El niño sensible y observador", "El recién llegado tímido", "El hermano o hermana mayor protector", "El amigo fiel", "El vecino peculiar"}',
  'Olor a tarta en el horno, risas de niños, luz suave de la tarde, textura de ceras, sabor a chocolate caliente.',
  '{"Un amigo se muda y hay que gestionar la despedida", "Un niño se siente diferente", "Un secreto que pesa y debe compartirse", "Celos por un bebé o un nuevo compañero"}'),
('humor', 'es', '{"de": "Humor & Chaos", "fr": "Humour & Chaos", "en": "Humor & Chaos", "es": "Humor y caos"}',
  '{"Todo sale mal cuando un niño intenta preparar una sorpresa", "Un objeto cotidiano empieza a hacer cosas absurdas", "Una mascota causa una serie de desastres cómicos", "Intercambio de papeles: el niño hace de padre y el padre de niño"}',
  'Cocinas patas arriba, cumpleaños caóticos, clase cuando un experimento sale mal, zoo el día que los animales cambian de jaula.',
  '{"El niño inventor cuyos planes fallan siempre", "El animal excéntrico", "El personaje que se toma todo al pie de la letra", "El gemelo gamberro"}',
  'Ruidos raros, colores vivos y salpicaduras, olores raros (queso, pócimas fallidas), texturas pegajosas.',
  '{"Cada intento de arreglarlo empeora las cosas", "Un malentendido desata una cadena de situaciones absurdas", "Un objeto mágico hace justo lo contrario de lo esperado", "La preparación secreta de un evento termina en desastre cómico"}'),
('educational', 'es', '{"de": "Wissen & Entdecken", "fr": "Savoir & Découvrir", "en": "Learn & Discover", "es": "Aprender y descubrir"}',
  '{"Un niño curioso hace una pregunta y sale a buscar la respuesta", "Un personaje histórico cuenta su historia como si hablara al niño", "El niño despierta en otra época y observa cómo vivía la gente", "Un animal u objeto explica su funcionamiento de forma divertida"}',
  'Laboratorios imaginarios, máquinas del tiempo, bibliotecas encantadas, observatorios, museos que cobran vida de noche.',
  '{"El niño curioso que siempre pregunta", "El profesor excéntrico", "El robot ayudante simpático", "El animal experto de su ecosistema"}',
  'Detalles precisos, colores naturales, sonidos auténticos de naturaleza o ciudad histórica, texturas de los materiales.',
  '{"El niño debe resolver un problema con lo aprendido", "Un experimento no da el resultado esperado", "Dos teorías se enfrentan y el niño debe encontrar la verdad", "Un fenómeno natural misterioso debe explicarse"}'),
-- Italian (it)
('fantasy', 'it', '{"de": "Märchen & Fantasie", "fr": "Contes & Fantaisie", "en": "Fairy Tales & Fantasy", "it": "Fiabe e fantasia"}',
  '{"Un bambino scopre un oggetto magico che lo trasporta in un mondo incantato", "Una creatura magica ha bisogno di aiuto e solo il bambino può salvare il regno", "Un incantesimo deve essere spezzato prima del tramonto con tre prove", "Il bambino trova una porta segreta verso un mondo dove gli animali parlano"}',
  'Foreste incantate con alberi luminosi, castelli fluttuanti tra le nuvole, villaggi sotto i funghi, grotte di cristallo, isole collegate da ponti arcobaleno.',
  '{"L''apprendista mago pasticcione", "La fata birichina", "Il drago buono", "Il re/la regina in difficoltà", "L''animale guida parlante", "Il guardiano misterioso"}',
  'Bagliori dorati, polvere di stelle, profumo di fiori magici, tintinnio di campanelli, muschio e seta.',
  '{"La magia scompare e va ripristinata", "Un mago malvagio minaccia il mondo incantato", "Il bambino deve scegliere tra tornare a casa o restare", "Un malinteso tra creature magiche crea caos"}'),
('action', 'it', '{"de": "Abenteuer & Action", "fr": "Aventure & Action", "en": "Adventure & Action", "it": "Avventura e azione"}',
  '{"Il bambino trova una mappa del tesoro e parte in spedizione con gli amici", "Un mistero nel quartiere deve essere risolto prima della fine delle vacanze", "Il bambino vive un''avventura inaspettata durante una gita scolastica", "Una corsa contro il tempo per salvare qualcosa o qualcuno"}',
  'Giungle lussureggianti, grotte con torce, navi pirata, montagne innevate, rovine con passaggi segreti.',
  '{"L''esploratore coraggioso", "Il migliore amico fedele", "Il rivale che diventa alleato", "Il mentore saggio", "Il personaggio comico"}',
  'Vento nei capelli, cuore che batte forte, odore di terra bagnata, passi frettolosi, sole cocente.',
  '{"Un ostacolo naturale blocca la strada", "Un rivale vuole arrivare per primo", "Il gruppo deve separarsi e ritrovarsi", "Un tradimento apparente nasconde buone intenzioni"}'),
('animals', 'it', '{"de": "Tiergeschichten", "fr": "Histoires d''animaux", "en": "Animal Stories", "it": "Storie di animali"}',
  '{"Un animale smarrito cerca la strada per tornare alla famiglia", "Un gruppo di animali diversi deve cooperare per superare una sfida", "Un animale giovane deve dimostrare il suo valore", "L''amicizia inattesa tra due specie molto diverse"}',
  'Fattorie tranquille all''alba, foreste con tane e nidi, oceani e barriere coralline, savana africana, giardini segreti con stagni.',
  '{"Il piccolo animale coraggioso", "Il saggio anziano del gruppo", "L''animale diffidente che impara a fidarsi", "Il compagno goffo ma adorabile"}',
  'Pelliccia morbida, canto degli uccelli, fruscio delle foglie, odore di terra e erba, sole sul pelo.',
  '{"Un predatore minaccia il gruppo", "Le stagioni cambiano e serve migrare o adattarsi", "Un cucciolo è separato dalla madre", "Due gruppi rivendicano lo stesso territorio"}'),
('everyday', 'it', '{"de": "Alltag & Gefühle", "fr": "Quotidien & Émotions", "en": "Everyday & Feelings", "it": "Quotidiano ed emozioni"}',
  '{"Un bambino affronta un cambiamento e impara ad adattarsi", "Un malinteso tra amici che si risolve parlando", "Il bambino scopre una passione o un talento inatteso", "Il primo giorno in un ambiente nuovo (scuola, quartiere, attività)"}',
  'Case accoglienti, cortili di scuola, parchi, aule, camerette, cucine all''ora della merenda.',
  '{"Il bambino sensibile e osservatore", "Il nuovo arrivato timido", "Il fratello o sorella maggiore protettivo", "L''amico fedele", "Il vicino bizzarro"}',
  'Profumo di torta nel forno, risate di bambini, luce soffusa della sera, texture dei pastelli, gusto della cioccolata calda.',
  '{"Un amico si trasferisce e bisogna gestire la separazione", "Un bambino si sente diverso", "Un segreto che pesa e va condiviso", "Gelosia per un fratellino o un nuovo compagno"}'),
('humor', 'it', '{"de": "Humor & Chaos", "fr": "Humour & Chaos", "en": "Humor & Chaos", "it": "Umorismo e caos"}',
  '{"Tutto va storto quando un bambino cerca di preparare una sorpresa", "Un oggetto quotidiano inizia a fare cose assurde", "Un animale domestico causa una serie di disastri comici", "Scambio di ruoli: il bambino fa il genitore e viceversa"}',
  'Cucine in disordine, feste di compleanno caotiche, classe durante un esperimento fallito, zoo quando gli animali decidono di cambiare gabbia.',
  '{"Il bambino inventore i cui piani falliscono sempre", "L''animale eccentrico", "Il personaggio che prende tutto alla lettera", "Il gemello burlone"}',
  'Rumori improbabili, colori vivaci e schizzi, odori sorprendenti (formaggio puzzolente, pozioni fallite), texture appiccicose.',
  '{"Ogni tentativo di risolvere peggiora le cose", "Un malinteso innesca una catena di situazioni assurde", "Un oggetto magico fa esattamente l''opposto di ciò che si aspetta", "La preparazione segreta di un evento diventa un disastro comico"}'),
('educational', 'it', '{"de": "Wissen & Entdecken", "fr": "Savoir & Découvrir", "en": "Learn & Discover", "it": "Imparare e scoprire"}',
  '{"Un bambino curioso fa una domanda e parte alla ricerca della risposta", "Un personaggio storico racconta la sua storia come se parlasse al bambino", "Il bambino si risveglia in un''epoca diversa e osserva come si viveva", "Un animale o oggetto spiega il suo funzionamento in modo divertente"}',
  'Laboratori immaginari, macchine del tempo, biblioteche incantate, osservatori, musei che prendono vita di notte.',
  '{"Il bambino curioso che fa sempre domande", "Il professore eccentrico", "Il robot assistente simpatico", "L''animale esperto del suo ecosistema"}',
  'Dettagli precisi, colori naturali, suoni autentici di natura o città storica, texture dei materiali.',
  '{"Il bambino deve risolvere un problema con ciò che ha imparato", "Un esperimento non dà il risultato atteso", "Due teorie si scontrano e il bambino deve trovare la verità", "Un fenomeno naturale misterioso va spiegato"}')
ON CONFLICT (theme_key, language) DO NOTHING;

-- Dutch (nl), Bosnian (bs), Slovenian (sl) theme_rules
INSERT INTO theme_rules (theme_key, language, labels, plot_templates, setting_descriptions, character_archetypes, sensory_details, typical_conflicts) VALUES
('fantasy', 'nl', '{"de": "Märchen & Fantasie", "fr": "Contes & Fantaisie", "en": "Fairy Tales & Fantasy", "nl": "Sprookjes & fantasie"}',
  '{"Een kind ontdekt een magisch voorwerp dat het naar een betoverde wereld brengt", "Een magisch wezen heeft hulp nodig en alleen het kind kan het koninkrijk redden", "Een betovering moet voor zonsondergang verbroken worden door drie proeven", "Het kind vindt een geheime deur naar een wereld waar dieren praten"}',
  'Betoverde bossen met lichtgevende bomen, zwevende kastelen in de wolken, miniatuurdorpjes onder paddenstoelen, glinsterende kristalgrotten, vliegende eilanden verbonden door regenboogbruggen.',
  '{"De onhandige tovenaarsleerling", "De ondeugende fee", "De goedaardige draak", "De koning/koningin in nood", "Het sprekende dier als gids", "De geheimzinnige wachter"}',
  'Gouden glinstering, sterrenstof, geur van magische bloemen, rinkelende belletjes, mos en zijde.',
  '{"De magie verdwijnt en moet hersteld worden", "Een boze tovenaar bedreigt de betoverde wereld", "Het kind moet kiezen tussen naar huis of in het magische land blijven", "Een misverstand tussen magische wezens veroorzaakt chaos"}'),
('action', 'nl', '{"de": "Abenteuer & Action", "fr": "Aventure & Action", "en": "Adventure & Action", "nl": "Avontuur & actie"}',
  '{"Het kind vindt een schatkaart en gaat op expeditie met vrienden", "Een raadsel in de buurt moet voor het einde van de vakantie opgelost worden", "Het kind belandt in een onverwacht avontuur tijdens een schooluitje", "Een race tegen de klok om iets of iemand te redden"}',
  'Weelderige jungles, donkere grotten met fakkels, piratenschepen op zee, besneeuwde bergen, oude ruïnes met geheime gangen.',
  '{"De dappere ontdekkingsreiziger", "De trouwe beste vriend", "De rivaal die bondgenoot wordt", "De wijze mentor", "De komische bijfiguur"}',
  'Wind in het haar, bonzend hart, geur van natte aarde, haastige voetstappen, brandende zon.',
  '{"Een natuurlijk obstakel blokkeert het pad", "Een rivaal wil als eerste het doel bereiken", "De groep moet splitsen en weer samenkomen", "Een ogenschijnlijk verraad verbergt een goede bedoeling"}'),
('animals', 'nl', '{"de": "Tiergeschichten", "fr": "Histoires d''animaux", "en": "Animal Stories", "nl": "Dierenverhalen"}',
  '{"Een verdwaald dier zoekt de weg terug naar zijn familie", "Een groep verschillende dieren moet samenwerken om een uitdaging te overwinnen", "Een jong dier moet zijn waarde bewijzen", "De onverwachte vriendschap tussen twee heel verschillende soorten"}',
  'Vredige boerderijen bij zonsopgang, diepe bossen met holen en nesten, oceanen en koraalriffen, Afrikaanse savanne, geheime tuinen met vijvers.',
  '{"Het dappere kleine dier", "De wijze oudste van de groep", "Het wantrouwige dier dat vertrouwen leert", "De onhandige maar lieve metgezel"}',
  'Zachte vacht, vogelgezang, ritselende bladeren, geur van aarde en gras, warme zon op de vacht.',
  '{"Een roofdier bedreigt de groep", "Seizoenen wisselen en migratie of aanpassing is nodig", "Een baby-dier is gescheiden van zijn moeder", "Twee dierengroepen claimen hetzelfde territorium"}'),
('everyday', 'nl', '{"de": "Alltag & Gefühle", "fr": "Quotidien & Émotions", "en": "Everyday & Feelings", "nl": "Alledaags & gevoelens"}',
  '{"Een kind krijgt te maken met een verandering en leert zich aan te passen", "Een misverstand tussen vrienden dat door communicatie wordt opgelost", "Het kind ontdekt een onverwachte passie of talent", "De eerste dag in een nieuwe omgeving (school, buurt, activiteit)"}',
  'Gezellige huizen, levendige schoolpleinen, buurtparken, klaslokalen, kinderkamers, keukens bij de snacktijd.',
  '{"Het gevoelige en oplettende kind", "De verlegen nieuwkomer", "De beschermende grote broer/zus", "De trouwe vriend", "De eigenaardige buurman"}',
  'Geur van cake uit de oven, kindergelach, zacht avondlicht, textuur van krijtjes, smaak van warme chocolade.',
  '{"Een vriend verhuist en het afscheid moet verwerkt worden", "Een kind voelt zich anders dan de anderen", "Een geheim dat zwaar weegt en gedeeld moet worden", "Jaloezie over een nieuwe baby of klasgenoot"}'),
('humor', 'nl', '{"de": "Humor & Chaos", "fr": "Humour & Chaos", "en": "Humor & Chaos", "nl": "Humor & chaos"}',
  '{"Alles gaat mis wanneer een kind een verrassing wil voorbereiden", "Een alledaags voorwerp begint absurde dingen te doen", "Een huisdier veroorzaakt een reeks komische rampen", "Rolwissel: het kind wordt de ouder en omgekeerd"}',
  'Rommelige keukens, chaotische verjaardagsfeesten, klaslokaal tijdens een mislukt experiment, dierentuin wanneer de dieren van hok wisselen.',
  '{"Het uitvindertje wiens plannen altijd spectaculair mislukken", "Het excentrieke dier", "De figuur die alles letterlijk neemt", "De grappenmaker-tweeling"}',
  'Onwaarschijnlijke geluiden, felle kleuren en spetters, verrassende geuren (stinkende kaas, mislukte brouwsels), slijmerige texturen.',
  '{"Elke poging het op te lossen maakt het erger", "Een misverstand veroorzaakt een keten van absurde situaties", "Een magisch voorwerp doet precies het tegenovergestelde van verwacht", "De geheime voorbereiding van een evenement wordt een komische ramp"}'),
('educational', 'nl', '{"de": "Wissen & Entdecken", "fr": "Savoir & Découvrir", "en": "Learn & Discover", "nl": "Leren & ontdekken"}',
  '{"Een nieuwsgierig kind stelt een vraag en gaat op ontdekkingsreis", "Een historisch figuur vertelt zijn verhaal alsof hij tegen het kind praat", "Het kind wordt wakker in een ander tijdperk en ziet hoe mensen leefden", "Een dier of voorwerp legt op speelse wijze zijn werking uit"}',
  'Denkbeeldige laboratoria, tijdmachines, betoverde bibliotheken, sterrenwachten, musea die ''s nachts tot leven komen.',
  '{"Het nieuwsgierige kind dat altijd vragen stelt", "De excentrieke professor", "De vriendelijke robotassistent", "Het dier als expert van zijn ecosysteem"}',
  'Precieze details, natuurlijke kleuren, authentieke geluiden van natuur of historische stad, texturen van bestudeerde materialen.',
  '{"Het kind moet een probleem oplossen met nieuwe kennis", "Een experiment geeft onverwachte resultaten", "Twee theorieën botsen en het kind moet de waarheid vinden", "Een mysterieus natuurverschijnsel moet uitgelegd worden"}'),
-- Bosnian (bs)
('fantasy', 'bs', '{"de": "Märchen & Fantasie", "fr": "Contes & Fantaisie", "en": "Fairy Tales & Fantasy", "bs": "Bajke i fantazija"}',
  '{"Dijete otkrije čarobni predmet koji ga prenosi u začarani svijet", "Čarobno biće treba pomoć i samo dijete može spasiti kraljevstvo", "Čarolija se mora slomiti prije zalaska sunca kroz tri kušnje", "Dijete nađe tajna vrata u svijet gdje životinje govore"}',
  'Začarane šume sa svjetlećim drvećem, dvorci u oblacima, miniaturna sela ispod gljiva, kristalne špilje, leteća ostrva povezana mostovima duge.',
  '{"Nespretni šegrt čarobnjaka", "Vragolasta vila", "Dobronamjerni zmaj", "Kralj/kraljica u nevolji", "Govoreća životinja vodič", "Tajanstveni čuvar"}',
  'Zlatni odsjaji, zvjezdana prašina, miris čarobnog cvijeća, zvončići, mahovina i svila.',
  '{"Magija nestaje i mora se vratiti", "Zli čarobnjak prijeti začaranom svijetu", "Dijete mora birati između povratka kući i ostanka", "Nesporazum među čarobnim bićima stvara haos"}'),
('action', 'bs', '{"de": "Abenteuer & Action", "fr": "Aventure & Action", "en": "Adventure & Action", "bs": "Avantura i akcija"}',
  '{"Dijete nađe kartu blaga i kreće u ekspediciju s prijateljima", "Misterija u susjedstvu mora biti riješena prije kraja praznika", "Dijete upadne u neočekivanu avanturu tijekom školskog izleta", "Utrka s vremenom da se nešto ili netko spasi"}',
  'Bujne džungle, mračne špilje s bakljama, gusarski brodovi, sniježne planine, drevne ruševine s tajnim prolazima.',
  '{"Hrabri istraživač", "Vjerni najbolji prijatelj", "Rival koji postane saveznik", "Mudri mentor", "Komični lik"}',
  'Vjetar u kosi, lupanje srca, miris vlažne zemlje, žurni koraci, pržeće sunce.',
  '{"Prirodna prepreka blokira put", "Rival želi prvi stići do cilja", "Grupa se mora razdvojiti i ponovo sastati", "Prividna izdaja krije dobru namjeru"}'),
('animals', 'bs', '{"de": "Tiergeschichten", "fr": "Histoires d''animaux", "en": "Animal Stories", "bs": "Priče o životinjama"}',
  '{"Izgubljena životinja traži put natrag obitelji", "Različite životinje moraju surađivati da prevladaju izazov", "Mlada životinja mora dokazati svoju vrijednost", "Neočekivano prijateljstvo između dvije vrste"}',
  'Mirne farme u zoru, duboke šume s jazbinama i gnijezdima, oceani i koraljni grebeni, afrička savana, tajni vrtovi s bara.',
  '{"Hrabra mala životinja", "Mudri starješina grupe", "Oprezna životinja koja uči povjerenju", "Nespretan ali drag drug"}',
  'Meko krzno, pjev ptica, šuštanje lišća, miris zemlje i trave, toplina sunca na dlaki.',
  '{"Predator prijeti grupi", "Godišnja doba se mijenjaju, treba migracija ili prilagodba", "Beba životinje odvojena od majke", "Dvije grupe polažu pravo na isti teritorij"}'),
('everyday', 'bs', '{"de": "Alltag & Gefühle", "fr": "Quotidien & Émotions", "en": "Everyday & Feelings", "bs": "Svakodnevnica i osjećaji"}',
  '{"Dijete se suoči s promjenom i nauči se prilagoditi", "Nesporazum među prijateljima koji se rješava razgovorom", "Dijete otkrije strast ili talent", "Prvi dan u novoj sredini (škola, kvart, aktivnost)"}',
  'Ugodne kuće, živahna školska igrališta, parkovi, učionice, dječije sobe, kuhinje u vrijeme užine.',
  '{"Osjetljivo i pažljivo dijete", "Sramežljivi pridošlica", "Zaštitnički stariji brat/sestra", "Vjerni prijatelj", "Čudan susjed"}',
  'Miris kolača iz pećnice, dječji smijeh, prigušena večernja svjetlost, tekstura bojica, okus tople čokolade.',
  '{"Prijatelj se seli i rastanak treba obraditi", "Dijete se osjeća drugačije", "Tajna koja tišti i mora se podijeliti", "Ljubomora na novu bebu ili kolegu"}'),
('humor', 'bs', '{"de": "Humor & Chaos", "fr": "Humour & Chaos", "en": "Humor & Chaos", "bs": "Humor i haos"}',
  '{"Sve krene po zlu kad dijete pokuša pripremiti iznenađenje", "Svakodnevni predmet počne raditi apsurdne stvari", "Kućni ljubimac izazove niz komičnih katastrofa", "Zamjena uloga: dijete postane roditelj i obratno"}',
  'Neuredne kuhinje, kaotične rođendanske zabave, učionica tijekom neuspjelog eksperimenta, zoološki vrt kad životinje odluče promijeniti kaveze.',
  '{"Dijete izumitelj čiji planovi uvijek spektakularno propadnu", "Ekscentrična životinja", "Lik koji sve shvaća doslovno", "Blizanski nestašan"}',
  'Nevjerojatni zvuci, jarke boje i prskanje, iznenađujući mirisi (smrdljivi sir, neuspjele napitke), ljepljive teksture.',
  '{"Svaki pokušaj rješavanja pogoršava stvari", "Nesporazum pokrene lanac apsurdnih situacija", "Čarobni predmet radi upravo suprotno od očekivanog", "Tajna priprema događaja postane komična katastrofa"}'),
('educational', 'bs', '{"de": "Wissen & Entdecken", "fr": "Savoir & Découvrir", "en": "Learn & Discover", "bs": "Učenje i otkrivanje"}',
  '{"Radoznalo dijete postavi pitanje i krene u potragu za odgovorom", "Povijesna osoba ispriča svoju priču kao da govori djetetu", "Dijete se probudi u drugom dobu i promatra kako su ljudi živjeli", "Životinja ili predmet na zabavan način objasni svoje djelovanje"}',
  'Zamišljeni laboratoriji, vremenski strojevi, začarane knjižnice, zvjezdarnice, muzeji koji noću ožive.',
  '{"Radoznalo dijete koje uvijek pita", "Ekscentrični profesor", "Ljubazni robotski pomoćnik", "Životinja stručnjak svog ekosustava"}',
  'Precizni detalji, prirodne boje, autentični zvuci prirode ili povijesnog grada, teksture materijala.',
  '{"Dijete mora riješiti problem novim znanjem", "Eksperiment daje neočekivane rezultate", "Dvije teorije se sukobljavaju i dijete mora naći istinu", "Misteriozan prirodni fenomen treba objasniti"}'),
-- Slovenian (sl)
('fantasy', 'sl', '{"de": "Märchen & Fantasie", "fr": "Contes & Fantaisie", "en": "Fairy Tales & Fantasy", "sl": "Pravljice in fantazija"}',
  '{"Otrok odkrije čarobni predmet, ki ga prenese v začarani svet", "Čarobno bitje potrebuje pomoč in samo otrok lahko reši kraljestvo", "Urok je treba prelomiti pred sončnim zahodom s tremi preizkušnjami", "Otrok najde skrivna vrata v svet, kjer živali govorijo"}',
  'Začarani gozdovi s svetlečim drevesi, plavajoči gradovi v oblakih, miniaturni vasi pod gobami, bleščeče kristalne jame, leteči otoki, povezani z mavričnimi mostovi.',
  '{"Nespretni vajenec čarovnika", "Nagajiva vila", "Dobrosrčni zmaj", "Kralj/kraljica v stiski", "Govoreča žival vodnik", "Skrivnostni čuvaj"}',
  'Zlati odsevi, zvezdni prah, dišava čarobnega cvetja, zvončki, mah in svila.',
  '{"Magija izginja in jo je treba obnoviti", "Zli čarovnik ogroza začarani svet", "Otrok mora izbrati med vrnitvijo domov in ostankom", "Nesporazum med čarobnimi bitji povzroči kaos"}'),
('action', 'sl', '{"de": "Abenteuer & Action", "fr": "Aventure & Action", "en": "Adventure & Action", "sl": "Pustolovščina in akcija"}',
  '{"Otrok najde zemljevid zaklada in odpotuje na odpravo s prijatelji", "Skrivnost v soseski je treba razrešiti pred koncem počitnic", "Otrok pade v nepričakovano pustolovščino med šolskim izletom", "Tekma s časom, da rešimo nekaj ali nekoga"}',
  'Bujne džungle, temne jame z baklami, gusarske ladje na oceanu, zasnežene gore, starodavne ruševine s skrivnimi prehodi.',
  '{"Pogumni raziskovalec", "Zvest najboljši prijatelj", "Rival, ki postane zaveznik", "Modri mentor", "Komični lik"}',
  'Veter v laseh, utripajoče srce, vonj mokre zemlje, hitri koraki, pekoče sonce.',
  '{"Naravna ovira blokira pot", "Rival želi prvi doseči cilj", "Skupina se mora razdeliti in ponovno združiti", "Navidezna izdaja skriva dobro namen"}'),
('animals', 'sl', '{"de": "Tiergeschichten", "fr": "Histoires d''animaux", "en": "Animal Stories", "sl": "Zgodbe o živalih"}',
  '{"Izgubljena žival išče pot nazaj k družini", "Skupina različnih živali mora sodelovati, da premaga izziv", "Mlada žival mora dokazati svojo vrednost", "Nepričakovano prijateljstvo med dvema zelo različnima vrstama"}',
  'Mirne kmetije ob zori, globoki gozdovi z brlogi in gnezdi, oceani in koralni grebeni, afriška savana, skrivni vrtovi z ribniki.',
  '{"Pogumna majhna žival", "Modri starešina skupine", "Previdna žival, ki se nauči zaupati", "Nespreten a ljubek spremljevalec"}',
  'Mehka dlaka, ptičje petje, šelestenje listov, vonj zemlje in trave, toplo sonce na dlaki.',
  '{"Plenilec ogroza skupino", "Leta se menjajo, potrebna je migracija ali prilagoditev", "Mladič je ločen od matere", "Dve skupini zahtevata isto ozemlje"}'),
('everyday', 'sl', '{"de": "Alltag & Gefühle", "fr": "Quotidien & Émotions", "en": "Everyday & Feelings", "sl": "Vsakdan in čustva"}',
  '{"Otrok se sooči s spremembo in se nauči prilagoditi", "Nesporazum med prijatelji se razreši z komunikacijo", "Otrok odkrije nepričakovano strast ali talent", "Prvi dan v novem okolju (šola, soseska, dejavnost)"}',
  'Udobne hiše, živa šolska igrišča, soseski parki, učilnice, otroške sobe, družinske kuhinje ob malici.',
  '{"Občutljiv in opazen otrok", "Sramežljiv novinec", "Varovalni starejši brat/sestra", "Zvest prijatelj", "Čudaški sosed"}',
  'Vonj torte iz pečice, otroški smeh, mehka večerna svetloba, tekstura voščenk, okus vroče čokolade.',
  '{"Prijatelj se preseli in ločitev je treba prenesti", "Otrok se počuti drugačnega", "Skrivnost, ki teži in jo je treba deliti", "Ljubosumje na novega otroka ali sošolca"}'),
('humor', 'sl', '{"de": "Humor & Chaos", "fr": "Humour & Chaos", "en": "Humor & Chaos", "sl": "Humor in kaos"}',
  '{"Vse gre narobe, ko otrok poskuša pripraviti presenečenje", "Vsakdanji predmet začne delati absurdne stvari", "Hišni ljubljenec povzroči serijo komičnih katastrof", "Zamenjava vlog: otrok postane starš in obratno"}',
  'Neurejene kuhinje, kaotične rojstnodnevne zabave, učilnica med neuspelim poskusom, živalski vrt, ko živali odločijo zamenjati kletke.',
  '{"Otrok izumitelj, katerega načrti vedno spektakularno odpovejo", "Ekscentrična žival", "Lik, ki vse jemlje dobesedno", "Dvojček nagajivček"}',
  'Neverjetni zvoki, žive barve in brizganje, presenetljivi vonji (smrdljiv sir, neuspeli napitki), lepljive teksture.',
  '{"Vsak poskus rešitve poslabša stvari", "Nesporazum sproži verigo absurdnih situacij", "Čarobni predmet naredi ravno nasprotno od pričakovanega", "Skrivna priprava dogodka postane komična katastrofa"}'),
('educational', 'sl', '{"de": "Wissen & Entdecken", "fr": "Savoir & Découvrir", "en": "Learn & Discover", "sl": "Učenje in odkrivanje"}',
  '{"Radoveden otrok postavi vprašanje in odpotuje na odkritje", "Zgodovinska oseba pripoveduje svojo zgodbo, kot da govori otroku", "Otrok se zbudi v drugi dobi in opazuje, kako so ljudje živeli", "Žival ali predmet na zabaven način razloži svoje delovanje"}',
  'Namišljeni laboratoriji, časovni stroji, začarane knjižnice, observatoriji, muzeji, ki ponoči oživijo.',
  '{"Radoveden otrok, ki vedno sprašuje", "Ekscentrični profesor", "Prijeten robotski pomočnik", "Žival kot strokovnjak svojega ekosistema"}',
  'Natančni detajli, naravne barve, avtentični zvoki narave ali zgodovinskega mesta, teksture preučevanih materialov.',
  '{"Otrok mora rešiti problem z novim znanjem", "Poskus da nepričakovane rezultate", "Dve teoriji se spopadeta in otrok mora najti resnico", "Skrivnostni naravni pojav je treba razložiti"}')
ON CONFLICT (theme_key, language) DO NOTHING;

-- ============================================================
-- 3. difficulty_rules (3 levels × 5 languages)
-- ============================================================

INSERT INTO difficulty_rules (
  difficulty_level, language,
  label, description, vocabulary_scope,
  new_words_per_story, figurative_language, idiom_usage,
  humor_types, repetition_strategy, example_vocabulary
) VALUES
-- Spanish (es)
(1, 'es', '{"es": "Fácil", "en": "Easy"}', '{"es": "Vocabulario sencillo, pocas palabras nuevas. Lectura amigable y fluida.", "en": "Simple vocabulary, few new words. Child-friendly and easy to read."}',
  'Palabras del día a día, concretas y familiares. Evitar tecnicismos. Pro-drop: no repetir pronombres sujeto.',
  3, 'Casi ninguna. Comparaciones muy simples si acaso.', 'Uso mínimo; expresiones muy comunes (ej. "de repente", "al final").',
  '{"situaciones absurdas", "onomatopeyas", "equivocaciones graciosas"}',
  'Repetir la palabra nueva 2-3 veces en contextos distintos en la historia. Usar diminutivos (-ito, -ita) para reforzar.',
  '{"correr", "mirar", "encontrar", "pequeño", "contento", "casa"}'),
(2, 'es', '{"es": "Medio", "en": "Medium"}', '{"es": "Vocabulario intermedio, algunas palabras nuevas. Equilibrado y comprensible.", "en": "Intermediate vocabulary, some new words. Balanced and clear."}',
  'Vocabulario algo más rico; sigue siendo mayormente concreto. Introducir algún adjetivo o verbo menos frecuente. Pro-drop.',
  6, 'Comparaciones y alguna metáfora sencilla. Subjuntivo donde sea natural.', 'Algunas expresiones idiomáticas frecuentes (ej. "tener miedo", "echar de menos").',
  '{"situaciones absurdas", "juegos de palabras simples", "malentendidos", "exageración"}',
  'Palabra nueva: aparecer en 2 escenas; variar el contexto. Recurrir a sinónimos sencillos en la misma historia.',
  '{"aventura", "misterio", "valiente", "sorprendido", "decidir", "ayudar"}'),
(3, 'es', '{"es": "Difícil", "en": "Hard"}', '{"es": "Vocabulario más rico, más palabras nuevas. Desafiante y enriquecedor.", "en": "Richer vocabulary, more new words. Challenging and enriching."}',
  'Léxico variado y matizado. Términos más literarios o descriptivos. Subjuntivo y pro-drop naturales.',
  10, 'Metáforas, comparaciones, personificación suave. Subjuntivo en cláusulas subordinadas.', 'Modismos y refranes adaptados a la edad.',
  '{"juegos de palabras", "ironía leve", "situaciones absurdas", "doble sentido suave"}',
  'Palabras nuevas repartidas en la trama; reforzar con contexto y sinónimos. No repetir en exceso.',
  '{"inesperado", "determinación", "reconciliación", "descubrimiento", "generosidad"}'),
-- Italian (it)
(1, 'it', '{"it": "Facile", "en": "Easy"}', '{"it": "Vocabolario semplice, poche parole nuove. Lettura amichevole e scorrevole.", "en": "Simple vocabulary, few new words. Child-friendly and easy to read."}',
  'Parole di tutti i giorni, concrete e familiari. Evitare tecnicismi. Pro-drop: non ripetere i pronomi soggetto.',
  3, 'Quasi nessuna. Al massimo confronti molto semplici.', 'Uso minimo; espressioni comuni (es. "tutto a un tratto", "alla fine").',
  '{"situazioni assurde", "onomatopee", "equivoci buffi"}',
  'Ripetere la parola nuova 2-3 volte in contesti diversi. Usare diminutivi (-ino, -etto) per rinforzare.',
  '{"correre", "guardare", "trovare", "piccolo", "felice", "casa"}'),
(2, 'it', '{"it": "Medio", "en": "Medium"}', '{"it": "Vocabolario intermedio, alcune parole nuove. Bilanciato e comprensibile.", "en": "Intermediate vocabulary, some new words. Balanced and clear."}',
  'Vocabolario un po'' più ricco; ancora per lo più concreto. Passato prossimo/imperfetto corretti. Pro-drop.',
  6, 'Confronti e qualche metafora semplice. Condizionale dove naturale.', 'Alcune espressioni idiomatiche comuni (es. "avere paura", "essere in gamba").',
  '{"situazioni assurde", "giochi di parole semplici", "malintesi", "esagerazione"}',
  'Parola nuova in 2 scene; variare il contesto. Sinonimi semplici nella stessa storia.',
  '{"avventura", "mistero", "coraggioso", "sorpreso", "decidere", "aiutare"}'),
(3, 'it', '{"it": "Difficile", "en": "Hard"}', '{"it": "Vocabolario più ricco, più parole nuove. Stimolante e formativo.", "en": "Richer vocabulary, more new words. Challenging and enriching."}',
  'Lessico vario e sfumato. Termini più letterari o descrittivi. Congiuntivo dove appropriato.',
  10, 'Metafore, confronti, personificazione leggera.', 'Modi di dire e proverbi adatti all''età.',
  '{"giochi di parole", "ironia leggera", "situazioni assurde", "doppio senso lieve"}',
  'Parole nuove distribuite nella trama; rinforzare con contesto e sinonimi.',
  '{"inesperato", "determinazione", "riconciliazione", "scoperta", "generosità"}'),
-- Dutch (nl)
(1, 'nl', '{"nl": "Makkelijk", "en": "Easy"}', '{"nl": "Eenvoudige woorden, weinig nieuwe woorden. Kindvriendelijk en vlot leesbaar.", "en": "Simple vocabulary, few new words. Child-friendly and easy to read."}',
  'Dagelijkse woorden, concreet en vertrouwd. Onderwerp altijd uitgeschreven (geen pro-drop). Verkleinwoorden (-je, -tje) passen goed.',
  3, 'Nauwelijks. Alleen heel simpele vergelijkingen.', 'Minimaal; veelvoorkomende uitdrukkingen (bijv. "opeens", "uiteindelijk").',
  '{"absurde situaties", "onomatopeeën", "grappige vergissingen"}',
  'Nieuw woord 2-3 keer in verschillende contexten. Verkleinwoorden voor warmte en herhaling.',
  '{"rennen", "kijken", "vinden", "klein", "blij", "huis"}'),
(2, 'nl', '{"nl": "Gemiddeld", "en": "Medium"}', '{"nl": "Gemiddelde woordenschat, wat nieuwe woorden. Evenwichtig en begrijpelijk.", "en": "Intermediate vocabulary, some new words. Balanced and clear."}',
  'Iets rijkere woordenschat; nog steeds vooral concreet. V2 en SOV correct. Onderwerp verplicht.',
  6, 'Vergelijkingen en eenvoudige metaforen. "Er/daar" waar natuurlijk.', 'Enkele veelvoorkomende uitdrukkingen (bijv. "bang zijn", "een handje helpen").',
  '{"absurde situaties", "eenvoudige woordspelingen", "misverstanden", "overdrijving"}',
  'Nieuw woord in 2 scènes; context variëren. Eenvoudige synoniemen in hetzelfde verhaal.',
  '{"avontuur", "mysterie", "dapper", "verrast", "beslissen", "helpen"}'),
(3, 'nl', '{"nl": "Moeilijk", "en": "Hard"}', '{"nl": "Rijkere woordenschat, meer nieuwe woorden. Uitdagend en verrijkend.", "en": "Richer vocabulary, more new words. Challenging and enriching."}',
  'Gevarieerd en genuanceerd lexicon. Meer literaire of beschrijvende termen. V2/SOV en er/daar natuurlijk.',
  10, 'Metaforen, vergelijkingen, lichte personificatie.', 'Idiomen en gezegden leeftijdsadequaat.',
  '{"woordspelingen", "lichte ironie", "absurde situaties", "subtiele dubbelzinnigheid"}',
  'Nieuwe woorden verspreid in het plot; versterken met context en synoniemen.',
  '{"onverwacht", "vastberadenheid", "verzoening", "ontdekking", "vrijgevigheid"}'),
-- Bosnian (bs)
(1, 'bs', '{"bs": "Lako", "en": "Easy"}', '{"bs": "Jednostavni rječnik, malo novih riječi. Prijateljski i tečno čitljivo.", "en": "Simple vocabulary, few new words. Child-friendly and easy to read."}',
  'Svakodnevne riječi, konkretne i poznate. Pro-drop. Aspekt (perfektiv/imperfektiv) dosljedan. Latinica.',
  3, 'Gotovo nema. Samo vrlo jednostavne usporedbe.', 'Minimalno; uobičajeni izrazi (npr. "odjednom", "na kraju").',
  '{"apsurdne situacije", "onomatopeje", "smiješne zabune"}',
  'Novu riječ 2-3 puta u različitim kontekstima. Padeži jednostavni.',
  '{"trčati", "gledati", "naći", "mali", "sretan", "kuća"}'),
(2, 'bs', '{"bs": "Srednje", "en": "Medium"}', '{"bs": "Srednji vokabular, nekoliko novih riječi. Uravnoteženo i razumljivo.", "en": "Intermediate vocabulary, some new words. Balanced and clear."}',
  'Nešto bogatiji vokabular; i dalje uglavnom konkretno. Aspekt za narativni tok. Pro-drop.',
  6, 'Usporedbe i jednostavne metafore.', 'Neke česte idiome (npr. "imati strah", "pomoći").',
  '{"apsurdne situacije", "jednostavne igre riječi", "nesporazumi", "pretjerivanje"}',
  'Nova riječ u 2 scene; mijenjati kontekst. Jednostavni sinonimi u istoj priči.',
  '{"avantura", "misterija", "hrabar", "iznenađen", "odlučiti", "pomoći"}'),
(3, 'bs', '{"bs": "Teško", "en": "Hard"}', '{"bs": "Bogatiji vokabular, više novih riječi. Izazovno i obogaćujuće.", "en": "Richer vocabulary, more new words. Challenging and enriching."}',
  'Raznovrstan i nijansiran rječnik. Više književnih ili opisnih pojmova. Aspekt i padeži prirodni.',
  10, 'Metafore, usporedbe, blaga personifikacija.', 'Idiomi i izreke prilagođeni dobi.',
  '{"igre riječi", "blaga ironija", "apsurdne situacije", "suptilna dvosmislenost"}',
  'Nove riječi raspoređene u radnji; pojačati kontekstom i sinonimima.',
  '{"neočekivan", "odlučnost", "pomirenje", "otkriće", "velikodušnost"}'),
-- Slovenian (sl)
(1, 'sl', '{"sl": "Lahko", "en": "Easy"}', '{"sl": "Preprost besednjak, malo novih besed. Prijazno in tekoče berljivo.", "en": "Simple vocabulary, few new words. Child-friendly and easy to read."}',
  'Vsakdanje besede, konkretne in znane. Pro-drop. Sestavljanke: ločene besede kjer velja. Dvojina za 2.',
  3, 'Skoraj nič. Samo zelo enostavne primerjave.', 'Minimalno; pogosti izrazi (npr. "nenadoma", "na koncu").',
  '{"absurdne situacije", "onomatopeje", "smešne zmede"}',
  'Novo besedo 2-3 krat v različnih kontekstih. Pazljivo na sestavljanke (ločene besede).',
  '{"teči", "gledati", "najti", "majhen", "vesel", "hiša"}'),
(2, 'sl', '{"sl": "Srednje", "en": "Medium"}', '{"sl": "Srednji besednjak, nekaj novih besed. Uravnoteženo in razumljivo.", "en": "Intermediate vocabulary, some new words. Balanced and clear."}',
  'Nekoliko bogatejši besednjak; še vedno večinoma konkreten. Sestavljanke: ne združevati, kjer je v slovenščini običajno ločeno. Dvojina.',
  6, 'Primerjave in enostavne metafore.', 'Nekaj pogostih idiomov (npr. "imeti strah", "pomagati").',
  '{"absurdne situacije", "enostavne besedne igre", "nesporazumi", "pretiravanje"}',
  'Nova beseda v 2 prizorih; spreminjati kontekst. Enostavni sinonim v isti zgodbi.',
  '{"avantura", "skrivnost", "pogumen", "presenečen", "odločiti", "pomagati"}'),
(3, 'sl', '{"sl": "Težko", "en": "Hard"}', '{"sl": "Bogatejši besednjak, več novih besed. Zahtevno in spodbudno.", "en": "Richer vocabulary, more new words. Challenging and enriching."}',
  'Raznovrsten in niansiran besednjak. Bolj literarni ali opisni izrazi. Sestavljanke: vedno ločene besede kjer je pravilo. Dvojina in sklanjatev naravna.',
  10, 'Metafore, primerjave, blaga personifikacija.', 'Idiomi in pregovori primerni starosti.',
  '{"besedne igre", "blaga ironija", "absurdne situacije", "subtilna dvoumnost"}',
  'Nove besede razporejene v zapletu; okrepiti s kontekstom in sinonimom. Ne združevati besed, ki morajo biti ločene.',
  '{"nepričakovan", "odločnost", "sprava", "odkritje", "radodarnost"}')
ON CONFLICT (difficulty_level, language) DO NOTHING;
