-- ============================================================
-- T-C1: DB-Übersetzungen — character_seeds
-- Adds 13 languages to labels: fr, es, nl, it, bs, tr, bg, ro, pl, lt, hu, ca, sl
-- (character_seeds had only de + en; needs all 13)
-- ============================================================

UPDATE character_seeds SET labels = labels || '{"fr": "Fille d''Afrique de l''Ouest", "es": "Niña de África Occidental", "nl": "West-Afrikaans meisje", "it": "Ragazza dell''Africa occidentale", "bs": "Djevojčica zapadne Afrike", "tr": "Batı Afrikalı Kız", "bg": "Момиче от Западна Африка", "ro": "Fată din Africa de Vest", "pl": "Dziewczynka z Afryki Zachodniej", "lt": "Vakarų Afrikos mergaitė", "hu": "Nyugat-afrikai lány", "ca": "Nena de l''Àfrica Occidental", "sl": "Deklica iz Zahodne Afrike"}'::jsonb WHERE seed_key = 'west_african_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon d''Asie de l''Est", "es": "Niño de Asia Oriental", "nl": "Oost-Aziatische jongen", "it": "Ragazzo dell''Asia orientale", "bs": "Dječak istočne Azije", "tr": "Doğu Asyalı Erkek Çocuk", "bg": "Момче от Източна Азия", "ro": "Băiat din Asia de Est", "pl": "Chłopiec z Azji Wschodniej", "lt": "Rytų Azijos berniukas", "hu": "Kelet-ázsiai fiú", "ca": "Nen de l''Àsia Oriental", "sl": "Fant iz Vzhodne Azije"}'::jsonb WHERE seed_key = 'east_asian_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille d''Asie du Sud", "es": "Niña de Asia del Sur", "nl": "Zuid-Aziatisch meisje", "it": "Ragazza dell''Asia meridionale", "bs": "Djevojčica južne Azije", "tr": "Güney Asyalı Kız", "bg": "Момиче от Южна Азия", "ro": "Fată din Asia de Sud", "pl": "Dziewczynka z Azji Południowej", "lt": "Pietų Azijos mergaitė", "hu": "Dél-ázsiai lány", "ca": "Nena del sud d''Àsia", "sl": "Deklica iz Južne Azije"}'::jsonb WHERE seed_key = 'south_asian_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon nordique", "es": "Niño nórdico", "nl": "Nordische jongen", "it": "Ragazzo nordico", "bs": "Nordijski dječak", "tr": "İskandinav Erkek Çocuk", "bg": "Скандинавско момче", "ro": "Băiat nordic", "pl": "Chłopiec nordycki", "lt": "Šiaurės šalių berniukas", "hu": "Északi fiú", "ca": "Nen nòrdic", "sl": "Severni fant"}'::jsonb WHERE seed_key = 'nordic_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille du Moyen-Orient", "es": "Niña de Oriente Medio", "nl": "Midden-Oosters meisje", "it": "Ragazza del Medio Oriente", "bs": "Djevojčica Bliskog istoka", "tr": "Orta Doğulu Kız", "bg": "Момиче от Близкия изток", "ro": "Fată din Orientul Mijlociu", "pl": "Dziewczynka z Bliskiego Wschodu", "lt": "Vidurio Rytų mergaitė", "hu": "Közel-keleti lány", "ca": "Nena de l''Orient Mitjà", "sl": "Deklica z Bližnjega vzhoda"}'::jsonb WHERE seed_key = 'middle_eastern_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon d''Amérique latine", "es": "Niño latinoamericano", "nl": "Latijns-Amerikaanse jongen", "it": "Ragazzo latinoamericano", "bs": "Dječak Latinske Amerike", "tr": "Latin Amerikalı Erkek Çocuk", "bg": "Момче от Латинска Америка", "ro": "Băiat latino-american", "pl": "Chłopiec z Ameryki Łacińskiej", "lt": "Lotynų Amerikos berniukas", "hu": "Latin-amerikai fiú", "ca": "Nen llatinoamericà", "sl": "Fant iz Latinske Amerike"}'::jsonb WHERE seed_key = 'latin_american_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille d''Europe de l''Est", "es": "Niña de Europa del Este", "nl": "Oost-Europees meisje", "it": "Ragazza dell''Europa orientale", "bs": "Djevojčica istočne Europe", "tr": "Doğu Avrupalı Kız", "bg": "Момиче от Източна Европа", "ro": "Fată din Europa de Est", "pl": "Dziewczynka z Europy Wschodniej", "lt": "Rytų Europos mergaitė", "hu": "Kelet-európai lány", "ca": "Nena d''Europa de l''Est", "sl": "Deklica iz Vzhodne Evrope"}'::jsonb WHERE seed_key = 'eastern_european_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon des Caraïbes", "es": "Niño caribeño", "nl": "Caribische jongen", "it": "Ragazzo caraibico", "bs": "Dječak Kariba", "tr": "Karayipli Erkek Çocuk", "bg": "Момче от Карибите", "ro": "Băiat din Caraibe", "pl": "Chłopiec z Karaibów", "lt": "Karibų berniukas", "hu": "Karibi fiú", "ca": "Nen del Carib", "sl": "Fant s Karibov"}'::jsonb WHERE seed_key = 'caribbean_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille d''Asie du Sud-Est", "es": "Niña del Sudeste Asiático", "nl": "Zuidoost-Aziatisch meisje", "it": "Ragazza del Sud-est asiatico", "bs": "Djevojčica jugoistočne Azije", "tr": "Güneydoğu Asyalı Kız", "bg": "Момиче от Югоизточна Азия", "ro": "Fată din Asia de Sud-Est", "pl": "Dziewczynka z Azji Południowo-Wschodniej", "lt": "Pietryčių Azijos mergaitė", "hu": "Délkelet-ázsiai lány", "ca": "Nena del sud-est d''Àsia", "sl": "Deklica iz Jugovzhodne Azije"}'::jsonb WHERE seed_key = 'southeast_asian_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon métis", "es": "Niño de herencia mixta", "nl": "Jongen met gemengde achtergrond", "it": "Ragazzo di origine mista", "bs": "Dječak miješanog porijekla", "tr": "Karışık Kökenli Erkek Çocuk", "bg": "Момче със смесено потекло", "ro": "Băiat cu patrimoniu mixt", "pl": "Chłopiec o mieszanym pochodzeniu", "lt": "Mišrios kilmės berniukas", "hu": "Vegyes származású fiú", "ca": "Nen d''orígens mixtes", "sl": "Fant mešanega porekla"}'::jsonb WHERE seed_key = 'mixed_heritage_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille aborigène d''Australie", "es": "Niña aborigen australiana", "nl": "Aboriginal meisje", "it": "Ragazza aborigena australiana", "bs": "Djevojčica australskih Aboridžina", "tr": "Avustralya Yerlisi Kız", "bg": "Момиче от австралийски аборигени", "ro": "Fată aborigenă australiană", "pl": "Dziewczynka aborygeńska", "lt": "Australijos aborigenų mergaitė", "hu": "Ausztrál őslakos lány", "ca": "Nena aborigen australiana", "sl": "Deklica avstralskih aboriginov"}'::jsonb WHERE seed_key = 'indigenous_australian_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon d''Europe centrale", "es": "Niño de Europa Central", "nl": "Midden-Europees jongen", "it": "Ragazzo dell''Europa centrale", "bs": "Dječak srednje Europe", "tr": "Orta Avrupalı Erkek Çocuk", "bg": "Момче от Централна Европа", "ro": "Băiat din Europa Centrală", "pl": "Chłopiec z Europy Środkowej", "lt": "Vidurio Europos berniukas", "hu": "Közép-európai fiú", "ca": "Nen d''Europa Central", "sl": "Fant iz Srednje Evrope"}'::jsonb WHERE seed_key = 'central_european_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille d''Afrique du Nord", "es": "Niña del Norte de África", "nl": "Noord-Afrikaans meisje", "it": "Ragazza del Nord Africa", "bs": "Djevojčica sjeverne Afrike", "tr": "Kuzey Afrikalı Kız", "bg": "Момиче от Северна Африка", "ro": "Fată din Africa de Nord", "pl": "Dziewczynka z Afryki Północnej", "lt": "Šiaurės Afrikos mergaitė", "hu": "Észak-afrikai lány", "ca": "Nena del nord d''Àfrica", "sl": "Deklica iz Severne Afrike"}'::jsonb WHERE seed_key = 'north_african_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon d''Europe de l''Ouest", "es": "Niño de Europa Occidental", "nl": "West-Europees jongen", "it": "Ragazzo dell''Europa occidentale", "bs": "Dječak zapadne Europe", "tr": "Batı Avrupalı Erkek Çocuk", "bg": "Момче от Западна Европа", "ro": "Băiat din Europa de Vest", "pl": "Chłopiec z Europy Zachodniej", "lt": "Vakarų Europos berniukas", "hu": "Nyugat-európai fiú", "ca": "Nen d''Europa Occidental", "sl": "Fant iz Zahodne Evrope"}'::jsonb WHERE seed_key = 'west_european_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille d''Afrique de l''Est", "es": "Niña de África Oriental", "nl": "Oost-Afrikaans meisje", "it": "Ragazza dell''Africa orientale", "bs": "Djevojčica istočne Afrike", "tr": "Doğu Afrikalı Kız", "bg": "Момиче от Източна Африка", "ro": "Fată din Africa de Est", "pl": "Dziewczynka z Afryki Wschodniej", "lt": "Rytų Afrikos mergaitė", "hu": "Kelet-afrikai lány", "ca": "Nena de l''Àfrica Oriental", "sl": "Deklica iz Vzhodne Afrike"}'::jsonb WHERE seed_key = 'east_african_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon d''Europe du Sud", "es": "Niño del Sur de Europa", "nl": "Zuid-Europees jongen", "it": "Ragazzo dell''Europa meridionale", "bs": "Dječak južne Europe", "tr": "Güney Avrupalı Erkek Çocuk", "bg": "Момче от Южна Европа", "ro": "Băiat din Europa de Sud", "pl": "Chłopiec z Europy Południowej", "lt": "Pietų Europos berniukas", "hu": "Dél-európai fiú", "ca": "Nen del sud d''Europa", "sl": "Fant iz Južne Evrope"}'::jsonb WHERE seed_key = 'south_european_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille d''Amérique du Sud", "es": "Niña de Sudamérica", "nl": "Zuid-Amerikaans meisje", "it": "Ragazza sudamericana", "bs": "Djevojčica Južne Amerike", "tr": "Güney Amerikalı Kız", "bg": "Момиче от Южна Америка", "ro": "Fată din America de Sud", "pl": "Dziewczynka z Ameryki Południowej", "lt": "Pietų Amerikos mergaitė", "hu": "Dél-amerikai lány", "ca": "Nena de l''Amèrica del Sud", "sl": "Deklica iz Južne Amerike"}'::jsonb WHERE seed_key = 'south_american_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon d''Asie centrale", "es": "Niño de Asia Central", "nl": "Centraal-Aziatische jongen", "it": "Ragazzo dell''Asia centrale", "bs": "Dječak srednje Azije", "tr": "Orta Asyalı Erkek Çocuk", "bg": "Момче от Централна Азия", "ro": "Băiat din Asia Centrală", "pl": "Chłopiec z Azji Środkowej", "lt": "Vidurio Azijos berniukas", "hu": "Közép-ázsiai fiú", "ca": "Nen de l''Àsia Central", "sl": "Fant iz Srednje Azije"}'::jsonb WHERE seed_key = 'central_asian_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille des îles du Pacifique", "es": "Niña de las islas del Pacífico", "nl": "Meisje van de Pacifische eilanden", "it": "Ragazza delle isole del Pacifico", "bs": "Djevojčica pacifičkih otoka", "tr": "Pasifik Adalı Kız", "bg": "Момиче от тихоокеанските острови", "ro": "Fată din insulele Pacificului", "pl": "Dziewczynka z wysp Pacyfiku", "lt": "Ramiojo vandenyno salų mergaitė", "hu": "Csendes-óceáni szigetek lány", "ca": "Nena de les illes del Pacífic", "sl": "Deklica s pacifiških otokov"}'::jsonb WHERE seed_key = 'pacific_islander_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Enfant nord-européen (genre neutre)", "es": "Niño/a del Norte de Europa (género neutro)", "nl": "Noord-Europees kind (genderneutraal)", "it": "Bambino nord-europeo (genere neutro)", "bs": "Dijete sjeverne Europe (neutralno)", "tr": "Kuzey Avrupalı Çocuk (nötr)", "bg": "Дете от Северна Европа (неутрално)", "ro": "Copil nord-european (neutru)", "pl": "Dziecko z Europy Północnej (neutralne)", "lt": "Šiaurės Europos vaikas (neutralus)", "hu": "Észak-európai gyerek (semleges)", "ca": "Nen del nord d''Europa (neutral)", "sl": "Otrok iz Severne Evrope (nevtralno)"}'::jsonb WHERE seed_key = 'northern_european_gender_neutral';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon rom", "es": "Niño romaní", "nl": "Roma jongen", "it": "Ragazzo rom", "bs": "Romski dječak", "tr": "Roman Erkek Çocuk", "bg": "Момче ром", "ro": "Băiat rom", "pl": "Chłopiec romski", "lt": "Romų berniukas", "hu": "Roma fiú", "ca": "Nen romaní", "sl": "Romski fant"}'::jsonb WHERE seed_key = 'romani_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille coréenne", "es": "Niña coreana", "nl": "Koreaans meisje", "it": "Ragazza coreana", "bs": "Korejska djevojčica", "tr": "Koreli Kız", "bg": "Корейско момиче", "ro": "Fată coreeană", "pl": "Dziewczynka koreańska", "lt": "Korėjiečių mergaitė", "hu": "Koreai lány", "ca": "Nena coreana", "sl": "Korejska deklica"}'::jsonb WHERE seed_key = 'korean_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon nigérian", "es": "Niño nigeriano", "nl": "Nigeriaanse jongen", "it": "Ragazzo nigeriano", "bs": "Nigerijski dječak", "tr": "Nijeryalı Erkek Çocuk", "bg": "Момче от Нигерия", "ro": "Băiat nigerian", "pl": "Chłopiec nigeryjski", "lt": "Nigerietis berniukas", "hu": "Nigériai fiú", "ca": "Nen nigerià", "sl": "Nigerijski fant"}'::jsonb WHERE seed_key = 'nigerian_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille turque", "es": "Niña turca", "nl": "Turks meisje", "it": "Ragazza turca", "bs": "Turska djevojčica", "tr": "Türk Kız", "bg": "Турско момиче", "ro": "Fată turcă", "pl": "Dziewczynka turecka", "lt": "Turkė mergaitė", "hu": "Török lány", "ca": "Nena turca", "sl": "Turška deklica"}'::jsonb WHERE seed_key = 'turkish_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon métis asiatique-européen", "es": "Niño de herencia asiático-europea", "nl": "Jongen met Aziatisch-Europese achtergrond", "it": "Ragazzo misto asiatico-europeo", "bs": "Dječak miješanog azijsko-europskog porijekla", "tr": "Asya-Avrupa Karışık Erkek Çocuk", "bg": "Момче със смесено азиатско-европейско потекло", "ro": "Băiat mixt asiatic-european", "pl": "Chłopiec o pochodzeniu azjatycko-europejskim", "lt": "Mišrios azijietiškos-europietiškos kilmės berniukas", "hu": "Ázsiai-európai vegyes fiú", "ca": "Nen d''orígens asiàtics i europeus", "sl": "Fant mešanega azijsko-evropskega porekla"}'::jsonb WHERE seed_key = 'mixed_asian_european_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille brésilienne", "es": "Niña brasileña", "nl": "Braziliaans meisje", "it": "Ragazza brasiliana", "bs": "Brazilijska djevojčica", "tr": "Brezilyalı Kız", "bg": "Бразилско момиче", "ro": "Fată braziliană", "pl": "Dziewczynka brazylijska", "lt": "Brazilė mergaitė", "hu": "Brazil lány", "ca": "Nena brasilera", "sl": "Brazilijska deklica"}'::jsonb WHERE seed_key = 'brazilian_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Fille scandinave", "es": "Niña escandinava", "nl": "Scandinavisch meisje", "it": "Ragazza scandinava", "bs": "Skandinavska djevojčica", "tr": "İskandinav Kız", "bg": "Скандинавско момиче", "ro": "Fată scandinavă", "pl": "Dziewczynka skandynawska", "lt": "Skandinavų mergaitė", "hu": "Skandináv lány", "ca": "Nena escandinava", "sl": "Skandinavska deklica"}'::jsonb WHERE seed_key = 'scandinavian_girl';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon d''Asie du Sud", "es": "Niño de Asia del Sur", "nl": "Zuid-Aziatische jongen", "it": "Ragazzo dell''Asia meridionale", "bs": "Dječak južne Azije", "tr": "Güney Asyalı Erkek Çocuk", "bg": "Момче от Южна Азия", "ro": "Băiat din Asia de Sud", "pl": "Chłopiec z Azji Południowej", "lt": "Pietų Azijos berniukas", "hu": "Dél-ázsiai fiú", "ca": "Nen del sud d''Àsia", "sl": "Fant iz Južne Azije"}'::jsonb WHERE seed_key = 'south_asian_boy';
UPDATE character_seeds SET labels = labels || '{"fr": "Enfant méditerranéen (genre neutre)", "es": "Niño/a mediterráneo (género neutro)", "nl": "Mediterraan kind (genderneutraal)", "it": "Bambino mediterraneo (genere neutro)", "bs": "Dijete Mediterana (neutralno)", "tr": "Akdenizli Çocuk (nötr)", "bg": "Дете от Средиземноморието (неутрално)", "ro": "Copil mediteranean (neutru)", "pl": "Dziecko śródziemnomorskie (neutralne)", "lt": "Viduržemio jūros vaikas (neutralus)", "hu": "Mediterrán gyerek (semleges)", "ca": "Nen mediterrani (neutral)", "sl": "Otrok Sredozemlja (nevtralno)"}'::jsonb WHERE seed_key = 'mediterranean_gender_neutral';
UPDATE character_seeds SET labels = labels || '{"fr": "Garçon amérindien", "es": "Niño indígena americano", "nl": "Inheems Amerikaans jongen", "it": "Ragazzo nativo americano", "bs": "Dječak američkih domorodaca", "tr": "Yerli Amerikalı Erkek Çocuk", "bg": "Момче от коренно американско семейство", "ro": "Băiat nativ american", "pl": "Chłopiec rdzenny amerykański", "lt": "Amerikos indėnų berniukas", "hu": "Amerikai őslakos fiú", "ca": "Nen indígena americà", "sl": "Fant ameriških staroselcev"}'::jsonb WHERE seed_key = 'indigenous_american_boy';

-- Mythical (12)
UPDATE character_seeds SET labels = labels || '{"fr": "Renarde rusée", "es": "Zorra sabia", "nl": "Wijze vos", "it": "Volpe saggia", "bs": "Mudra lisica", "tr": "Bilge Tilki", "bg": "Мъдра лисица", "ro": "Vulpe înțeleaptă", "pl": "Mądry lis", "lt": "Išmintingă lapė", "hu": "Bölcs róka", "ca": "Guineu sàvia", "sl": "Modra lisica"}'::jsonb WHERE seed_key = 'wise_fox';
UPDATE character_seeds SET labels = labels || '{"fr": "Petit dragon mal assuré", "es": "Dragón pequeño inseguro", "nl": "Kleine onzekere draak", "it": "Piccolo drago insicuro", "bs": "Mali nesiguran zmaj", "tr": "Küçük Güvensiz Ejderha", "bg": "Малък несигурен дракон", "ro": "Dragon mic nesigur", "pl": "Mały niepewny smok", "lt": "Mažas neįsitikinęs drakonas", "hu": "Bizonytalan kis sárkány", "ca": "Drac petit insegur", "sl": "Mali negotov zmaj"}'::jsonb WHERE seed_key = 'small_dragon';
UPDATE character_seeds SET labels = labels || '{"fr": "Chat de rue qui parle", "es": "Gato callejero que habla", "nl": "Sprekende straatkat", "it": "Gatto di strada parlante", "bs": "Govoreća ulična mačka", "tr": "Konuşan Sokak Kedisi", "bg": "Говореща улична котка", "ro": "Pisică de stradă vorbitoare", "pl": "Mówiący kot uliczny", "lt": "Kalbanti gatvės katė", "hu": "Beszélő utcai macska", "ca": "Gat de carrer que parla", "sl": "Govoreča ulična mačka"}'::jsonb WHERE seed_key = 'talking_cat';
UPDATE character_seeds SET labels = labels || '{"fr": "Esprit des bois timide", "es": "Espíritu del bosque tímido", "nl": "Verlegen bosgeest", "it": "Spirito del bosco timido", "bs": "Stidljivo šumsko biće", "tr": "Utangaç Orman Ruhu", "bg": "Плахо горско същество", "ro": "Spirit al pădurii sfios", "pl": "Nieśmiały duch lasu", "lt": "Kukli miško dvasia", "hu": "Félénk erdei szellem", "ca": "Esperit del bosc tímid", "sl": "Sramežljiv gozdni duh"}'::jsonb WHERE seed_key = 'forest_spirit';
UPDATE character_seeds SET labels = labels || '{"fr": "Petite souris courageuse", "es": "Valiente ratoncita", "nl": "Dappere kleine muis", "it": "Coraggioso topolino", "bs": "Hrabra mala miš", "tr": "Cesur Küçük Fare", "bg": "Храбра малка мишка", "ro": "Șoarece curajos", "pl": "Odważna mała mysz", "lt": "Drąsi maža pelė", "hu": "Bátor kis egér", "ca": "Petit ratolí valent", "sl": "Pogumna majhna miška"}'::jsonb WHERE seed_key = 'brave_mouse';
UPDATE character_seeds SET labels = labels || '{"fr": "Ours nuage doux", "es": "Oso de nubes gentil", "nl": "Zachte wolkenbeer", "it": "Orso nuvola gentile", "bs": "Nježni medvjed od oblaka", "tr": "Nazik Bulut Ayı", "bg": "Мек облачен мечка", "ro": "Urs noros blând", "pl": "Łagodny niedźwiedź z chmur", "lt": "Švelnus debesų lokys", "hu": "Gyengéd felhőmedve", "ca": "Ós de núvols amable", "sl": "Nežen oblačni medved"}'::jsonb WHERE seed_key = 'cloud_bear';
UPDATE character_seeds SET labels = labels || '{"fr": "Lièvre étoilé", "es": "Liebre estrellada", "nl": "Sterrenhaas", "it": "Lepre stellare", "bs": "Zvjezdani zec", "tr": "Yıldız Tavşanı", "bg": "Звездна зайка", "ro": "Iepure stelat", "pl": "Gwiezdny zając", "lt": "Žvaigždėtas kiškis", "hu": "Csillag nyúl", "ca": "Llebre estel·lada", "sl": "Zvezdni zajec"}'::jsonb WHERE seed_key = 'star_hare';
UPDATE character_seeds SET labels = labels || '{"fr": "Loutre de rivière joueuse", "es": "Nutria de río juguetona", "nl": "Speelse rivierotter", "it": "Lontra di fiume giocosa", "bs": "Razigrana riječna vidra", "tr": "Oynak Nehir Samuru", "bg": "Игрива речна видра", "ro": "Vidră de râu jucăușă", "pl": "Figlarna wydra rzeczna", "lt": "Žaismingas upinis ūdra", "hu": "Játékos folyami vidra", "ca": "Llúdria de riu juganera", "sl": "Igrava rečna vidra"}'::jsonb WHERE seed_key = 'river_otter';
UPDATE character_seeds SET labels = labels || '{"fr": "Vieille chouette prétendument sage", "es": "Búho viejo que finge sabiduría", "nl": "Oude zogenaamd wijze uil", "it": "Vecchia civetta presunta saggia", "bs": "Stara navodno mudra sova", "tr": "Sözde Bilge Yaşlı Baykuş", "bg": "Стара претендираща за мъдрост сова", "ro": "Bufniță bătrână pretins înțeleaptă", "pl": "Stara rzekomo mądra sowa", "lt": "Sena tariamai išmintingi pelėda", "hu": "Régi állítólagos bölcs bagoly", "ca": "Mussol vell que es fa el savi", "sl": "Stara domnevno modra sova"}'::jsonb WHERE seed_key = 'old_owl';
UPDATE character_seeds SET labels = labels || '{"fr": "Troll de pierre maladroit", "es": "Trol de piedra torpe", "nl": "Onhandige stenen trol", "it": "Troll di pietra goffo", "bs": "Nespretni kameni trol", "tr": "Sakar Taş Trol", "bg": "Плахо каменен трол", "ro": "Troll de piatră neîndemânatic", "pl": "Niezdarny kamienny troll", "lt": "Nerangus akmeninis trolis", "hu": "Ügyetlen kőtroll", "ca": "Troll de pedra maldestre", "sl": "Okoren kamniti trol"}'::jsonb WHERE seed_key = 'stone_troll';
UPDATE character_seeds SET labels = labels || '{"fr": "Fée du vent", "es": "Hada del viento", "nl": "Windfee", "it": "Fata del vento", "bs": "Vjetarska vila", "tr": "Rüzgar Perisi", "bg": "Вятърна фея", "ro": "Zână a vântului", "pl": "Wróżka wiatru", "lt": "Vėjo fėja", "hu": "Szél tündér", "ca": "Fada del vent", "sl": "Vetrova vila"}'::jsonb WHERE seed_key = 'wind_fairy';
UPDATE character_seeds SET labels = labels || '{"fr": "Minuscule gnome champignon", "es": "Gnomo de setas minúsculo", "nl": "Minuscule paddenstoelengnom", "it": "Minuscolo gnomo fungo", "bs": "Sićušni gnome gljiva", "tr": "Minik Mantar Cücesi", "bg": "Малък гном с гъба", "ro": "Gnom ciupercă minuscul", "pl": "Malutki gnome grzybek", "lt": "Mažyčias grybų gnomas", "hu": "Apró gombagnóm", "ca": "Nano de bolets minúscul", "sl": "Majhen gnom gob"}'::jsonb WHERE seed_key = 'mushroom_gnome';

-- Sidekicks (10)
UPDATE character_seeds SET labels = labels || '{"fr": "Sceptique loyal", "es": "Escéptico leal", "nl": "Loyale scepticus", "it": "Scettico leale", "bs": "Odan skeptik", "tr": "Sadık Şüpheci", "bg": "Лоялен скептик", "ro": "Sceptic loial", "pl": "Lojalny sceptyk", "lt": "Ištikimas skeptikas", "hu": "Hűséges szkeptikus", "ca": "Escèptic leal", "sl": "Zvest skeptik"}'::jsonb WHERE seed_key = 'loyal_skeptic';
UPDATE character_seeds SET labels = labels || '{"fr": "Comique", "es": "Alivio cómico", "nl": "Comische noot", "it": "Sollievo comico", "bs": "Komično olakšanje", "tr": "Komedi Rahatlaması", "bg": "Комично облекчение", "ro": "Ușurare comică", "pl": "Komiczna odskocznia", "lt": "Kominis atsipalaidavimas", "hu": "Komikus megkönnyebbülés", "ca": "Alleuj còmic", "sl": "Komično olajšanje"}'::jsonb WHERE seed_key = 'comic_relief';
UPDATE character_seeds SET labels = labels || '{"fr": "Génie silencieux", "es": "Genio callado", "nl": "Stille genie", "it": "Genio silenzioso", "bs": "Tihi genijalac", "tr": "Sessiz Dahı", "bg": "Тих гений", "ro": "Geniu tăcut", "pl": "Cichy geniusz", "lt": "Tylus geniusas", "hu": "Csendes zseni", "ca": "Geni callat", "sl": "Tihi genij"}'::jsonb WHERE seed_key = 'quiet_genius';
UPDATE character_seeds SET labels = labels || '{"fr": "Débutant enthousiaste", "es": "Novato entusiasta", "nl": "Enthousiaste beginner", "it": "Principiante entusiasta", "bs": "Oduševljeni početnik", "tr": "Hevesli Acemi", "bg": "Ентусиазиран новак", "ro": "Începător entuziast", "pl": "Entuzjastyczny nowicjusz", "lt": "Entuziastingas naujokas", "hu": "Lelkes kezdő", "ca": "Novell entusiasta", "sl": "Navdušen novinec"}'::jsonb WHERE seed_key = 'enthusiastic_rookie';
UPDATE character_seeds SET labels = labels || '{"fr": "Expert réticent", "es": "Experto reacio", "nl": "Terughoudende expert", "it": "Esperto riluttante", "bs": "Nevoljni stručnjak", "tr": "Gönülsüz Uzman", "bg": "Неохотен експерт", "ro": "Expert reticent", "pl": "Niechętny ekspert", "lt": "Nepasiduojantis ekspertas", "hu": "Vonakodó szakértő", "ca": "Expert reticent", "sl": "Nenaklonjen strokovnjak"}'::jsonb WHERE seed_key = 'reluctant_expert';
UPDATE character_seeds SET labels = labels || '{"fr": "Protecteur féroce", "es": "Protector feroz", "nl": "Felle beschermer", "it": "Protettore feroce", "bs": "Žestoki zaštitnik", "tr": "Azılı Koruyucu", "bg": "Яростен защитник", "ro": "Protector feroce", "pl": "Zacięty obrońca", "lt": "Žiaurus gynėjas", "hu": "Vad védelmező", "ca": "Protector feroç", "sl": "Divji zaščitnik"}'::jsonb WHERE seed_key = 'fierce_protector';
UPDATE character_seeds SET labels = labels || '{"fr": "Le traducteur", "es": "El traductor", "nl": "De vertaler", "it": "Il traduttore", "bs": "Prevodilac", "tr": "Çevirmen", "bg": "Преводачът", "ro": "Traductorul", "pl": "Tłumacz", "lt": "Vertėjas", "hu": "A fordító", "ca": "El traductor", "sl": "Prevajalec"}'::jsonb WHERE seed_key = 'the_translator';
UPDATE character_seeds SET labels = labels || '{"fr": "Agent du chaos", "es": "Agente del caos", "nl": "Chaosagent", "it": "Agente del caos", "bs": "Agent haosa", "tr": "Kaos Ajanı", "bg": "Агент на хаоса", "ro": "Agent al haosului", "pl": "Agent chaosu", "lt": "Chaoso agentas", "hu": "Káoszügynök", "ca": "Agent del caos", "sl": "Agent kaosa"}'::jsonb WHERE seed_key = 'chaos_agent';
UPDATE character_seeds SET labels = labels || '{"fr": "Le documentariste", "es": "El documentalista", "nl": "De documentairemaker", "it": "Il documentarista", "bs": "Dokumentarist", "tr": "Belgeselci", "bg": "Документалистът", "ro": "Documentaristul", "pl": "Dokumentalista", "lt": "Dokumentuotojas", "hu": "A dokumentáló", "ca": "El documentalista", "sl": "Dokumentarist"}'::jsonb WHERE seed_key = 'the_documentarian';
UPDATE character_seeds SET labels = labels || '{"fr": "Compagnon animal", "es": "Compañero animal", "nl": "Dierenmaatje", "it": "Compagno animale", "bs": "Životinjski drug", "tr": "Hayvan Arkadaşı", "bg": "Животно спътник", "ro": "Companion animal", "pl": "Towarzysz zwierzę", "lt": "Gyvūnas draugas", "hu": "Állati társ", "ca": "Company animal", "sl": "Živalski spremljevalec"}'::jsonb WHERE seed_key = 'animal_companion';

-- Antagonists (8)
UPDATE character_seeds SET labels = labels || '{"fr": "Le tyran apeuré", "es": "El matón asustado", "nl": "De bange bullebak", "it": "Il bullo spaventato", "bs": "Prestrašeni nasilnik", "tr": "Korkak Zorba", "bg": "Страхливият побойник", "ro": "Bătăușul înfricat", "pl": "Zastraszony dręczyciel", "lt": "Išgąstęs tyranas", "hu": "A félénk zsarnok", "ca": "L''assetjador poruc", "sl": "Prestrašeni nasilnež"}'::jsonb WHERE seed_key = 'the_scared_bully';
UPDATE character_seeds SET labels = labels || '{"fr": "L''ami jaloux", "es": "El amigo celoso", "nl": "De jaloerse vriend", "it": "L''amico geloso", "bs": "Ljubomorni prijatelj", "tr": "Kıskanç Arkadaş", "bg": "Ревнивият приятел", "ro": "Prietenul gelos", "pl": "Zazdrosny przyjaciel", "lt": "Pavydus draugas", "hu": "A féltékeny barát", "ca": "L''amic gelós", "sl": "Ljubosumen prijatelj"}'::jsonb WHERE seed_key = 'the_jealous_friend';
UPDATE character_seeds SET labels = labels || '{"fr": "Le contrôleur bien intentionné", "es": "El controlador bienintencionado", "nl": "De goedbedoelende controleur", "it": "Il controllore benintenzionato", "bs": "Dobronamjerni kontrolor", "tr": "İyi Niyetli Kontrolcü", "bg": "Добронамереният контролор", "ro": "Controlorul bine-intenționat", "pl": "Kontroler z dobrymi intencjami", "lt": "Geranoriškas kontrolierius", "hu": "A jószándékú irányító", "ca": "El controlador benintencionat", "sl": "Dobronamerni nadzornik"}'::jsonb WHERE seed_key = 'the_well_meaning_controller';
UPDATE character_seeds SET labels = labels || '{"fr": "L''adorateur des règles", "es": "El adorador de reglas", "nl": "De regelaanbidder", "it": "L''adoratore delle regole", "bs": "Obožavatelj pravila", "tr": "Kuralara Tapan", "bg": "Почитателят на правилата", "ro": "Adoratorul regulilor", "pl": "Wielbiciel reguł", "lt": "Taisyklių garbintojas", "hu": "A szabályimádó", "ca": "L''adorador de regles", "sl": "Častilec pravil"}'::jsonb WHERE seed_key = 'the_rule_worshipper';
UPDATE character_seeds SET labels = labels || '{"fr": "Le rival", "es": "El rival", "nl": "De rivaal", "it": "Il rivale", "bs": "Rival", "tr": "Rakip", "bg": "Съперникът", "ro": "Rivalul", "pl": "Rywal", "lt": "Rivalas", "hu": "A rivális", "ca": "El rival", "sl": "Tekmec"}'::jsonb WHERE seed_key = 'the_rival';
UPDATE character_seeds SET labels = labels || '{"fr": "Le filou", "es": "El tramposo", "nl": "De bedrieger", "it": "L''imbroglione", "bs": "Prevarant", "tr": "Düzenbaz", "bg": "Измамникът", "ro": "Înșelătorul", "pl": "Oszust", "lt": "Sukčius", "hu": "A csaló", "ca": "L''enganyador", "sl": "Prevarant"}'::jsonb WHERE seed_key = 'the_trickster';
UPDATE character_seeds SET labels = labels || '{"fr": "Le meneur de bande", "es": "El líder de la manada", "nl": "De roedelleider", "it": "Il capobranco", "bs": "Vođa grupe", "tr": "Sürü Lideri", "bg": "Водещият на стадото", "ro": "Liderul haitei", "pl": "Przywódca stada", "lt": "Bandos lyderis", "hu": "A falkavezér", "ca": "El líder de la manada", "sl": "Vodja tropa"}'::jsonb WHERE seed_key = 'the_pack_leader';
UPDATE character_seeds SET labels = labels || '{"fr": "L''insouciant", "es": "El despistado", "nl": "De onoplettende", "it": "Lo sconsiderato", "bs": "Nemarni", "tr": "Düşüncesiz", "bg": "Безгрижният", "ro": "Cel neatent", "pl": "Nieuważny", "lt": "Atsainus", "hu": "A gondatlan", "ca": "El descurat", "sl": "Neomajhen"}'::jsonb WHERE seed_key = 'the_careless_one';
