-- ============================================================
-- Language-specific story rules: pt, tr, pl
-- Adds rows to age_rules, theme_rules, difficulty_rules.
-- Content is language-specific; grammar guidance tailored to
-- each language (PT-PT pro-drop, Turkish agglutination/SOV,
-- Polish cases/aspect).
-- emotion_rules already seeded from EN in
-- 20260217_language_expansion_beta.sql.
-- Idempotent: ON CONFLICT DO NOTHING.
-- ============================================================

-- ============================================================
-- 1. age_rules (4 bands per language: 6-7, 8-9, 10-11, 12-13)
-- ============================================================

-- ---------- PORTUGUESE (pt): European PT-PT, pro-drop, articles o/a/os/as, subjunctive ----------
INSERT INTO age_rules (
  min_age, max_age, language,
  max_sentence_length, allowed_tenses, sentence_structures,
  min_word_count, max_word_count,
  paragraph_length, dialogue_ratio, narrative_perspective,
  narrative_guidelines, example_sentences
) VALUES
(6, 7, 'pt', 10,
  '{"presente do indicativo", "pretérito perfeito simples", "perífrase ir + infinitivo"}',
  'Frases simples. Pro-drop: NÃO repetir o pronome sujeito (português é pro-drop: "correu" e não "ele correu"). Máximo 2 orações por frase. Conectores: quando, porque.',
  250, 400,
  '2-3 frases por parágrafo',
  '35-45% diálogo. Usar travessão (—) para diálogo, NÃO aspas.',
  'Terceira pessoa (evitar ele/ela se o verbo já indica a pessoa)',
  'Vocabulário quotidiano e concreto. NUNCA usar pronomes sujeito redundantes. Emoções simples (contente, triste, zangado). Um problema e a sua solução. Artigos definidos (o/a/os/as) corretos. Conectores temporais (primeiro, depois, no fim). Diálogo com travessão (—). Descrições sensoriais simples. Diminutivos (-inho/-inha) para registo infantil. IMPORTANTE: usar PT-PT (guardar, pequeno-almoço, autocarro, telemóvel) e NÃO PT-BR.',
  '{"A Mia encontrou um gatinho no jardim.", "— Posso ficar com ele? perguntou a Mia.", "No dia seguinte foi buscar comida para o gato.", "Quando ronronava, a Mia ficava muito contente."}'),
(8, 9, 'pt', 14,
  '{"presente", "pretérito perfeito", "pretérito imperfeito", "futuro simples", "conjuntivo presente (introdução)"}',
  'Mistura de frases simples e subordinadas com que, quando, porque, se, como. Pro-drop obrigatório: omitir eu/ele/ela quando o verbo já indica. Máximo três orações.',
  400, 600,
  '3-4 frases por parágrafo',
  '30-40% diálogo. Travessão (—) para diálogo.',
  'Terceira pessoa; primeira pessoa possível. Pro-drop.',
  'Vocabulário mais rico; continua a omitir pronomes sujeito. Conjuntivo apropriado em orações subordinadas (ex. "queria que viesse"). Diminutivos (-inho, -inha) para afetividade. Artigos definidos corretos. Várias peripécias antes do desfecho. Inferências simples. Humor adequado. PT-PT sempre.',
  '{"Enquanto os outros dormiam, a Luna olhava as estrelas pela janela.", "Sempre tinha sonhado voar como os pássaros.", "Se ao menos pudesse encontrar o mapa que o avô tinha escondido...", "— Nunca me vou render, sussurrou apertando o medalhão."}'),
(10, 11, 'pt', 18,
  '{"presente", "pretérito perfeito", "imperfeito", "mais-que-perfeito", "futuro", "condicional", "conjuntivo presente e imperfeito"}',
  'Frases complexas com subordinadas. Pro-drop: não repetir sujeitos. Conjuntivo em desejos, dúvidas, juízos de valor. Discurso direto e indireto.',
  600, 900,
  '4-5 frases por parágrafo',
  '25-35% diálogo. Travessão (—).',
  'Terceira ou primeira pessoa. Pro-drop consistente.',
  'Vocabulário rico e matizado. Conjuntivo natural em literatura infantil. Figuras de estilo simples. Personagens com dilemas morais. Artigos e concordância corretos. Ritmo narrativo variável. Temas profundos. Finais abertos possíveis. PT-PT.',
  '{"Embora a tempestade rugisse lá fora, o Leo não pensava abandonar a expedição.", "De repente percebeu que o verdadeiro tesouro eram os amigos do caminho.", "— Achas que podemos mudar as coisas? perguntou a Sara.", "O ancião sorriu como se tivesse esperado aquela pergunta."}'),
(12, 13, 'pt', 18,
  '{"presente", "pretérito perfeito", "imperfeito", "mais-que-perfeito", "futuro", "condicional", "conjuntivo presente e imperfeito"}',
  'Frases complexas com subordinadas. Pro-drop. Conjuntivo em desejos, dúvidas, juízos de valor. Discurso direto e indireto.',
  600, 900,
  '4-5 frases por parágrafo',
  '25-35% diálogo.',
  'Terceira ou primeira pessoa. Pro-drop.',
  'Igual a 10-11 com maior profundidade. Conjuntivo e pro-drop naturais. Diminutivos para proximidade. Artigos corretos. PT-PT.',
  '{"Embora a tempestade rugisse lá fora, o Leo não pensava abandonar a expedição.", "Percebeu que o verdadeiro tesouro eram os amigos.", "— Achas que podemos mudar as coisas? perguntou a Sara.", "O ancião sorriu como se tivesse esperado aquela pergunta."}')
ON CONFLICT (min_age, max_age, language) DO NOTHING;

-- ---------- TURKISH (tr): agglutinative, SOV, vowel harmony, NO articles, suffix-based ----------
INSERT INTO age_rules (
  min_age, max_age, language,
  max_sentence_length, allowed_tenses, sentence_structures,
  min_word_count, max_word_count,
  paragraph_length, dialogue_ratio, narrative_perspective,
  narrative_guidelines, example_sentences
) VALUES
(6, 7, 'tr', 10,
  '{"geniş zaman (şimdiki)", "di''li geçmiş zaman (-dı/-di)", "gelecek zaman (-ecek/-acak)"}',
  'Basit cümleler. SOV sırası: özne + nesne + yüklem. Türkçede artikel (a/the) YOKTUR. Ünlü uyumuna dikkat (büyük/küçük ünlü uyumu). Maksimum 2 yan cümle. Soru eki mi/mı/mu/mü ayrı yazılır.',
  250, 400,
  'Paragraf başına 2-3 cümle',
  '%35-45 diyalog',
  'Üçüncü kişi (o)',
  'Günlük ve somut sözcük dağarcığı. SOV: yüklem her zaman sonda. Ekler doğru ünlü uyumuyla. Basit duygular (mutlu, üzgün, kızgın). Bir sorun ve çözümü. Zaman bağlaçları (önce, sonra, en sonunda). Basit duyusal betimlemeler. -cık/-cik küçültme ekleri.',
  '{"Mia bahçede bir kedi yavrusu buldu.", "— Onu alabilir miyim? diye sordu Mia.", "Ertesi gün kedi için yiyecek aramaya gitti.", "Kedi mırlayınca Mia çok mutlu oldu."}'),
(8, 9, 'tr', 14,
  '{"geniş zaman", "di''li geçmiş", "miş''li geçmiş", "gelecek zaman", "şart kipi (-se/-sa, giriş)"}',
  'Basit ve birleşik cümlelerin karışımı. SOV korunur. Ki bağlacı, -dığında, -ınca, çünkü ile yan cümleler. Ünlü uyumu tutarlı. Üç yan cümleye kadar.',
  400, 600,
  'Paragraf başına 3-4 cümle',
  '%30-40 diyalog',
  'Üçüncü kişi; birinci kişi mümkün.',
  'Daha zengin sözcük dağarcığı. SOV tutarlı. -miş''li geçmiş zaman duyumsal/rivayetsel kullanımda. Ünlü uyumu doğru. Atmosfer betimlemeleri. Birden fazla olay örgüsü dönüşü. Basit çıkarımlar. Yaşa uygun mizah.',
  '{"Diğerleri uyurken Luna pencereden yıldızlara bakıyordu.", "Her zaman kuşlar gibi uçmayı hayal etmişti.", "Keşke dedenin sakladığı haritayı bulabilse...", "— Asla pes etmeyeceğim, diye fısıldadı madalyonu sıkarak."}'),
(10, 11, 'tr', 18,
  '{"geniş zaman", "di''li geçmiş", "miş''li geçmiş", "gelecek zaman", "şart kipi", "gereklilik kipi (-malı/-meli)", "istek kipi (-e/-a)"}',
  'Karmaşık cümleler, yan cümlelerle. SOV korunur. Dolaylı ve dolaysız anlatım. Ünlü uyumu titizlikle uygulanır.',
  600, 900,
  'Paragraf başına 4-5 cümle',
  '%25-35 diyalog',
  'Üçüncü veya birinci kişi.',
  'Zengin ve nüanslı sözcük dağarcığı. Doğru SOV ve ünlü uyumu. Basit söz sanatları. Ahlaki ikilemler yaşayan karakterler. Değişken anlatı ritmi. Derin temalar. Açık uçlu sonuçlar mümkün.',
  '{"Dışarıda fırtına kükrüyor olsa da Leo keşif gezisini bırakmayı düşünmüyordu.", "Birden gerçek hazinenin yol arkadaşları olduğunu anladı.", "— Bir şeyleri değiştirebileceğimize inanıyor musun? diye sordu Sara.", "Yaşlı adam sanki o soruyu bekliyormuş gibi gülümsedi."}'),
(12, 13, 'tr', 18,
  '{"geniş zaman", "di''li geçmiş", "miş''li geçmiş", "gelecek zaman", "şart kipi", "gereklilik kipi", "istek kipi"}',
  'Karmaşık cümleler. SOV. Dolaylı ve dolaysız anlatım. Ünlü uyumu titiz.',
  600, 900,
  'Paragraf başına 4-5 cümle',
  '%25-35 diyalog',
  'Üçüncü veya birinci kişi.',
  '10-11 ile aynı, daha derin. SOV ve ünlü uyumu doğal. Küçültme ekleri sıcaklık için.',
  '{"Fırtına kükrüyor olsa da Leo keşif gezisinden vazgeçmiyordu.", "Gerçek hazinenin arkadaşları olduğunu anladı.", "— Bir şeyleri değiştirebileceğimize inanıyor musun? diye sordu Sara.", "Yaşlı adam sanki o soruyu bekliyormuş gibi gülümsedi."}')
ON CONFLICT (min_age, max_age, language) DO NOTHING;

-- ---------- POLISH (pl): NOT pro-drop (optional); 7 cases; verb aspect pairs; gendered nouns ----------
INSERT INTO age_rules (
  min_age, max_age, language,
  max_sentence_length, allowed_tenses, sentence_structures,
  min_word_count, max_word_count,
  paragraph_length, dialogue_ratio, narrative_perspective,
  narrative_guidelines, example_sentences
) VALUES
(6, 7, 'pl', 10,
  '{"czas teraźniejszy", "czas przeszły (dokonany i niedokonany)", "czas przyszły (będę + bezokolicznik)"}',
  'Proste zdania. Zaimki osobowe opcjonalne (polski dopuszcza pro-drop, ale nie jest obowiązkowy). Aspekt: dokonany dla zakończonych czynności, niedokonany dla trwających. Maksymalnie 2 zdania podrzędne. Przypadki: proste formy (mianownik, biernik).',
  250, 400,
  '2-3 zdania na akapit',
  '35-45% dialog',
  'Trzecia osoba (on/ona)',
  'Codzienny i konkretny słownik. Aspekt dokonany/niedokonany konsekwentny. Przypadki proste (odpowiednie dla dzieci). Emocje proste (wesoły, smutny, zły). Jeden problem i rozwiązanie. Łączniki czasowe (najpierw, potem, w końcu). Zdrobnienia (-ek, -ka, -ko) naturalne w języku dziecięcym. Proste opisy zmysłowe.',
  '{"Mia znalazła kotka w ogrodzie.", "— Czy mogę go zatrzymać? zapytała Mia.", "Następnego dnia poszła szukać jedzenia dla kota.", "Kiedy mruczał, Mia była bardzo szczęśliwa."}'),
(8, 9, 'pl', 14,
  '{"czas teraźniejszy", "czas przeszły dokonany", "czas przeszły niedokonany", "czas przyszły", "tryb warunkowy (wprowadzenie)"}',
  'Mieszanka zdań prostych i złożonych z że, kiedy, bo, jeśli, jak. Aspekt: para dokonana/niedokonana konsekwentna w narracji. Przypadki jasne. Do trzech zdań podrzędnych.',
  400, 600,
  '3-4 zdania na akapit',
  '30-40% dialog',
  'Trzecia osoba; pierwsza osoba możliwa.',
  'Bogatszy słownik. Aspekt dla rytmu narracji (niedokonany dla tła, dokonany dla zdarzeń). Przypadki poprawne. Zdrobnienia dla ciepła. Opisy atmosfery. Więcej zwrotów akcji. Proste wnioskowanie. Humor odpowiedni do wieku.',
  '{"Kiedy inni spali, Luna patrzyła na gwiazdy przez okno.", "Zawsze marzyła o lataniu jak ptaki.", "Gdyby tylko mogła znaleźć mapę, którą dziadek ukrył...", "— Nigdy się nie poddam, szepnęła ściskając medalion."}'),
(10, 11, 'pl', 18,
  '{"czas teraźniejszy", "czas przeszły dokonany i niedokonany", "czas zaprzeszły", "czas przyszły", "tryb warunkowy", "tryb rozkazujący"}',
  'Złożone zdania z podrzędnymi. Aspekt konsekwentny. Przypadki poprawne. Mowa zależna i niezależna.',
  600, 900,
  '4-5 zdań na akapit',
  '25-35% dialog',
  'Trzecia lub pierwsza osoba.',
  'Bogaty, niuansowany słownik. Aspekt i przypadki naturalne. Proste figury stylistyczne. Postacie z dylematami moralnymi. Zmienny rytm narracji. Głębokie tematy. Otwarte zakończenia możliwe.',
  '{"Choć burza szalała na zewnątrz, Leo nie zamierzał porzucić wyprawy.", "Nagle zrozumiał, że prawdziwym skarbem byli przyjaciele z drogi.", "— Wierzysz, że możemy coś zmienić? zapytała Sara.", "Starzec uśmiechnął się, jakby czekał na to pytanie."}'),
(12, 13, 'pl', 18,
  '{"czas teraźniejszy", "czas przeszły dokonany i niedokonany", "czas zaprzeszły", "czas przyszły", "tryb warunkowy", "tryb rozkazujący"}',
  'Złożone zdania. Aspekt i przypadki naturalne. Mowa zależna i niezależna.',
  600, 900,
  '4-5 zdań na akapit',
  '25-35% dialog',
  'Trzecia lub pierwsza osoba.',
  'Jak 10-11 z większą głębią. Aspekt i przypadki naturalne. Zdrobnienia dla bliskości.',
  '{"Choć burza szalała, Leo nie porzucił wyprawy.", "Zrozumiał, że prawdziwym skarbem byli przyjaciele.", "— Wierzysz, że możemy coś zmienić? zapytała Sara.", "Starzec uśmiechnął się, jakby czekał na to pytanie."}')
ON CONFLICT (min_age, max_age, language) DO NOTHING;

-- ============================================================
-- 2. theme_rules (6 themes × 3 languages)
-- ============================================================

INSERT INTO theme_rules (theme_key, language, labels, plot_templates, setting_descriptions, character_archetypes, sensory_details, typical_conflicts) VALUES
-- Portuguese (pt) – cultural elements: sea/explorers, tiles (azulejos), fado, pastéis de nata
('fantasy', 'pt', '{"de": "Märchen & Fantasie", "fr": "Contes & Fantaisie", "en": "Fairy Tales & Fantasy", "pt": "Contos e fantasia"}',
  '{"Uma criança descobre um objeto mágico que a leva a um mundo encantado", "Uma criatura mágica precisa de ajuda e só a criança pode salvar o reino", "Um feitiço tem de ser quebrado antes do pôr do sol com três provas", "A criança encontra uma porta secreta para um mundo onde os animais falam"}',
  'Florestas encantadas com árvores luminosas, castelos flutuantes nas nuvens, aldeias debaixo de cogumelos, grutas de cristal, ilhas ligadas por pontes de arco-íris, praias mágicas com conchas que cantam.',
  '{"O aprendiz de feiticeiro desastrado", "A fada travessa", "O dragão bondoso", "O rei/a rainha em apuros", "O animal guia que fala", "O guardião misterioso"}',
  'Brilhos dourados, pó de estrelas, cheiro a flores mágicas, som de sininhos, texturas de musgo e seda, maresia encantada.',
  '{"A magia desaparece e tem de ser restaurada", "Um bruxo mau ameaça o mundo encantado", "A criança tem de escolher entre voltar para casa ou ficar", "Um mal-entendido entre criaturas mágicas causa caos"}'),
('action', 'pt', '{"de": "Abenteuer & Action", "fr": "Aventure & Action", "en": "Adventure & Action", "pt": "Aventura e ação"}',
  '{"A criança encontra um mapa do tesouro e parte em expedição com amigos", "Um mistério no bairro tem de ser resolvido antes das férias acabarem", "A criança vive uma aventura inesperada numa visita de estudo", "Uma corrida contra o tempo para salvar algo ou alguém"}',
  'Selvas frondosas, grutas com archotes, barcos piratas, montanhas nevadas, ruínas com passagens secretas, falésias junto ao oceano Atlântico.',
  '{"O explorador corajoso", "O melhor amigo leal", "O rival que se torna aliado", "O mentor sábio", "A personagem cómica"}',
  'Vento no cabelo, coração acelerado, cheiro a terra molhada, passos apressados, sol ardente, salitre no ar.',
  '{"Um obstáculo natural bloqueia o caminho", "Um rival quer chegar primeiro", "O grupo tem de se separar e reunir-se", "Uma traição aparente esconde boa intenção"}'),
('animals', 'pt', '{"de": "Tiergeschichten", "fr": "Histoires d''animaux", "en": "Animal Stories", "pt": "Histórias de animais"}',
  '{"Um animal perdido procura o caminho de volta à família", "Um grupo de animais diferentes tem de cooperar para superar um desafio", "Um animal jovem tem de provar o seu valor", "A amizade inesperada entre duas espécies muito diferentes"}',
  'Quintas tranquilas ao amanhecer, bosques com tocas e ninhos, oceanos e recifes, savana africana, jardins secretos com lagos, costa atlântica com gaivotas.',
  '{"O animalzinho corajoso", "O ancião sábio do grupo", "O animal desconfiado que aprende a confiar", "O companheiro desastrado mas querido"}',
  'Pelo macio, canto dos pássaros, folhas que estalam, cheiro a terra e erva, sol no pelo, maresia.',
  '{"Um predador ameaça o grupo", "As estações mudam e é preciso migrar ou adaptar-se", "Uma cria separa-se da mãe", "Dois grupos reclamam o mesmo território"}'),
('everyday', 'pt', '{"de": "Alltag & Gefühle", "fr": "Quotidien & Émotions", "en": "Everyday & Feelings", "pt": "Dia a dia e sentimentos"}',
  '{"Uma criança enfrenta uma mudança e aprende a adaptar-se", "Um mal-entendido entre amigos que se resolve com conversa", "A criança descobre uma paixão ou talento inesperado", "O primeiro dia num ambiente novo (escola, bairro, atividade)"}',
  'Casas acolhedoras, pátios de recreio, parques, salas de aula, quartos de criança, cozinhas à hora do lanche.',
  '{"A criança sensível e observadora", "O recém-chegado tímido", "O irmão ou irmã mais velho protetor", "O amigo fiel", "O vizinho peculiar"}',
  'Cheiro a bolo no forno, risos de crianças, luz suave da tarde, textura de lápis de cera, sabor a chocolate quente, aroma a pastéis de nata.',
  '{"Um amigo muda-se e é preciso lidar com a despedida", "Uma criança sente-se diferente", "Um segredo que pesa e tem de ser partilhado", "Ciúmes por um bebé ou um novo colega"}'),
('humor', 'pt', '{"de": "Humor & Chaos", "fr": "Humour & Chaos", "en": "Humor & Chaos", "pt": "Humor e caos"}',
  '{"Tudo corre mal quando uma criança tenta preparar uma surpresa", "Um objeto do dia a dia começa a fazer coisas absurdas", "Um animal de estimação causa uma série de desastres cómicos", "Troca de papéis: a criança faz de pai/mãe e vice-versa"}',
  'Cozinhas de pernas para o ar, festas de aniversário caóticas, aula quando uma experiência corre mal, jardim zoológico no dia em que os animais trocam de jaula.',
  '{"A criança inventora cujos planos falham sempre", "O animal excêntrico", "A personagem que leva tudo à letra", "O gémeo traquinas"}',
  'Barulhos estranhos, cores vivas e salpicos, cheiros esquisitos (queijo fedorento, poções falhadas), texturas pegajosas.',
  '{"Cada tentativa de resolver piora as coisas", "Um mal-entendido desencadeia uma série de situações absurdas", "Um objeto mágico faz exatamente o contrário do esperado", "A preparação secreta de um evento acaba num desastre cómico"}'),
('educational', 'pt', '{"de": "Wissen & Entdecken", "fr": "Savoir & Découvrir", "en": "Learn & Discover", "pt": "Aprender e descobrir"}',
  '{"Uma criança curiosa faz uma pergunta e parte em busca da resposta", "Uma personagem histórica conta a sua história como se falasse à criança", "A criança acorda noutra época e observa como se vivia", "Um animal ou objeto explica o seu funcionamento de forma divertida"}',
  'Laboratórios imaginários, máquinas do tempo, bibliotecas encantadas, observatórios, museus que ganham vida à noite, caravelas de descobrimentos.',
  '{"A criança curiosa que faz sempre perguntas", "O professor excêntrico", "O robô ajudante simpático", "O animal especialista do seu ecossistema"}',
  'Detalhes precisos, cores naturais, sons autênticos de natureza ou cidade histórica, texturas de materiais, cheiro a livros antigos.',
  '{"A criança tem de resolver um problema com o que aprendeu", "Uma experiência não dá o resultado esperado", "Duas teorias confrontam-se e a criança tem de encontrar a verdade", "Um fenómeno natural misterioso tem de ser explicado"}'),

-- Turkish (tr) – cultural elements: bazaar, Nasreddin Hoca, Bosphorus, tulips, çay
('fantasy', 'tr', '{"de": "Märchen & Fantasie", "fr": "Contes & Fantaisie", "en": "Fairy Tales & Fantasy", "tr": "Masallar ve fantezi"}',
  '{"Bir çocuk onu büyülü bir dünyaya taşıyan sihirli bir nesne keşfeder", "Büyülü bir yaratık yardıma ihtiyaç duyar ve sadece çocuk krallığı kurtarabilir", "Gün batmadan önce üç sınavla bir büyü bozulmalıdır", "Çocuk hayvanların konuştuğu bir dünyaya açılan gizli bir kapı bulur"}',
  'Işıldayan ağaçlarla dolu büyülü ormanlar, bulutlardaki uçan kaleler, mantarların altındaki minik köyler, kristal mağaralar, gökkuşağı köprüleriyle bağlı uçan adalar, Boğaz kıyısında sihirli bahçeler.',
  '{"Sakar büyücü çırağı", "Yaramaz peri", "İyi kalpli ejderha", "Zor durumda kral/kraliçe", "Konuşan rehber hayvan", "Gizemli muhafız"}',
  'Altın parıltılar, yıldız tozu, sihirli çiçek kokusu, çıngırak sesi, yosun ve ipek dokusu.',
  '{"Büyü kayboluyor ve geri getirilmesi gerekiyor", "Kötü bir büyücü büyülü dünyayı tehdit ediyor", "Çocuk eve dönmek ya da kalmak arasında seçim yapmalı", "Büyülü yaratıklar arasındaki yanlış anlama kaos yaratır"}'),
('action', 'tr', '{"de": "Abenteuer & Action", "fr": "Aventure & Action", "en": "Adventure & Action", "tr": "Macera ve aksiyon"}',
  '{"Çocuk bir hazine haritası bulur ve arkadaşlarıyla keşif gezisine çıkar", "Mahalledeki bir gizem tatil bitmeden çözülmelidir", "Çocuk bir okul gezisinde beklenmedik bir maceraya atılır", "Bir şeyi veya birini kurtarmak için zamana karşı yarış"}',
  'Gür ormanlar, meşaleli mağaralar, korsan gemileri, karlı dağlar, gizli geçitli eski harabeler, İstanbul''un dar sokakları, büyük çarşı.',
  '{"Cesur kaşif", "Sadık en iyi arkadaş", "Müttefik olan rakip", "Bilge akıl hocası", "Komik karakter"}',
  'Saçlarda rüzgâr, hızlanan kalp, ıslak toprak kokusu, acele adımlar, kavurucu güneş, çay kokusu.',
  '{"Doğal bir engel yolu kapatır", "Bir rakip ilk varmak ister", "Grup ayrılıp tekrar buluşmalı", "Görünürdeki ihanet iyi niyeti gizler"}'),
('animals', 'tr', '{"de": "Tiergeschichten", "fr": "Histoires d''animaux", "en": "Animal Stories", "tr": "Hayvan hikayeleri"}',
  '{"Kayıp bir hayvan ailesine geri dönüş yolunu arar", "Farklı hayvanlardan oluşan bir grup bir zorluğu aşmak için işbirliği yapmalı", "Genç bir hayvan değerini kanıtlamalı", "İki çok farklı tür arasındaki beklenmedik dostluk"}',
  'Şafakta huzurlu çiftlikler, inleri ve yuvaları olan derin ormanlar, okyanuslar ve mercan resifleri, Afrika savanası, havuzlu gizli bahçeler, Kapadokya''nın peri bacaları.',
  '{"Cesur küçük hayvan", "Grubun bilge yaşlısı", "Güvenmeyi öğrenen çekingen hayvan", "Sakar ama sevimli yol arkadaşı"}',
  'Yumuşak kürk, kuş sesleri, hışırdayan yapraklar, toprak ve çimen kokusu, kürkte sıcak güneş.',
  '{"Bir yırtıcı grubu tehdit eder", "Mevsimler değişir ve göç etmek veya uyum sağlamak gerekir", "Bir yavru annesinden ayrılır", "İki grup aynı bölgeyi talep eder"}'),
('everyday', 'tr', '{"de": "Alltag & Gefühle", "fr": "Quotidien & Émotions", "en": "Everyday & Feelings", "tr": "Günlük yaşam ve duygular"}',
  '{"Bir çocuk bir değişiklikle yüzleşir ve uyum sağlamayı öğrenir", "Arkadaşlar arasındaki bir yanlış anlama konuşarak çözülür", "Çocuk beklenmedik bir tutku veya yetenek keşfeder", "Yeni bir ortamda ilk gün (okul, mahalle, etkinlik)"}',
  'Sıcak evler, canlı okul bahçeleri, parklar, sınıflar, çocuk odaları, ikindi vakti mutfaklar.',
  '{"Hassas ve gözlemci çocuk", "Utangaç yeni gelen", "Koruyucu ağabey/abla", "Sadık arkadaş", "Tuhaf komşu"}',
  'Fırından gelen kek kokusu, çocuk kahkahaları, yumuşak akşam ışığı, boya kalemi dokusu, sıcak çikolata tadı, çay saati.',
  '{"Bir arkadaş taşınır ve vedayı yönetmek gerekir", "Bir çocuk kendini farklı hisseder", "Ağırlık yapan ve paylaşılması gereken bir sır", "Yeni bir bebeğe veya arkadaşa kıskançlık"}'),
('humor', 'tr', '{"de": "Humor & Chaos", "fr": "Humour & Chaos", "en": "Humor & Chaos", "tr": "Mizah ve kaos"}',
  '{"Bir çocuk sürpriz hazırlamaya çalışınca her şey ters gider", "Günlük bir nesne saçma şeyler yapmaya başlar", "Bir evcil hayvan bir dizi komik felakete neden olur", "Rol değişimi: çocuk ebeveyn, ebeveyn çocuk olur"}',
  'Altüst olmuş mutfaklar, kaotik doğum günü partileri, deney yanlış gittiğinde sınıf, hayvanların kafes değiştirdiği gün hayvanat bahçesi, Nasreddin Hoca''nın köyü.',
  '{"Planları hep muhteşem biçimde başarısız olan mucit çocuk", "Eksantrik hayvan", "Her şeyi kelimesi kelimesine alan karakter", "Yaramaz ikiz"}',
  'Tuhaf sesler, canlı renkler ve sıçramalar, garip kokular (kokmuş peynir, başarısız iksirler), yapışkan dokular.',
  '{"Her düzeltme girişimi işleri daha da kötüleştirir", "Bir yanlış anlama bir dizi saçma durumu tetikler", "Sihirli bir nesne beklenenin tam tersini yapar", "Bir etkinliğin gizli hazırlığı komik bir felaketle sonuçlanır"}'),
('educational', 'tr', '{"de": "Wissen & Entdecken", "fr": "Savoir & Découvrir", "en": "Learn & Discover", "tr": "Öğren ve keşfet"}',
  '{"Meraklı bir çocuk bir soru sorar ve cevabını aramaya çıkar", "Tarihi bir kişilik hikâyesini çocuğa anlatır gibi anlatır", "Çocuk başka bir çağda uyanır ve insanların nasıl yaşadığını gözlemler", "Bir hayvan veya nesne işleyişini eğlenceli biçimde anlatır"}',
  'Hayali laboratuvarlar, zaman makineleri, büyülü kütüphaneler, rasathaneler, geceleri canlanan müzeler, Topkapı Sarayı''nda keşif.',
  '{"Her zaman soru soran meraklı çocuk", "Eksantrik profesör", "Sevimli robot asistan", "Ekosisteminin uzmanı hayvan"}',
  'Hassas detaylar, doğal renkler, doğa veya tarihi şehrin otantik sesleri, malzemelerin dokuları.',
  '{"Çocuk öğrendikleriyle bir sorunu çözmeli", "Bir deney beklenen sonucu vermez", "İki teori çatışır ve çocuk gerçeği bulmalı", "Gizemli bir doğa olayının açıklanması gerekir"}'),

-- Polish (pl) – cultural elements: Wawel Dragon, Baltic Sea, forests, amber, pierogi
('fantasy', 'pl', '{"de": "Märchen & Fantasie", "fr": "Contes & Fantaisie", "en": "Fairy Tales & Fantasy", "pl": "Baśnie i fantazja"}',
  '{"Dziecko odkrywa magiczny przedmiot, który przenosi je do zaczarowanego świata", "Magiczne stworzenie potrzebuje pomocy i tylko dziecko może uratować królestwo", "Zaklęcie musi zostać złamane przed zachodem słońca przez trzy próby", "Dziecko znajduje tajemne drzwi do świata, w którym zwierzęta mówią"}',
  'Zaczarowane lasy ze świecącymi drzewami, unoszące się zamki w chmurach, miniaturowe wioski pod grzybami, kryształowe jaskinie, latające wyspy połączone tęczowymi mostami, wawelskie podziemia.',
  '{"Niezdarny uczeń czarodzieja", "Psotna wróżka", "Dobroduszny smok", "Król/królowa w opałach", "Mówiące zwierzę-przewodnik", "Tajemniczy strażnik"}',
  'Złote blaski, gwiezdny pył, zapach magicznych kwiatów, dźwięk dzwoneczków, mech i jedwab, bursztynowy blask.',
  '{"Magia zanika i trzeba ją przywrócić", "Zły czarownik zagraża zaczarowanemu światu", "Dziecko musi wybrać między powrotem do domu a pozostaniem", "Nieporozumienie między magicznymi stworzeniami powoduje chaos"}'),
('action', 'pl', '{"de": "Abenteuer & Action", "fr": "Aventure & Action", "en": "Adventure & Action", "pl": "Przygoda i akcja"}',
  '{"Dziecko znajduje mapę skarbów i wyrusza na wyprawę z przyjaciółmi", "Tajemnica w okolicy musi zostać rozwiązana przed końcem wakacji", "Dziecko przeżywa niespodziewaną przygodę na wycieczce szkolnej", "Wyścig z czasem, żeby coś lub kogoś uratować"}',
  'Bujne dżungle, jaskinie z pochodniami, statki pirackie, zaśnieżone góry, ruiny z tajnymi przejściami, mazurskie jeziora, bałtyckie plaże.',
  '{"Odważny odkrywca", "Wierny najlepszy przyjaciel", "Rywal, który staje się sojusznikiem", "Mądry mentor", "Komiczna postać"}',
  'Wiatr we włosach, kołatanie serca, zapach mokrej ziemi, pośpieszne kroki, palące słońce, zapach sosnowego lasu.',
  '{"Naturalna przeszkoda blokuje drogę", "Rywal chce dotrzeć pierwszy", "Grupa musi się rozdzielić i spotkać ponownie", "Pozorna zdrada kryje dobre intencje"}'),
('animals', 'pl', '{"de": "Tiergeschichten", "fr": "Histoires d''animaux", "en": "Animal Stories", "pl": "Historie o zwierzętach"}',
  '{"Zagubione zwierzę szuka drogi powrotnej do rodziny", "Grupa różnych zwierząt musi współpracować, żeby pokonać wyzwanie", "Młode zwierzę musi udowodnić swoją wartość", "Niespodziewana przyjaźń między dwoma bardzo różnymi gatunkami"}',
  'Spokojne gospodarstwa o świcie, głębokie lasy z norami i gniazdami, oceany i rafy koralowe, afrykańska sawanna, tajemnicze ogrody ze stawami, puszcza białowieska.',
  '{"Odważne małe zwierzę", "Mądry starszyzna grupy", "Nieufne zwierzę, które uczy się ufać", "Niezdarny, ale uroczy towarzysz"}',
  'Miękkie futro, śpiew ptaków, szelest liści, zapach ziemi i trawy, ciepłe słońce na futrze.',
  '{"Drapieżnik zagraża grupie", "Pory roku się zmieniają i trzeba migrować lub się przystosować", "Młode oddziela się od matki", "Dwie grupy roszczą sobie prawo do tego samego terytorium"}'),
('everyday', 'pl', '{"de": "Alltag & Gefühle", "fr": "Quotidien & Émotions", "en": "Everyday & Feelings", "pl": "Codzienność i uczucia"}',
  '{"Dziecko staje przed zmianą i uczy się adaptować", "Nieporozumienie między przyjaciółmi, które rozwiązuje się rozmową", "Dziecko odkrywa niespodziewaną pasję lub talent", "Pierwszy dzień w nowym otoczeniu (szkoła, osiedle, zajęcia)"}',
  'Przytulne domy, tętniące życiem boiska szkolne, parki, sale lekcyjne, pokoje dziecięce, kuchnie o porze podwieczorku.',
  '{"Wrażliwe i spostrzegawcze dziecko", "Nieśmiały nowicjusz", "Opiekuńczy starszy brat/siostra", "Wierny przyjaciel", "Osobliwy sąsiad"}',
  'Zapach ciasta z piekarnika, śmiech dzieci, miękkie wieczorne światło, faktura kredek, smak gorącej czekolady, aromat pierogów.',
  '{"Przyjaciel się przeprowadza i trzeba poradzić sobie z pożegnaniem", "Dziecko czuje się inne", "Tajemnica, która ciąży i trzeba się nią podzielić", "Zazdrość o nowe dziecko lub kolegę"}'),
('humor', 'pl', '{"de": "Humor & Chaos", "fr": "Humour & Chaos", "en": "Humor & Chaos", "pl": "Humor i chaos"}',
  '{"Wszystko idzie nie tak, gdy dziecko próbuje przygotować niespodziankę", "Codzienny przedmiot zaczyna robić absurdalne rzeczy", "Zwierzę domowe powoduje serię komicznych katastrof", "Zamiana ról: dziecko jest rodzicem, a rodzic dzieckiem"}',
  'Wywrócone kuchnie, chaotyczne urodziny, klasa podczas nieudanego eksperymentu, zoo gdy zwierzęta postanawiają zamienić się klatkami.',
  '{"Dziecko wynalazca, którego plany zawsze spektakularnie się nie udają", "Ekscentryczne zwierzę", "Postać, która wszystko bierze dosłownie", "Figlarz-bliźniak"}',
  'Nieprawdopodobne dźwięki, żywe kolory i plamy, dziwne zapachy (śmierdzący ser, nieudane mikstury), lepkie tekstury.',
  '{"Każda próba naprawienia pogarsza sytuację", "Nieporozumienie wywołuje łańcuch absurdalnych sytuacji", "Magiczny przedmiot robi dokładnie odwrotnie niż oczekiwano", "Tajna przygotowywanie wydarzenia kończy się komiczną katastrofą"}'),
('educational', 'pl', '{"de": "Wissen & Entdecken", "fr": "Savoir & Découvrir", "en": "Learn & Discover", "pl": "Ucz się i odkrywaj"}',
  '{"Ciekawe dziecko zadaje pytanie i wyrusza na poszukiwanie odpowiedzi", "Postać historyczna opowiada swoją historię, jakby mówiła do dziecka", "Dziecko budzi się w innej epoce i obserwuje, jak żyli ludzie", "Zwierzę lub przedmiot w zabawny sposób wyjaśnia swoje działanie"}',
  'Wyimaginowane laboratoria, wehikuły czasu, zaczarowane biblioteki, obserwatoria, muzea ożywające nocą, kopalnia soli w Wieliczce.',
  '{"Ciekawe dziecko, które zawsze pyta", "Ekscentryczny profesor", "Sympatyczny robot asystent", "Zwierzę-ekspert swojego ekosystemu"}',
  'Precyzyjne detale, naturalne kolory, autentyczne dźwięki natury lub historycznego miasta, tekstury materiałów, blask bursztynu.',
  '{"Dziecko musi rozwiązać problem z pomocą tego, czego się nauczyło", "Eksperyment nie daje oczekiwanego wyniku", "Dwie teorie się zderzają i dziecko musi znaleźć prawdę", "Tajemnicze zjawisko przyrodnicze trzeba wyjaśnić"}')
ON CONFLICT (theme_key, language) DO NOTHING;

-- ============================================================
-- 3. difficulty_rules (3 levels × 3 languages)
-- ============================================================

INSERT INTO difficulty_rules (
  difficulty_level, language,
  label, description, vocabulary_scope,
  new_words_per_story, figurative_language, idiom_usage,
  humor_types, repetition_strategy, example_vocabulary
) VALUES
-- Portuguese (pt)
(1, 'pt', '{"pt": "Fácil", "en": "Easy"}', '{"pt": "Vocabulário simples, poucas palavras novas. Leitura amigável e fluida.", "en": "Simple vocabulary, few new words. Child-friendly and easy to read."}',
  'Palavras do dia a dia, concretas e familiares. Evitar tecnicismos. Pro-drop: não repetir pronomes sujeito. Artigos (o/a/os/as) corretos. PT-PT.',
  3, 'Quase nenhuma. Comparações muito simples se necessário.', 'Uso mínimo; expressões muito comuns (ex. "de repente", "no fim").',
  '{"situações absurdas", "onomatopeias", "enganos cómicos"}',
  'Repetir a palavra nova 2-3 vezes em contextos diferentes na história. Usar diminutivos (-inho, -inha) para reforçar.',
  '{"correr", "olhar", "encontrar", "pequeno", "contente", "casa"}'),
(2, 'pt', '{"pt": "Médio", "en": "Medium"}', '{"pt": "Vocabulário intermédio, algumas palavras novas. Equilibrado e compreensível.", "en": "Intermediate vocabulary, some new words. Balanced and clear."}',
  'Vocabulário algo mais rico; continua a ser maioritariamente concreto. Conjuntivo onde natural. Pro-drop. Artigos corretos. PT-PT.',
  6, 'Comparações e alguma metáfora simples. Conjuntivo onde natural.', 'Algumas expressões idiomáticas frequentes (ex. "ter medo", "ter saudades").',
  '{"situações absurdas", "jogos de palavras simples", "mal-entendidos", "exagero"}',
  'Palavra nova: aparecer em 2 cenas; variar o contexto. Recorrer a sinónimos simples na mesma história.',
  '{"aventura", "mistério", "corajoso", "surpreendido", "decidir", "ajudar"}'),
(3, 'pt', '{"pt": "Difícil", "en": "Hard"}', '{"pt": "Vocabulário mais rico, mais palavras novas. Desafiante e enriquecedor.", "en": "Richer vocabulary, more new words. Challenging and enriching."}',
  'Léxico variado e matizado. Termos mais literários ou descritivos. Conjuntivo e pro-drop naturais. PT-PT.',
  10, 'Metáforas, comparações, personificação suave. Conjuntivo em orações subordinadas.', 'Expressões idiomáticas e provérbios adaptados à idade.',
  '{"jogos de palavras", "ironia leve", "situações absurdas", "duplo sentido suave"}',
  'Palavras novas repartidas na trama; reforçar com contexto e sinónimos. Não repetir em excesso.',
  '{"inesperado", "determinação", "reconciliação", "descoberta", "generosidade"}'),
-- Turkish (tr)
(1, 'tr', '{"tr": "Kolay", "en": "Easy"}', '{"tr": "Basit sözcük dağarcığı, az yeni sözcük. Çocuk dostu ve akıcı.", "en": "Simple vocabulary, few new words. Child-friendly and easy to read."}',
  'Günlük, somut ve tanıdık sözcükler. Teknik terimlerden kaçın. SOV: yüklem sonda. Ünlü uyumu doğru. Artikel yok.',
  3, 'Neredeyse hiç. Yalnızca çok basit benzetmeler.', 'Minimum; çok yaygın ifadeler (ör. "birden", "sonunda").',
  '{"absürt durumlar", "yansıma sesler", "komik yanlış anlamalar"}',
  'Yeni sözcüğü 2-3 kez farklı bağlamlarda tekrarla. Küçültme ekleri (-cık, -cik) ile pekiştir.',
  '{"koşmak", "bakmak", "bulmak", "küçük", "mutlu", "ev"}'),
(2, 'tr', '{"tr": "Orta", "en": "Medium"}', '{"tr": "Orta düzey sözcük dağarcığı, birkaç yeni sözcük. Dengeli ve anlaşılır.", "en": "Intermediate vocabulary, some new words. Balanced and clear."}',
  'Biraz daha zengin sözcük dağarcığı; hâlâ çoğunlukla somut. SOV tutarlı. Ünlü uyumu doğru.',
  6, 'Benzetmeler ve basit mecazlar. -miş''li geçmiş zaman rivayetsel kullanımda.', 'Bazı yaygın deyimler (ör. "korkmak", "özlemek").',
  '{"absürt durumlar", "basit kelime oyunları", "yanlış anlamalar", "abartma"}',
  'Yeni sözcük 2 sahnede; bağlam çeşitle. Aynı hikâyede basit eş anlamlılar.',
  '{"macera", "gizem", "cesur", "şaşırmış", "karar vermek", "yardım etmek"}'),
(3, 'tr', '{"tr": "Zor", "en": "Hard"}', '{"tr": "Daha zengin sözcük dağarcığı, daha fazla yeni sözcük. Zorlayıcı ve zenginleştirici.", "en": "Richer vocabulary, more new words. Challenging and enriching."}',
  'Çeşitli ve nüanslı sözcük dağarcığı. Daha edebi veya betimleyici terimler. SOV ve ünlü uyumu doğal.',
  10, 'Mecazlar, benzetmeler, hafif kişileştirme.', 'Yaşa uygun deyimler ve atasözleri.',
  '{"kelime oyunları", "hafif ironi", "absürt durumlar", "ince çift anlamlılık"}',
  'Yeni sözcükler olay örgüsüne yayılmış; bağlam ve eş anlamlılarla pekiştir.',
  '{"beklenmedik", "kararlılık", "barışma", "keşif", "cömertlik"}'),
-- Polish (pl)
(1, 'pl', '{"pl": "Łatwy", "en": "Easy"}', '{"pl": "Prosty słownik, mało nowych słów. Przyjazne i płynne czytanie.", "en": "Simple vocabulary, few new words. Child-friendly and easy to read."}',
  'Codzienne, konkretne i znane słowa. Unikać terminów technicznych. Aspekt dokonany/niedokonany konsekwentny. Przypadki proste.',
  3, 'Prawie żadna. Tylko bardzo proste porównania.', 'Minimalne; bardzo popularne wyrażenia (np. "nagle", "w końcu").',
  '{"absurdalne sytuacje", "onomatopeje", "zabawne pomyłki"}',
  'Nowe słowo 2-3 razy w różnych kontekstach. Zdrobnienia (-ek, -ka, -ko) dla wzmocnienia.',
  '{"biegać", "patrzeć", "znaleźć", "mały", "wesoły", "dom"}'),
(2, 'pl', '{"pl": "Średni", "en": "Medium"}', '{"pl": "Średni słownik, kilka nowych słów. Zrównoważone i zrozumiałe.", "en": "Intermediate vocabulary, some new words. Balanced and clear."}',
  'Nieco bogatszy słownik; nadal w większości konkretny. Aspekt dla rytmu narracji. Przypadki poprawne.',
  6, 'Porównania i proste metafory.', 'Niektóre popularne idiomy (np. "bać się", "tęsknić").',
  '{"absurdalne sytuacje", "proste gry słowne", "nieporozumienia", "przesada"}',
  'Nowe słowo w 2 scenach; zmieniać kontekst. Proste synonimy w tej samej historii.',
  '{"przygoda", "tajemnica", "odważny", "zaskoczony", "zdecydować", "pomagać"}'),
(3, 'pl', '{"pl": "Trudny", "en": "Hard"}', '{"pl": "Bogatszy słownik, więcej nowych słów. Wymagające i wzbogacające.", "en": "Richer vocabulary, more new words. Challenging and enriching."}',
  'Zróżnicowany i niuansowany słownik. Bardziej literackie lub opisowe terminy. Aspekt i przypadki naturalne.',
  10, 'Metafory, porównania, lekka personifikacja.', 'Idiomy i przysłowia dostosowane do wieku.',
  '{"gry słowne", "lekka ironia", "absurdalne sytuacje", "subtelna dwuznaczność"}',
  'Nowe słowa rozłożone w fabule; wzmacniać kontekstem i synonimami.',
  '{"niespodziewany", "determinacja", "pojednanie", "odkrycie", "hojność"}')
ON CONFLICT (difficulty_level, language) DO NOTHING;
