-- ============================================================
-- Fill translation gaps for 7 core languages (de, fr, en, es, nl, it, bs)
-- in learning_themes, content_themes_by_level, image_styles, story_subtypes.
-- Idempotent: only adds missing keys (does not overwrite existing).
-- ============================================================

-- ── 1. learning_themes: add missing 'bs' (and es, nl, it if absent) ──
-- Seed already has all 7; these updates fix any row missing a key.

UPDATE learning_themes SET labels = labels || '{"bs": "Dijeljenje i velikodušnost"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči da dijeljenje donosi radost i jača odnose."}'::jsonb WHERE theme_key = 'sharing' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Empatija i promjena perspektive"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči da se stavi u poziciju drugih i razumije njihova osjećanja."}'::jsonb WHERE theme_key = 'empathy' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Njegovanje prijateljstva"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči kako graditi i održavati dobra prijateljstva."}'::jsonb WHERE theme_key = 'friendship' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Saradnja"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči da se zajedno postiže više nego samo."}'::jsonb WHERE theme_key = 'cooperation' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Strpljenje i čekanje"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči da dobre stvari ponekad zahtijevaju vrijeme."}'::jsonb WHERE theme_key = 'patience' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Suočavanje s frustracijom"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči kako se nositi s razočarenjima i neuspjesima."}'::jsonb WHERE theme_key = 'frustration' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Hrabrost i prevazilaženje stidljivosti"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči biti hrabro i isprobavati nove stvari."}'::jsonb WHERE theme_key = 'courage' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Upravljanje ljutnjom"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči prepoznati ljutnju i konstruktivno se nositi s njom."}'::jsonb WHERE theme_key = 'anger_management' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Iskrenost"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči vrijednost istine i iskrenosti."}'::jsonb WHERE theme_key = 'honesty' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Samostalnost"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči samo pokušavati stvari i donositi vlastite odluke."}'::jsonb WHERE theme_key = 'independence' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Preuzimanje odgovornosti"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči stajati iza svojih postupaka i obećanja."}'::jsonb WHERE theme_key = 'responsibility' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Priznavanje grešaka"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči da je griješenje ljudsko i da se iz grešaka može učiti."}'::jsonb WHERE theme_key = 'admitting_mistakes' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Znatiželja i postavljanje pitanja"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči da je postavljanje pitanja prvi korak ka razumijevanju."}'::jsonb WHERE theme_key = 'curiosity' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Rješavanje problema"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči sistematski pristupati izazovima."}'::jsonb WHERE theme_key = 'problem_solving' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));
UPDATE learning_themes SET labels = labels || '{"bs": "Kreativnost i originalno razmišljanje"}'::jsonb, descriptions = descriptions || '{"bs": "Dijete uči razvijati vlastite ideje i pronalaziti kreativna rješenja."}'::jsonb WHERE theme_key = 'creativity' AND (NOT (labels ? 'bs') OR NOT (descriptions ? 'bs'));

-- ── 2. content_themes_by_level: add missing 'bs' for labels + example_texts ──
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Svađa među prijateljima"}'::jsonb, example_texts = example_texts || '{"bs": "Mia i Tom su se svađali oko posljednjeg kolačića, ali su onda imali ideju."}'::jsonb WHERE theme_key = 'friend_conflict' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Blaga tuga"}'::jsonb, example_texts = example_texts || '{"bs": "Kad mu je balon odletio, Leo je bio tužan – ali onda je ugledao dugu."}'::jsonb WHERE theme_key = 'minor_sadness' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Kratki trenuci straha"}'::jsonb, example_texts = example_texts || '{"bs": "U tamnoj šumi čula je zvuk – to je bila samo mala vjeverica!"}'::jsonb WHERE theme_key = 'minor_fear' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Razočarenje"}'::jsonb, example_texts = example_texts || '{"bs": "Piknik je propao zbog kiše, ali su kod kuće napravili tvrđavu od deka."}'::jsonb WHERE theme_key = 'disappointment' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Razvod / Razdvajanje"}'::jsonb, example_texts = example_texts || '{"bs": "Linini roditelji sada žive u dva različita doma – ali oboje je vole jednako."}'::jsonb WHERE theme_key = 'divorce' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Selidba / Promjena"}'::jsonb, example_texts = example_texts || '{"bs": "Novi grad bio je nepoznat, ali u školi je neko čekao s osmijehom."}'::jsonb WHERE theme_key = 'moving' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Maltretiranje"}'::jsonb, example_texts = example_texts || '{"bs": "Niko nije htio sjesti pored nje – dok nije došlo novo dijete i reklo: Smijem li?"}'::jsonb WHERE theme_key = 'bullying' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Usamljenost"}'::jsonb, example_texts = example_texts || '{"bs": "Na rubu igrališta stajao je sam – dok nije primijetio da je i jež sam."}'::jsonb WHERE theme_key = 'loneliness' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Smrt kućnog ljubimca"}'::jsonb, example_texts = example_texts || '{"bs": "Zlatna ribica Mjehurić više nije plivala – ali sjećanja su ostala zauvijek."}'::jsonb WHERE theme_key = 'pet_death' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Ljubomora"}'::jsonb, example_texts = example_texts || '{"bs": "Kad je beba stigla, Max se osjećao nevidljivim – dok ga tata nije poveo u avanturu velikog brata."}'::jsonb WHERE theme_key = 'jealousy' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Smrt (prilagođeno djeci)"}'::jsonb, example_texts = example_texts || '{"bs": "Bake više nije bilo, ali svaki put kad bi vjetar zaljuljao lišće, Mia je mislila na nju."}'::jsonb WHERE theme_key = 'death' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Rat / Bijeg"}'::jsonb, example_texts = example_texts || '{"bs": "Morali su napustiti dom, ali u ruksaku je bila omiljena knjiga – komadić doma."}'::jsonb WHERE theme_key = 'war_flight' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Teška bolest"}'::jsonb, example_texts = example_texts || '{"bs": "Tata je dugo bio u bolnici, ali svaki dan mu je crtala sliku – jednu ljepšu od druge."}'::jsonb WHERE theme_key = 'serious_illness' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Složene porodične strukture"}'::jsonb, example_texts = example_texts || '{"bs": "Dvije mame, tata daleko, a ipak toliko ljubavi."}'::jsonb WHERE theme_key = 'complex_families' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Eksplicitno nasilje"}'::jsonb, example_texts = example_texts || '{"bs": "Nikada se neće pojaviti ni u jednoj priči."}'::jsonb WHERE theme_key = 'explicit_violence' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Seksualni sadržaj"}'::jsonb, example_texts = example_texts || '{"bs": "Nikada se neće pojaviti ni u jednoj priči."}'::jsonb WHERE theme_key = 'sexual_content' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Samoubistvo"}'::jsonb, example_texts = example_texts || '{"bs": "Nikada se neće pojaviti ni u jednoj priči."}'::jsonb WHERE theme_key = 'suicide' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Zloupotreba droga"}'::jsonb, example_texts = example_texts || '{"bs": "Nikada se neće pojaviti ni u jednoj priči."}'::jsonb WHERE theme_key = 'drug_abuse' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));
UPDATE content_themes_by_level SET labels = labels || '{"bs": "Horor / Neriješena trauma"}'::jsonb, example_texts = example_texts || '{"bs": "Nikada se neće pojaviti ni u jednoj priči."}'::jsonb WHERE theme_key = 'unresolved_horror' AND (NOT (labels ? 'bs') OR NOT (example_texts ? 'bs'));

-- ── 3. image_styles: add missing 'bs' for labels + description (batch2 styles) ──
UPDATE image_styles SET labels = labels || '{"bs": "3D Avantura"}'::jsonb, description = description || '{"bs": "Pixar stil s glatkim teksturama i živim bojama."}'::jsonb WHERE style_key = '3d_adventure' AND (NOT (labels ? 'bs') OR NOT (description ? 'bs'));
UPDATE image_styles SET labels = labels || '{"bs": "Pixel Art"}'::jsonb, description = description || '{"bs": "Retro gaming izgled u 16-bitnom stilu."}'::jsonb WHERE style_key = 'pixel_art' AND (NOT (labels ? 'bs') OR NOT (description ? 'bs'));
UPDATE image_styles SET labels = labels || '{"bs": "Svijet Kockica"}'::jsonb, description = description || '{"bs": "Šareni 3D blokovi poput LEGO-a — kreativno i razigrano."}'::jsonb WHERE style_key = 'brick_block' AND (NOT (labels ? 'bs') OR NOT (description ? 'bs'));
UPDATE image_styles SET labels = labels || '{"bs": "Retro"}'::jsonb, description = description || '{"bs": "Nostalgičan izgled s ligne claire, poput Tintina."}'::jsonb WHERE style_key = 'vintage_retro' AND (NOT (labels ? 'bs') OR NOT (description ? 'bs'));

-- ── 4. story_subtypes: add missing fr, es, nl, it, bs to descriptions ──
-- Seed had only de + en; these add the other 5 core languages.

UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Une histoire dans une forêt magique pleine d''animaux parlants et de créatures mystérieuses", "es": "Una historia en un bosque mágico lleno de animales que hablan y criaturas misteriosas", "nl": "Een verhaal in een magisch bos vol pratende dieren en mysterieuze wezens", "it": "Una storia in una foresta magica piena di animali parlanti e creature misteriose", "bs": "Priča u čarobnoj šumi punoj životinja koje govore i tajanstvenih bića"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'enchanted_forest' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Un motif de conte connu raconté de façon nouvelle et surprenante", "es": "Un motivo de cuento conocido contado de forma nueva y sorprendente", "nl": "Een bekend sprookjesmotief op een nieuwe en verrassende manier verteld", "it": "Un motivo di fiaba conosciuto raccontato in modo nuovo e sorprendente", "bs": "Poznat motiv bajke ispripovijedan na nov i iznenađujući način"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'fairy_tale_twist' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Un enfant trouve ou sauve une créature magique et ils deviennent inséparables", "es": "Un niño encuentra o rescata una criatura mágica y se vuelven amigos inseparables", "nl": "Een kind vindt of redt een magisch wezen en ze worden onafscheidelijke vrienden", "it": "Un bambino trova o salva una creatura magica e diventano amici inseparabili", "bs": "Dijete pronalazi ili spašava čarobno biće i postaju nerazdvojni prijatelji"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'magical_creature_friendship' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Quelqu''un rétrécit à la taille d''une fourmi ou grandit plus haut que les maisons", "es": "Alguien se encoge al tamaño de una hormiga o crece más alto que las casas", "nl": "Iemand krimpt tot miergrootte of groeit hoger dan de huizen", "it": "Qualcuno si rimpicciolisce alle dimensioni di una formica o diventa più alto delle case", "bs": "Neko se smanji na veličinu mrava ili naraste više od kuća"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'shrinking_growing' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Voler sur un objet magique, une créature ou avec ses propres pouvoirs", "es": "Volar en un objeto mágico, criatura o con tus propios poderes", "nl": "Vliegen op een magisch voorwerp, wezen of met je eigen krachten", "it": "Volare su un oggetto magico, una creatura o con i propri poteri", "bs": "Letjeti na čarobnom predmetu, stvorenju ili vlastitim moćima"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'flying_adventure' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Voyager par une porte magique, un livre ou un miroir dans un monde totalement différent", "es": "Viajar por una puerta, libro o espejo mágico a un mundo completamente distinto", "nl": "Reizen door een magische deur, boek of spiegel naar een heel andere wereld", "it": "Viaggiare attraverso una porta, un libro o uno specchio magico in un mondo del tutto diverso", "bs": "Putovati kroz čarobna vrata, knjigu ili ogledalo u potpuno drugi svijet"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'portal_other_world' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Aventures dans une école où on apprend sorts, potions et matières magiques", "es": "Aventuras en una escuela donde se aprenden hechizos, pócimas y materias mágicas", "nl": "Avonturen op een school waar je toverspreuken, drankjes en magie leert", "it": "Avventure in una scuola dove si imparano incantesimi, pozioni e materie magiche", "bs": "Avanture u školi gdje se uče čarolije, napitci i magijski predmeti"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'wizard_school' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Une malédiction doit être brisée — mais la solution n''est pas celle qu''on attend", "es": "Una maldición debe romperse — pero la solución no es la esperada", "nl": "Een vloek moet worden verbroken — maar de oplossing is niet wat je verwacht", "it": "Una maledizione deve essere spezzata — ma la soluzione non è quella che ti aspetti", "bs": "Kletva se mora slomiti — ali rješenje nije ono što očekuješ"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'curse_breaking' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Voyager dans un monde de rêve fantastique qui change avec les émotions du rêveur", "es": "Viajar por un mundo de sueños fantástico que cambia con las emociones del soñador", "nl": "Reizen door een fantastische droomwereld die meebeweegt met de emoties van de dromer", "it": "Viaggiare in un mondo di sogno fantastico che cambia con le emozioni del sognatore", "bs": "Putovanje kroz fantastičan svijet snova koji se mijenja s emocijama sanjača"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'dream_journey' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Aventures sous l''eau : sirènes, cités englouties, poissons parlants", "es": "Aventuras submarinas: sirenas, ciudades hundidas, peces que hablan", "nl": "Onderwateravonturen: zeemeerminnen, verzonken steden, pratende vissen", "it": "Avventure sottomarine: sirene, città sommerse, pesci parlanti", "bs": "Podvodne avanture: sirene, potopljeni gradovi, ribe koje govore"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'underwater_kingdom' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Revivre le même jour encore et encore et comprendre pourquoi", "es": "Vivir el mismo día una y otra vez y descubrir por qué", "nl": "Dezelfde dag steeds opnieuw beleven en uitzoeken waarom", "it": "Rivivere lo stesso giorno ancora e ancora e capire perché", "bs": "Živjeti isti dan iznova i iznova i otkriti zašto"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'time_loop' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Un monde caché existe en parallèle du nôtre — seuls quelques-uns peuvent le voir", "es": "Un mundo oculto existe en paralelo al nuestro — solo unos pocos pueden verlo", "nl": "Een verborgen wereld bestaat naast de onze — slechts weinigen kunnen hem zien", "it": "Un mondo nascosto esiste parallelamente al nostro — solo in pochi possono vederlo", "bs": "Skriveni svijet postoji paralelno s našim — samo ga nekoliko može vidjeti"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'invisible_world' AND NOT (descriptions ? 'fr');

-- adventure_action
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Une carte, des énigmes et des indices mènent à un trésor caché", "es": "Un mapa, acertijos y pistas llevan a un tesoro escondido", "nl": "Een kaart, raadsels en aanwijzingen leiden naar een verborgen schat", "it": "Una mappa, indovinelli e indizi portano a un tesoro nascosto", "bs": "Karta, zagonetke i tragovi vode do skrivenog blaga"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'treasure_hunt' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Quelque chose a disparu ou une énigme doit être résolue — avec esprit et logique", "es": "Algo ha desaparecido o un enigma debe resolverse — con ingenio y lógica", "nl": "Iets is verdwenen of een raadsel moet worden opgelost — met verstand en logica", "it": "Qualcosa è scomparso o un enigma deve essere risolto — con ingegno e logica", "bs": "Nešto je nestalo ili zagonetka se mora riješiti — pameti i logikom"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'detective_case' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Voyager dans le passé ou le futur et y vivre une aventure", "es": "Viajar al pasado o al futuro y vivir una aventura allí", "nl": "Reizen naar het verleden of de toekomst en daar een avontuur beleven", "it": "Viaggiare nel passato o nel futuro e vivere un''avventura lì", "bs": "Putovati u prošlost ili budućnost i tamo doživjeti avanturu"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'time_travel' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Quelqu''un ou quelque chose doit être sauvé — contre la montre", "es": "Alguien o algo debe ser rescatado — contra reloj", "nl": "Iemand of iets moet gered worden — tegen de klok in", "it": "Qualcuno o qualcosa deve essere salvato — contro il tempo", "bs": "Neko ili nešto treba spasiti — u utrci s vremenom"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'rescue_mission' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Agir en secret, décrypter des codes et accomplir une mission secrète", "es": "Actuar en secreto, descifrar códigos y cumplir una misión secreta", "nl": "Undercover gaan, codes kraken en een geheime missie volbrengen", "it": "Agire sotto copertura, decifrare codici e portare a termine una missione segreta", "bs": "Djelovati tajno, razbiti šifre i izvršiti tajnu misiju"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'spy_mission' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Survivre seul ou à deux dans la nature — avec courage et ingéniosité", "es": "Sobrevivir solo o en pareja en la naturaleza — con valor e ingenio", "nl": "Alleen of met z''n tweeën overleven in de natuur — met moed en vindingrijkheid", "it": "Sopravvivere da soli o in due nella natura — con coraggio e ingegno", "bs": "Preživjeti sam ili u dvoje u prirodi — s hrabrošću i domišljenošću"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'survival_nature' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Un voyage dans l''inconnu pour découvrir quelque chose de nouveau", "es": "Un viaje a lo desconocido para descubrir algo nuevo", "nl": "Een reis naar het onbekende om iets nieuws te ontdekken", "it": "Un viaggio nell''ignoto per scoprire qualcosa di nuovo", "bs": "Putovanje u nepoznato da se otkrije nešto novo"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'expedition_discovery' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Une course palpitante ou une compétition à rebondissements", "es": "Una carrera emocionante o competición con giros sorprendentes", "nl": "Een spannende race of wedstrijd met verrassende wendingen", "it": "Una gara emozionante o una competizione con colpi di scena", "bs": "Uzbudljiva utrka ili takmičenje s iznenađujućim preokretima"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'race_competition' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "La nuit, il se passe quelque chose d''inattendu — et une aventure commence", "es": "Algo inesperado ocurre de noche — y comienza una aventura", "nl": "''s Nachts gebeurt er iets onverwachts — en een avontuur begint", "it": "Di notte succede qualcosa di inatteso — e inizia un''avventura", "bs": "Noću se nešto neočekivano dogodi — i počinje avantura"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'night_adventure' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Échouer sur une île déserte et y vivre une aventure", "es": "Quedar en una isla desierta y vivir allí una aventura", "nl": "Stranden op een onbewoond eiland en daar een avontuur beleven", "it": "Naufragare su un''isola deserta e vivere lì un''avventura", "bs": "Nasukati se na pustom otoku i tamo doživjeti avanturu"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'shipwreck_island' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Découvrir des tunnels secrets, des pièces cachées et des mondes souterrains", "es": "Descubrir túneles secretos, habitaciones ocultas y mundos subterráneos", "nl": "Geheime tunnels, verborgen kamers en ondergrondse werelden ontdekken", "it": "Scoprire tunnel segreti, stanze nascoste e mondi sotterranei", "bs": "Otkriti tajne tunele, skrivene sobe i podzemne svjetove"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'underground_exploration' AND NOT (descriptions ? 'fr');

-- real_life
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Quelqu''un de nouveau arrive en classe — et tout change", "es": "Alguien nuevo llega a clase — y todo cambia", "nl": "Er komt iemand nieuws in de klas — en alles verandert", "it": "Qualcuno di nuovo arriva in classe — e tutto cambia", "bs": "Neko novo dođe u razred — i sve se mijenja"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'new_kid_school' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Trouver un animal blessé ou perdu et l''aider", "es": "Encontrar un animal herido o perdido y ayudarlo", "nl": "Een gewond of verloren dier vinden en helpen", "it": "Trovare un animale ferito o perso e aiutarlo", "bs": "Pronaći ozlijeđenu ili izgubljenu životinju i pomoći joj"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'animal_rescue' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Une journée ou une sortie spéciale en famille — avec des surprises", "es": "Un día o excursión especial en familia — con sorpresas", "nl": "Een bijzondere dag of uitje met het gezin — met verrassingen", "it": "Una giornata o gita speciale in famiglia — con sorprese", "bs": "Poseban dan ili izlet s obitelji — s iznenađenjima"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'family_adventure' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Il se passe quelque chose d''inattendu en cuisine — une recette rate ou cartonne", "es": "Algo inesperado ocurre en la cocina — una receta sale mal o triunfa", "nl": "Er gebeurt iets onverwachts in de keuken — een recept mislukt of wordt een hit", "it": "In cucina succede qualcosa di inatteso — una ricetta fallisce o spopola", "bs": "U kuhinji se nešto neočekivano dogodi — recept ne uspije ili postane hit"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'cooking_baking' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Il se passe quelque chose d''étrange dans le quartier — qui est derrière ?", "es": "Algo extraño ocurre en el barrio — ¿quién está detrás?", "nl": "Er gebeurt iets vreemds in de buurt — wie zit erachter?", "it": "Succede qualcosa di strano nel quartiere — chi c''è dietro?", "bs": "U susjedstvu se nešto čudno događa — tko stoji iza toga?"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'neighborhood_mystery' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Se préparer à un match, concert ou pièce de théâtre important", "es": "Prepararse para un partido, concierto u obra de teatro importante", "nl": "Voorbereiden op een belangrijke wedstrijd, concert of schoolvoorstelling", "it": "Prepararsi a una partita, concerto o spettacolo scolastico importante", "bs": "Priprema za važnu utakmicu, koncert ili školsku predstavu"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'big_game_performance' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Déménager dans une nouvelle maison, ville ou pays", "es": "Mudarse a una casa, ciudad o país nuevo", "nl": "Verhuizen naar een nieuw huis, stad of land", "it": "Trasferirsi in una nuova casa, città o paese", "bs": "Selidba u novu kuću, grad ili državu"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'moving_new_home' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Un enfant découvre une passion que les autres ne comprennent pas — jusqu''à surprendre tout le monde", "es": "Un niño descubre una pasión que otros no entienden — hasta sorprender a todos", "nl": "Een kind ontdekt een passie die anderen niet begrijpen — tot ze iedereen verrassen", "it": "Un bambino scopre una passione che gli altri non capiscono — finché non sorprende tutti", "bs": "Dijete otkrije strast koju drugi ne razumiju — dok ne iznenadi sve"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'secret_hobby' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Les grands-parents racontent le passé — et soudain le passé s''anime", "es": "Los abuelos cuentan el pasado — y de repente el pasado cobra vida", "nl": "Grootouders vertellen over vroeger — en opeens komt het verleden tot leven", "it": "I nonni raccontano il passato — e all''improvviso il passato prende vita", "bs": "Bake i djedovi pričaju o prošlosti — i odjednom prošlost oživi"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'grandparent_story' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "La nature a besoin d''aide — et les enfants passent à l''action", "es": "La naturaleza necesita ayuda — y los niños actúan", "nl": "De natuur heeft hulp nodig — en kinderen grijpen in", "it": "La natura ha bisogno di aiuto — e i bambini passano all''azione", "bs": "Priroda treba pomoć — i djeca preuzimaju akciju"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'eco_adventure' AND NOT (descriptions ? 'fr');

-- surprise
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Tout va de travers — et ça devient de plus en plus drôle", "es": "Todo sale mal — y cada vez es más gracioso", "nl": "Alles gaat mis — en het wordt alleen maar grappiger", "it": "Tutto va storto — e diventa sempre più divertente", "bs": "Sve pođe po zlu — i postaje sve smješnije"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'chaos_comedy' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "L''enfant et l''adulte échangent les rôles — l''enfant commande", "es": "El niño y el adulto intercambian roles — el niño manda", "nl": "Kind en volwassene wisselen van rol — het kind is de baas", "it": "Bambino e adulto si scambiano i ruoli — comanda il bambino", "bs": "Dijete i odrasla osoba zamijene uloge — dijete je šef"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'role_reversal' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Quelqu''un découvre soudain un talent totalement inattendu", "es": "Alguien descubre de repente una capacidad totalmente inesperada", "nl": "Iemand ontdekt plots een volkomen onverwachte gave", "it": "Qualcuno scopre all''improvviso un talento del tutto inaspettato", "bs": "Neko iznenada otkrije potpuno neočekivanu sposobnost"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'unexpected_talent' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Un vœu se réalise — mais pas comme prévu", "es": "Un deseo se cumple — pero no como se esperaba", "nl": "Een wens komt uit — maar niet zoals verwacht", "it": "Un desiderio si avvera — ma non come previsto", "bs": "Želja se ispuni — ali ne onako kako se očekivalo"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'wish_gone_wrong' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Les objets du quotidien prennent vie et ont une volonté propre", "es": "Los objetos cotidianos cobran vida y tienen voluntad propia", "nl": "Alledaagse voorwerpen komen tot leven en hebben een eigen wil", "it": "Gli oggetti di tutti i giorni prendono vita e hanno una volontà propria", "bs": "Svakodnevni predmeti ožive i imaju vlastitu volju"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'talking_objects' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Un jour où tout est à l''envers — la pluie monte, l''école commence la nuit", "es": "Un día en que todo va al revés — la lluvia sube, el colegio empieza de noche", "nl": "Een dag waarop alles omgekeerd is — regen valt omhoog, school begint ''s nachts", "it": "Un giorno in cui tutto è al contrario — piove verso l''alto, la scuola inizia di notte", "bs": "Dan kad je sve naopako — kiša pada gore, škola počinje noću"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'backwards_day' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Une confusion déclenche une réaction en chaîne", "es": "Una confusión desencadena una reacción en cadena", "nl": "Een vergissing zet een kettingreactie in gang", "it": "Un equivoco innesca una reazione a catena", "bs": "Zabuna pokreće lančanu reakciju"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'mix_up_confusion' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Pas de super-pouvoir, pas de magie — un enfant ordinaire fait ce qu''il faut", "es": "Sin superpoder ni magia — un niño normal hace lo correcto", "nl": "Geen superkracht, geen magie — een gewoon kind doet het goede", "it": "Niente superpoteri, niente magia — un bambino normale fa la cosa giusta", "bs": "Bez supermoći, bez magije — obično dijete učini pravu stvar"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'super_ordinary_hero' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Dans un tiroir, sous une pierre ou derrière le mur vit une civilisation minuscule", "es": "En un cajón, bajo una piedra o tras la pared vive una civilización diminuta", "nl": "In een la, onder een steen of achter de muur woont een piepkleine beschaving", "it": "In un cassetto, sotto una pietra o dietro il muro vive una minuscola civiltà", "bs": "U ladici, ispod kamena ili iza zida živi sićušna civilizacija"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'miniature_world' AND NOT (descriptions ? 'fr');
UPDATE story_subtypes SET descriptions = descriptions || '{"fr": "Une lettre mystérieuse arrive — et mène à un voyage inattendu", "es": "Llega una carta misteriosa — y lleva a un viaje inesperado", "nl": "Er arriveert een mysterieuze brief — en die leidt tot een onverwachte reis", "it": "Arriva una lettera misteriosa — e conduce a un viaggio inatteso", "bs": "Stigne misteriozno pismo — i vodi do neočekivanog putovanja"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'letter_from_stranger' AND NOT (descriptions ? 'fr');

-- ============================================================
-- Verification: after running this migration, re-run the audit
-- queries from docs/TRANSLATION_AUDIT_REPORT.md §5. Every row
-- should show TRUE for has_de, has_fr, has_en, has_es, has_nl,
-- has_it, has_bs (and for description/example_texts where applicable).
-- ============================================================
