-- ============================================================
-- T-C1: DB-Übersetzungen — learning_themes
-- Adds: tr, bg, ro, pl, lt, hu, ca, sl to labels + descriptions
-- ============================================================

UPDATE learning_themes SET labels = labels || '{"tr": "Paylaşma ve Cömertlik", "bg": "Споделяне и щедрост", "ro": "Împărtășire și generozitate", "pl": "Dzielenie się i hojność", "lt": "Dalijimasis ir dosnumas", "hu": "Megosztás és nagylelkűség", "ca": "Compartir i generositat", "sl": "Deljenje in radodarnost"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk paylaşmanın neşe getirdiğini ve ilişkileri güçlendirdiğini öğrenir.", "bg": "Детето научава, че споделянето носи радост и затвърдява връзките.", "ro": "Copilul învață că împărtășirea aduce bucurie și întărește legăturile.", "pl": "Dziecko uczy się, że dzielenie się przynosi radość i wzmacnia relacje.", "lt": "Vaikas išmoksta, kad dalijimasis neša džiaugsmą ir stiprina santykius.", "hu": "A gyerek megtanulja, hogy a megosztás örömet ad és erősíti a kapcsolatokat.", "ca": "El nen aprèn que compartir aporta alegria i enforteix les relacions.", "sl": "Otrok se nauči, da deljenje prinaša veselje in krepi odnose."}'::jsonb WHERE theme_key = 'sharing';

UPDATE learning_themes SET labels = labels || '{"tr": "Empati ve Bakış Açısı", "bg": "Емпатия и смяна на перспектива", "ro": "Empatie și schimbare de perspectivă", "pl": "Empatia i zmiana perspektywy", "lt": "Empatija ir perspektyvos keitimas", "hu": "Empátia és perspektívaváltás", "ca": "Empatia i canvi de perspectiva", "sl": "Empatija in zamenjava perspektive"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk kendini başkalarının yerine koymayı ve duygularını anlamayı öğrenir.", "bg": "Детето се научава да се поставя на мястото на другите и да разбира чувствата им.", "ro": "Copilul învață să se pună în locul altora și să le înțeleagă sentimentele.", "pl": "Dziecko uczy się wchodzić w buty innych i rozumieć ich uczucia.", "lt": "Vaikas mokosi įsivaizduoti save kito vietoje ir suprasti jų jausmus.", "hu": "A gyerek megtanulja a másik helyébe képzelni magát és megérteni érzelmeit.", "ca": "El nen aprèn a posar-se al lloc dels altres i entendre els seus sentiments.", "sl": "Otrok se nauči vživet v druge in razumeti njihova čustva."}'::jsonb WHERE theme_key = 'empathy';

UPDATE learning_themes SET labels = labels || '{"tr": "Arkadaşlığı Beslemek", "bg": "Поддържане на приятелства", "ro": "Îngrijirea prieteniilor", "pl": "Dbanie o przyjaźnie", "lt": "Draugystės puoselėjimas", "hu": "Barátságok ápolása", "ca": "Cultivar l''amistat", "sl": "Negovanje prijateljstev"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk iyi arkadaşlıklar kurmayı ve sürdürmeyi öğrenir.", "bg": "Детето се научава как да изгражда и поддържа добри приятелства.", "ro": "Copilul învață cum să construiască și să mențină prietenii bune.", "pl": "Dziecko uczy się budować i utrzymywać dobre przyjaźnie.", "lt": "Vaikas mokosi kurti ir palaikyti gerus draugystes.", "hu": "A gyerek megtanulja, hogyan építsen és ápoljon jó barátságokat.", "ca": "El nen aprèn a construir i mantenir bones amistats.", "sl": "Otrok se nauči graditi in ohranjati dobra prijateljstva."}'::jsonb WHERE theme_key = 'friendship';

UPDATE learning_themes SET labels = labels || '{"tr": "İş Birliği", "bg": "Сътрудничество", "ro": "Cooperare", "pl": "Współpraca", "lt": "Bendradarbiavimas", "hu": "Együttműködés", "ca": "Cooperació", "sl": "Sodelovanje"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk birlikte tek başına olduğundan daha fazlasına ulaşılabileceğini öğrenir.", "bg": "Детето научава, че заедно се постига повече отколкото сам.", "ro": "Copilul învață că împreună se realizează mai mult decât singur.", "pl": "Dziecko uczy się, że razem osiąga się więcej niż w pojedynkę.", "lt": "Vaikas išmoksta, kad kartu pasiekiama daugiau nei vienam.", "hu": "A gyerek megtanulja, hogy együtt többet érnek el, mint egyedül.", "ca": "El nen aprèn que junts s''aconsegueix més que sol.", "sl": "Otrok se nauči, da skupaj dosežemo več kot sam."}'::jsonb WHERE theme_key = 'cooperation';

UPDATE learning_themes SET labels = labels || '{"tr": "Sabır ve Beklemeyi Öğrenmek", "bg": "Търпение и умението да чакаш", "ro": "Răbdare și a ști a aștepta", "pl": "Cierpliwość i czekanie", "lt": "Kantrybė ir mokėjimas laukti", "hu": "Türelem és várakozás", "ca": "Paciència i saber esperar", "sl": "Potrpežljivost in čakanje"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk iyi şeylerin bazen zaman aldığını öğrenir.", "bg": "Детето научава, че добрите неща понякога изискват време.", "ro": "Copilul învață că lucrurile bune uneori cer timp.", "pl": "Dziecko uczy się, że dobre rzeczy czasem wymagają czasu.", "lt": "Vaikas išmoksta, kad geri dalykai kartais reikalauja laiko.", "hu": "A gyerek megtanulja, hogy a jó dolgok néha időt igényelnek.", "ca": "El nen aprèn que les coses bones a vegades necessiten temps.", "sl": "Otrok se nauči, da dobre stvari včasih zahtevajo čas."}'::jsonb WHERE theme_key = 'patience';

UPDATE learning_themes SET labels = labels || '{"tr": "Hayal Kırıklığıyla Başa Çıkma", "bg": "Правене с фрустрация", "ro": "Gestionarea frustrării", "pl": "Radzenie sobie z frustracją", "lt": "Susidorojimas su frustracija", "hu": "Frusztráció kezelése", "ca": "Gestionar la frustració", "sl": "Soočanje s frustracijo"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk hayal kırıklıkları ve aksiliklere nasıl göğüs gereceğini öğrenir.", "bg": "Детето се научава да се справя с разочарованията и неуспехите.", "ro": "Copilul învață să facă față dezamăgirilor și setbacurilor.", "pl": "Dziecko uczy się radzić sobie z rozczarowaniami i niepowodzeniami.", "lt": "Vaikas mokosi susitvarkyti su nusivylimais ir kliūtimis.", "hu": "A gyerek megtanulja kezelni a csalódásokat és a visszaeséseket.", "ca": "El nen aprèn a fer front a les decepcions i els contratemps.", "sl": "Otrok se nauči soočati z razočaranji in nazadovanji."}'::jsonb WHERE theme_key = 'frustration';

UPDATE learning_themes SET labels = labels || '{"tr": "Cesaret ve Utangaçlığı Yenmek", "bg": "Смелост и преодоляване на срамежливост", "ro": "Curaj și depășirea rușinii", "pl": "Odwaga i przezwyciężanie nieśmiałości", "lt": "Drąsa ir drovumo įveikimas", "hu": "Bátorság és szégyenlősség legyőzése", "ca": "Coratge i superar la timidesa", "sl": "Pogum in premagovanje sramežljivosti"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk cesur olmayı ve yeni şeyler denemeyi öğrenir.", "bg": "Детето се научава да бъде смело и да опитва нови неща.", "ro": "Copilul învață să fie curajos și să încerce lucruri noi.", "pl": "Dziecko uczy się być odważnym i próbować nowych rzeczy.", "lt": "Vaikas mokosi būti drąsus ir išmėginti naujų dalykų.", "hu": "A gyerek megtanulja bátornak lenni és új dolgokat kipróbálni.", "ca": "El nen aprèn a ser valent i provar coses noves.", "sl": "Otrok se nauči biti pogumen in preizkušati nove stvari."}'::jsonb WHERE theme_key = 'courage';

UPDATE learning_themes SET labels = labels || '{"tr": "Öfkeyle Başa Çıkma", "bg": "Управление на гнева", "ro": "Gestionarea furiei", "pl": "Radzenie sobie ze złością", "lt": "Pyktį valdyti", "hu": "Düh kezelése", "ca": "Gestionar la ràbia", "sl": "Obvladovanje jeze"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk öfkeyi tanımayı ve yapıcı şekilde ele almayı öğrenir.", "bg": "Детето се научава да разпознава гнева и да се справя конструктивно.", "ro": "Copilul învață să recunoască furia și să o gestioneze constructiv.", "pl": "Dziecko uczy się rozpoznawać złość i radzić sobie z nią konstruktywnie.", "lt": "Vaikas mokosi atpažinti pyktį ir konstruktyviai su juo elgtis.", "hu": "A gyerek megtanulja felismerni a dühöt és konstruktívan kezelni.", "ca": "El nen aprèn a reconèixer la ràbia i gestionar-la de manera constructiva.", "sl": "Otrok se nauči prepoznati jezo in z njo konstruktivno ravnati."}'::jsonb WHERE theme_key = 'anger_management';

UPDATE learning_themes SET labels = labels || '{"tr": "Dürüstlük", "bg": "Честност", "ro": "Onestitate", "pl": "Szczerość", "lt": "Sąžiningumas", "hu": "Őszinteség", "ca": "Honestedat", "sl": "Poštenost"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk doğrunun ve samimiyetin değerini öğrenir.", "bg": "Детето научава стойността на истината и искреността.", "ro": "Copilul învață valoarea adevărului și a sincerității.", "pl": "Dziecko uczy się wartości prawdy i szczerości.", "lt": "Vaikas išmoksta tiesos ir nuoširdumo vertę.", "hu": "A gyerek megtanulja az igazság és az őszinteség értékét.", "ca": "El nen aprèn el valor de la veritat i la sinceritat.", "sl": "Otrok se nauči vrednosti resnice in iskrenosti."}'::jsonb WHERE theme_key = 'honesty';

UPDATE learning_themes SET labels = labels || '{"tr": "Bağımsızlık", "bg": "Независимост", "ro": "Independență", "pl": "Niezależność", "lt": "Nepriklausomumas", "hu": "Önállóság", "ca": "Independència", "sl": "Samostalnost"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk kendi başına denemeyi ve kendi kararlarını almayı öğrenir.", "bg": "Детето се научава да опитва самостоятелно и да взима решения.", "ro": "Copilul învață să încerce singur și să ia propriile decizii.", "pl": "Dziecko uczy się próbować samodzielnie i podejmować własne decyzje.", "lt": "Vaikas mokosi bandyti pats ir priimti savo sprendimus.", "hu": "A gyerek megtanulja egyedül kipróbálni és saját döntéseket hozni.", "ca": "El nen aprèn a provar coses sol i prendre les seves decisions.", "sl": "Otrok se nauči sam poskušati in sprejemati lastne odločitve."}'::jsonb WHERE theme_key = 'independence';

UPDATE learning_themes SET labels = labels || '{"tr": "Sorumluluk Almak", "bg": "Поемане на отговорност", "ro": "A-și asuma responsabilitatea", "pl": "Branie odpowiedzialności", "lt": "Atsakomybės prisiėmimas", "hu": "Felelősségvállalás", "ca": "Assumir la responsabilitat", "sl": "Prevzemati odgovornost"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk eylemleri ve sözleri sahiplenmeyi öğrenir.", "bg": "Детето се научава да отстоява постъпките и обещанията си.", "ro": "Copilul învață să-și asume acțiunile și promisiunile.", "pl": "Dziecko uczy się stać murem za czynami i obietnicami.", "lt": "Vaikas mokosi atsakyti už savo veiksmus ir pažadus.", "hu": "A gyerek megtanulja kiállni tettei és ígéretei mellett.", "ca": "El nen aprèn a fer-se responsable dels seus actes i promeses.", "sl": "Otrok se nauči zavzeti za svoja dejanja in obljube."}'::jsonb WHERE theme_key = 'responsibility';

UPDATE learning_themes SET labels = labels || '{"tr": "Hataları Kabul Etmek", "bg": "Признаване на грешки", "ro": "Recunoașterea greșelilor", "pl": "Przyznawanie się do błędów", "lt": "Klaidų pripažinimas", "hu": "Hibák beismerése", "ca": "Admetre els errors", "sl": "Priznanje napak"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk hata yapmanın insani olduğunu ve bundan ders çıkarılabileceğini öğrenir.", "bg": "Детето научава, че грешките са човешки и от тях се учи.", "ro": "Copilul învață că a greși e uman și că poți învăța din greșeli.", "pl": "Dziecko uczy się, że błędy są ludzkie i można się z nich uczyć.", "lt": "Vaikas išmoksta, kad klysti žmogiška ir iš klaidų galima mokytis.", "hu": "A gyerek megtanulja, hogy a hibázás emberi dolog és tanulni lehet belőle.", "ca": "El nen aprèn que equivocar-se és humà i s''hi pot aprendre.", "sl": "Otrok se nauči, da je delanje napak človeško in da se iz njih lahko uči."}'::jsonb WHERE theme_key = 'admitting_mistakes';

UPDATE learning_themes SET labels = labels || '{"tr": "Merak ve Soru Sormak", "bg": "Любопитство и задаване на въпроси", "ro": "Curiozitate și a pune întrebări", "pl": "Ciekawość i zadawanie pytań", "lt": "Smalsumas ir klausimų uždavinėjimas", "hu": "Kíváncsiság és kérdezés", "ca": "Curiositat i fer preguntes", "sl": "Radovednost in postavljanje vprašanj"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk soru sormanın anlamanın ilk adımı olduğunu öğrenir.", "bg": "Детето научава, че задаването на въпроси е първата стъпка към разбирането.", "ro": "Copilul învață că a pune întrebări e primul pas către înțelegere.", "pl": "Dziecko uczy się, że zadawanie pytań to pierwszy krok do zrozumienia.", "lt": "Vaikas išmoksta, kad klausimų uždavinėjimas yra pirmas žingsnis į supratimą.", "hu": "A gyerek megtanulja, hogy a kérdezés az első lépés a megértés felé.", "ca": "El nen aprèn que fer preguntes és el primer pas per entendre.", "sl": "Otrok se nauči, da je postavljanje vprašanj prvi korak do razumevanja."}'::jsonb WHERE theme_key = 'curiosity';

UPDATE learning_themes SET labels = labels || '{"tr": "Problem Çözme", "bg": "Решаване на проблеми", "ro": "Rezolvarea problemelor", "pl": "Rozwiązywanie problemów", "lt": "Problemų sprendimas", "hu": "Problémamegoldás", "ca": "Resolució de problemes", "sl": "Reševanje problemov"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk zorluklara sistematik yaklaşmayı öğrenir.", "bg": "Детето се научава да подхожда системно към предизвикателствата.", "ro": "Copilul învață să abordeze provocările sistematic.", "pl": "Dziecko uczy się systematycznie podchodzić do wyzwań.", "lt": "Vaikas mokosi sistemingai spręsti iššūkius.", "hu": "A gyerek megtanulja rendszerszerűen megközelíteni a kihívásokat.", "ca": "El nen aprèn a abordar els reptes de manera sistemàtica.", "sl": "Otrok se nauči izzivom pristopati sistematično."}'::jsonb WHERE theme_key = 'problem_solving';

UPDATE learning_themes SET labels = labels || '{"tr": "Yaratıcılık ve Farklı Düşünme", "bg": "Креативност и нестандартно мислене", "ro": "Creativitate și gândire neconvențională", "pl": "Kreatywność i nieszablonowe myślenie", "lt": "Kūrybiškumas ir neįprastas mąstymas", "hu": "Kreativitás és önálló gondolkodás", "ca": "Creativitat i pensar de manera diferent", "sl": "Ustvarjalnost in drugačen način razmišljanja"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk kendi fikirlerini geliştirmeyi ve yaratıcı çözümler bulmayı öğrenir.", "bg": "Детето се научава да развива собствени идеи и да намира творчески решения.", "ro": "Copilul învață să-și dezvolte ideile și să găsească soluții creative.", "pl": "Dziecko uczy się rozwijać własne pomysły i znajdować kreatywne rozwiązania.", "lt": "Vaikas mokosi kurti savo idėjas ir rasti kūrybiškus sprendimus.", "hu": "A gyerek megtanulja saját ötleteket kifejleszteni és kreatív megoldásokat találni.", "ca": "El nen aprèn a desenvolupar les seves idees i trobar solucions creatives.", "sl": "Otrok se nauči razvijati lastne ideje in iskati ustvarjalne rešitve."}'::jsonb WHERE theme_key = 'creativity';
