-- ============================================================
-- T-C1: DB-Übersetzungen — story_subtypes
-- Adds: tr, bg, ro, pl, lt, hu, ca, sl to labels + descriptions
-- Merge via JSONB ||. WHERE theme_key + subtype_key.
-- ============================================================

UPDATE story_subtypes SET labels = labels || '{"tr": "Büyülü Orman", "bg": "Магическа гора", "ro": "Pădure încântată", "pl": "Zaczarowany las", "lt": "Apburta miška", "hu": "Varázserdő", "ca": "Bosc encantat", "sl": "Začarani gozd"}'::jsonb, descriptions = descriptions || '{"tr": "Konuşan hayvanlar ve gizemli yaratıklarla dolu büyülü bir ormanda geçen bir hikaye", "bg": "История в магическа гора с говорещи животни и мистериозни създания", "ro": "O poveste într-o pădure magică plină de animale vorbitoare și ființe misterioase", "pl": "Historia w magicznym lesie pełnym mówiących zwierząt i tajemniczych stworzeń", "lt": "Pasaka magiškame miške, pilname kalbančių gyvūnų ir paslaptingų būtybių", "hu": "Egy történet egy varázserdőben, tele beszélő állatokkal és rejtélyes lényekkel", "ca": "Una història en un bosc màgic ple d''animals parlants i criatures misterioses", "sl": "Zgodba v čarobnem gozdu polnem govorečih živali in skrivnostnih bitij"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'enchanted_forest';

UPDATE story_subtypes SET labels = labels || '{"tr": "Masal Farklı", "bg": "Приказка с обрат", "ro": "Basm cu twist", "pl": "Baśń na opak", "lt": "Pasaka kitaip", "hu": "Tündérmese megfordítva", "ca": "Conte de fades amb gir", "sl": "Pravljica na novo"}'::jsonb, descriptions = descriptions || '{"tr": "Tanıdık bir masal motifi yeni ve şaşırtıcı şekilde anlatılır", "bg": "Познат приказен мотив разказан по нов и изненадващ начин", "ro": "Un motiv de basm cunoscut repovestit într-un mod nou și surprinzător", "pl": "Znany motyw baśniowy opowiedziany w nowy i zaskakujący sposób", "lt": "Pažįstama pasakos tema pasakojama naujai ir stebinančiai", "hu": "Egy ismert tündérmese motívum új és meglepő módon mesélve", "ca": "Un motiu de conte conegut explicat d''una manera nova i sorprenent", "sl": "Znana pravljična motivacija pripovedana na nov in presenetljiv način"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'fairy_tale_twist';

UPDATE story_subtypes SET labels = labels || '{"tr": "Büyülü Yaratık Dostluğu", "bg": "Приятелство с магическо създание", "ro": "Prietenie cu o creatură magică", "pl": "Przyjaźń z magicznym stworzeniem", "lt": "Draugystė su magiška būtybe", "hu": "Varázslény barátság", "ca": "Amistat amb criatura màgica", "sl": "Prijateljstvo z magičnim bitjem"}'::jsonb, descriptions = descriptions || '{"tr": "Bir çocuk büyülü bir varlık bulur veya kurtarır ve ayrılmaz arkadaş olurlar", "bg": "Детето намира или спасява магическо създание и стават неразделни приятели", "ro": "Un copil găsește sau salvează o creatură magică și devin prieteni inseparabili", "pl": "Dziecko znajduje lub ratuje magiczne stworzenie i stają się nierozłączni", "lt": "Vaikas randa arba gelbėja magišką būtybę ir jie tampa neatskiriamais draugais", "hu": "Egy gyerek talál vagy megment egy varázslényt, és elválaszthatatlan barátok lesznek", "ca": "Un nen troba o rescata una criatura màgica i es fan amics inseparables", "sl": "Otrok najde ali reši čarobno bitje in postaneta neločljiva prijatelja"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'magical_creature_friendship';

UPDATE story_subtypes SET labels = labels || '{"tr": "Küçülme ve Büyüme", "bg": "Свиване и растеж", "ro": "Mic și mare", "pl": "Kurczenie i rośnięcie", "lt": "Mažėjimas ir augimas", "hu": "Zsugorodás és növekedés", "ca": "Enconguir-se i créixer", "sl": "Skrčenje in rast"}'::jsonb, descriptions = descriptions || '{"tr": "Biri karınca boyuna küçülür veya evlerin üzerine çıkacak kadar büyür", "bg": "Някой се свива до размера на мравка или пораства над къщите", "ro": "Cineva se micșorează la mărimea unei furnici sau crește mai mare decât casele", "pl": "Ktoś kurczy się do rozmiaru mrówki lub rośnie wyżej niż domy", "lt": "Kažkas susitraukia iki skruzdėlos dydžio arba išauga aukščiau nei namai", "hu": "Valaki hangyaméretre zsugorodik vagy magasabbra nő a házaknál", "ca": "Algú s''encongeix com una formiga o creix més alt que les cases", "sl": "Nekdo se skrči na velikost mravlje ali zraste višje od hiš"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'shrinking_growing';

UPDATE story_subtypes SET labels = labels || '{"tr": "Uçuş Macerası", "bg": "Летящо приключение", "ro": "Aventură zburătoare", "pl": "Latająca przygoda", "lt": "Skraidymo nuotykis", "hu": "Repülő kaland", "ca": "Aventura voladora", "sl": "Leteča pustolovščina"}'::jsonb, descriptions = descriptions || '{"tr": "Büyülü bir nesne, yaratık veya kendi gücünle uçmak", "bg": "Летене с магически предмет, създание или със собствени сили", "ro": "Zburat pe un obiect magic, cu o creatură sau cu puteri proprii", "pl": "Latanie na magicznym przedmiocie, stworze lub własną mocą", "lt": "Skraidymas ant magiško daikto, būtybės ar savo jėga", "hu": "Repülés varázstárgyon, lényen vagy saját erőből", "ca": "Volar amb un objecte màgic, una criatura o amb els teus poders", "sl": "Letenje na čarobnem predmetu, bitju ali z lastno močjo"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'flying_adventure';

UPDATE story_subtypes SET labels = labels || '{"tr": "Başka Dünyaya Portal", "bg": "Портал към друг свят", "ro": "Portal către altă lume", "pl": "Portal do innego świata", "lt": "Portalas į kitą pasaulį", "hu": "Portál másik világba", "ca": "Portal a un altre món", "sl": "Portal v drug svet"}'::jsonb, descriptions = descriptions || '{"tr": "Büyülü bir kapı, kitap veya aynadan tamamen farklı bir dünyaya yolculuk", "bg": "Пътуване през магическа врата, книга или огледало в съвсем друг свят", "ro": "Călătorie printr-o ușă magică, carte sau oglindă într-o lume complet diferită", "pl": "Podróż przez magiczne drzwi, książkę lub lustro do zupełnie innego świata", "lt": "Kelionė per magiškas duris, knygą ar veidrodį į visiškai kitokią pasaulį", "hu": "Utazás varázsajtón, könyvön vagy tükörön keresztül egy teljesen más világba", "ca": "Viatge a través d''una porta màgica, llibre o mirall a un món completament diferent", "sl": "Potovanje skozi čarobna vrata, knjigo ali ogledalo v popolnoma drug svet"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'portal_other_world';

UPDATE story_subtypes SET labels = labels || '{"tr": "Büyücü Okulu", "bg": "Училище за магия", "ro": "Școala de vrăjitori", "pl": "Szkoła czarodziejów", "lt": "Burtininkų mokykla", "hu": "Varázslóiskola", "ca": "Escola de bruixots", "sl": "Čarovniška šola"}'::jsonb, descriptions = descriptions || '{"tr": "Büyü, iksir ve sihirli dersler öğrenilen bir okulda maceralar", "bg": "Приключения в училище, където се учат заклинания, отвари и магически предмети", "ro": "Aventuri la o școală unde înveți vrăji, poțiuni și materii magice", "pl": "Przygody w szkole, gdzie uczy się zaklęć, eliksirów i magii", "lt": "Nuotykiai mokykloje, kur mokomasi burtų, eliksyrų ir magiškų dalykų", "hu": "Kalandok egy iskolában, ahol varázslatokat, bájitalokat és mágiát tanulnak", "ca": "Aventures en una escola on s''aprenen encanteris, pócimes i matèries màgiques", "sl": "Pustolovščine v šoli, kjer se učijo uroke, napitnice in čarobne predmete"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'wizard_school';

UPDATE story_subtypes SET labels = labels || '{"tr": "Laneti Kırmak", "bg": "Премахване на проклятието", "ro": "Ruperea blestemului", "pl": "Przełamanie klątwy", "lt": "Kerų laužymas", "hu": "Átok megtörése", "ca": "Trencar la maledicció", "sl": "Prekletstvo prekiniti"}'::jsonb, descriptions = descriptions || '{"tr": "Bir lanet kırılmalı — ama çözüm beklediğin gibi değil", "bg": "Проклятието трябва да бъде премахнато — но решението не е това, което очакваш", "ro": "Un blestem trebuie rupt — dar soluția nu e ce te aștepți", "pl": "Klątwa musi zostać przełamana — ale rozwiązanie jest inne niż myślisz", "lt": "Kerai turi būti laužomi — bet sprendimas ne toks, kokio tikėjaisi", "hu": "Az átoknak törnie kell — de a megoldás nem az, amire számítasz", "ca": "Una maledicció s''ha de trencar — però la solució no és la que t''esperes", "sl": "Prekletstvo je treba prekiniti — a rešitev ni tista, ki jo pričakuješ"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'curse_breaking';

UPDATE story_subtypes SET labels = labels || '{"tr": "Rüya Yolculuğu", "bg": "Пътуване в съня", "ro": "Călătorie în vis", "pl": "Podróż we śnie", "lt": "Sapno kelionė", "hu": "Álomutazás", "ca": "Viatge de somnis", "sl": "Potovanje v sanjah"}'::jsonb, descriptions = descriptions || '{"tr": "Rüyada, rüya görenin duygularına göre değişen fantastik bir dünyada yolculuk", "bg": "Пътуване в фантастичен свят на сънища, който се променя с емоциите на сънуващия", "ro": "Călătorie printr-o lume de vis fantastică care se schimbă cu emoțiile visătorului", "pl": "Podróż przez fantastyczny świat snów zmieniający się z emocjami śniącego", "lt": "Kelionė fantastiška sapnų pasauliu, kuris kinta su sapnuotojo emocijomis", "hu": "Utazás egy fantasztikus álomvilágban, ami az álmodó érzelmeihez igazodik", "ca": "Viatge per un món de somnis fantàstic que canvia amb les emocions del somiador", "sl": "Potovanje skozi fantastičen svet sanj, ki se spreminja z čustvi sanjača"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'dream_journey';

UPDATE story_subtypes SET labels = labels || '{"tr": "Sualtı Krallığı", "bg": "Подводно кралство", "ro": "Regatul subacvatic", "pl": "Podwodne królestwo", "lt": "Povandeninė karalystė", "hu": "Vízalatti királyság", "ca": "Regne submarí", "sl": "Podvodno kraljestvo"}'::jsonb, descriptions = descriptions || '{"tr": "Sualtı maceralar: deniz kızları, batık şehirler, konuşan balıklar", "bg": "Подводни приключения: русалки, потънали градове, говорещи риби", "ro": "Aventuri subacvatice: sirene, orașe scufundate, pești vorbitori", "pl": "Podwodne przygody: syreny, zatopione miasta, mówiące ryby", "lt": "Povandeninės nuotykiai: undinės, nuskendusios miestai, kalbančios žuvys", "hu": "Vízalatti kalandok: sellők, elsüllyedt városok, beszélő halak", "ca": "Aventures submarines: sirenes, ciutats submergides, peixos parlants", "sl": "Podvodne pustolovščine: sirene, potopljena mesta, govoreče ribe"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'underwater_kingdom';

UPDATE story_subtypes SET labels = labels || '{"tr": "Zaman Döngüsü", "bg": "Времева примка", "ro": "Buclă temporală", "pl": "Pętla czasu", "lt": "Laiko kilpa", "hu": "Időhurok", "ca": "Bucle temporal", "sl": "Časovna zanka"}'::jsonb, descriptions = descriptions || '{"tr": "Aynı günü tekrar tekrar yaşamak ve nedenini bulmak", "bg": "Да преживееш същия ден отново и отново и да разбереш защо", "ro": "Să trăiești aceeași zi iar și iar și să înțelegi de ce", "pl": "Przeżywanie tego samego dnia w kółko i odkrywanie dlaczego", "lt": "Gyventi tą pačią dieną vėl ir vėl bei išsiaiškinti kodėl", "hu": "Ugyanazt a napot újra és újra élni és kideríteni miért", "ca": "Viure el mateix dia una i altra vegada i esbrinar per què", "sl": "Živeti isti dan znova in znova in ugotoviti zakaj"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'time_loop';

UPDATE story_subtypes SET labels = labels || '{"tr": "Görünmez Dünya", "bg": "Невидимият свят", "ro": "Lumea invizibilă", "pl": "Niewidzialny świat", "lt": "Nematomas pasaulis", "hu": "A láthatatlan világ", "ca": "El món invisible", "sl": "Nevidni svet"}'::jsonb, descriptions = descriptions || '{"tr": "Bizimkine paralel gizli bir dünya var — onu sadece birkaç kişi görebilir", "bg": "Скрит свят съществува успоредно на нашия — само малцина могат да го видят", "ro": "O lume ascunsă există paralel cu a noastră — doar câțiva o pot vedea", "pl": "Ukryty świat istnieje równolegle do naszego — tylko nieliczni go widzą", "lt": "Slaptas pasaulis egzistuoja lygiagrečiai su mūsų — tik keli gali jį matyti", "hu": "Egy rejtett világ párhuzamosan létezik a mienkkel — csak kevesen látják", "ca": "Un món amagat existeix en paral·lel al nostre — només uns pocs el poden veure", "sl": "Skrit svet obstaja vzporedno z našim — le redki ga vidijo"}'::jsonb WHERE theme_key = 'magic_fantasy' AND subtype_key = 'invisible_world';

-- adventure_action (11)
UPDATE story_subtypes SET labels = labels || '{"tr": "Hazine Avı", "bg": "Лов на съкровище", "ro": "Vânătoare de comori", "pl": "Poszukiwanie skarbu", "lt": "Lobis medžioklė", "hu": "Kincses vadászat", "ca": "Cacera del tresor", "sl": "Lov na zaklad"}'::jsonb, descriptions = descriptions || '{"tr": "Harita, bilmeceler ve ipuçları gizli bir hazineye götürür", "bg": "Карта, загадки и следи водят до скрит съкровище", "ro": "O hartă, ghicitori și indicii duc la o comoară ascunsă", "pl": "Mapa, zagadki i wskazówki prowadzą do ukrytego skarbu", "lt": "Žemėlapis, mįslės ir užuominos veda prie paslėpto lobio", "hu": "Egy térkép, rejtvények és nyomok egy rejtett kincshez vezetnek", "ca": "Un mapa, endevinalles i pistes condueixen a un tresor amagat", "sl": "Zemljevid, uganke in namigi vodijo do skritega zaklada"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'treasure_hunt';

UPDATE story_subtypes SET labels = labels || '{"tr": "Dedektif Vakası", "bg": "Детективска история", "ro": "Caz de detectiv", "pl": "Sprawa detektywistyczna", "lt": "Detektyvo byla", "hu": "Detektívtörténet", "ca": "Cas de detectiu", "sl": "Detektivski primer"}'::jsonb, descriptions = descriptions || '{"tr": "Bir şey kaybolmuş veya bir bilmece çözülmeli — zeka ve mantıkla", "bg": "Нещо изчезва или загадка трябва да се реши — с остроумие и логика", "ro": "Ceva a dispărut sau un puzzle trebuie rezolvat — cu istețime și logică", "pl": "Coś zniknęło lub zagadka do rozwiązania — sprytem i logiką", "lt": "Kažkas dingo arba mįslė turi būti išspręsta — sumanumu ir logika", "hu": "Valami eltűnt vagy rejtélyt kell megoldani — eszével és logikával", "ca": "Alguna cosa ha desaparegut o s''ha de resoldre un enigma — amb enginy i lògica", "sl": "Nekaj je izginilo ali uganko je treba rešiti — z duhovitostjo in logiko"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'detective_case';

UPDATE story_subtypes SET labels = labels || '{"tr": "Zaman Yolculuğu", "bg": "Пътуване във времето", "ro": "Călătorie în timp", "pl": "Podróż w czasie", "lt": "Kelionė laiku", "hu": "Időutazás", "ca": "Viatge en el temps", "sl": "Potovanje v času"}'::jsonb, descriptions = descriptions || '{"tr": "Geçmişe veya geleceğe yolculuk ve orada macera yaşamak", "bg": "Пътуване в миналото или бъдещето и преживяване на приключение там", "ro": "Călătorie în trecut sau viitor și aventură acolo", "pl": "Podróż w przeszłość lub przyszłość i przeżycie tam przygody", "lt": "Kelionė į praeitį arba ateitį ir nuotykiai ten", "hu": "Utazás a múltba vagy a jövőbe és kalandélmény ott", "ca": "Viatge al passat o al futur i viure una aventura allà", "sl": "Potovanje v preteklost ali prihodnost in pustolovščina tam"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'time_travel';

UPDATE story_subtypes SET labels = labels || '{"tr": "Kurtarma Görevi", "bg": "Спасителна мисия", "ro": "Misiune de salvare", "pl": "Misja ratunkowa", "lt": "Išgelbėjimo misija", "hu": "Mentőakció", "ca": "Missió de rescat", "sl": "Reševalna misija"}'::jsonb, descriptions = descriptions || '{"tr": "Birini veya bir şeyi kurtarmak gerekiyor — zamana karşı", "bg": "Някой или нещо трябва да бъде спасено — срещу времето", "ro": "Cineva sau ceva trebuie salvat — în cursul timpului", "pl": "Ktoś lub coś trzeba uratować — w wyścigu z czasem", "lt": "Kažkas arba kažkas turi būti išgelbėtas — prieš laiką", "hu": "Valakit vagy valamit meg kell menteni — az idővel versenyezve", "ca": "Algú o alguna cosa s''ha de rescatar — contra rellotge", "sl": "Nekoga ali nekaj je treba rešiti — v teku s časom"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'rescue_mission';

UPDATE story_subtypes SET labels = labels || '{"tr": "Casusluk Görevi", "bg": "Шпионска мисия", "ro": "Misiune de spion", "pl": "Misja szpiegowska", "lt": "Šnipų misija", "hu": "Kémküldetés", "ca": "Missió d''espia", "sl": "Vohunska misija"}'::jsonb, descriptions = descriptions || '{"tr": "Gizli çalışmak, şifreleri çözmek ve gizli bir görevi tamamlamak", "bg": "Работа под прикритие, разбиване на кодове и изпълнение на тайна мисия", "ro": "A lucra sub acoperire, a sparge coduri și a finaliza o misiune secretă", "pl": "Działanie pod przykrywką, łamanie szyfrów i wykonanie tajnej misji", "lt": "Dirbti slaptai, įveikti kodus ir atlikti slaptą misiją", "hu": "Bújkálás, kódok feltörése és titkos küldetés teljesítése", "ca": "Actuar en secret, desxifrar codis i completar una missió secreta", "sl": "Delovanje pod krinko, razbijanje kodov in opraviti skrivno misijo"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'spy_mission';

UPDATE story_subtypes SET labels = labels || '{"tr": "Vahşi Doğada Hayatta Kalma", "bg": "Оцеляване в природата", "ro": "Supraviețuire în natură", "pl": "Przetrwanie na dzikiej ziemi", "lt": "Išgyvenimas gamtoje", "hu": "Túlélés a vadonban", "ca": "Supervivença a la natura", "sl": "Preživetje v naravi"}'::jsonb, descriptions = descriptions || '{"tr": "Doğada yalnız veya ikili hayatta kalmak — cesaret ve beceriyle", "bg": "Оцеляване сам или по двойки в природата — с смелост и изобретателност", "ro": "Supraviețuire singur sau în doi în natură — cu curaj și ingeniozitate", "pl": "Przetrwanie samemu lub we dwoje w przyrodzie — z odwagą i pomysłowością", "lt": "Išgyventi vienam ar dviem gamtoje — su drąsa ir išradingumu", "hu": "Egyedül vagy kettesben túlélni a természetben — bátorsággal és találékonyássággal", "ca": "Sobrevivir sol o en parella a la natura — amb coratge i enginy", "sl": "Preživeti sam ali v dvoje v naravi — s pogumom in domišljijo"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'survival_nature';

UPDATE story_subtypes SET labels = labels || '{"tr": "Keşif ve Keşif", "bg": "Експедиция и откритие", "ro": "Expediție și descoperire", "pl": "Ekspedycja i odkrycie", "lt": "Ekspedicija ir atradimas", "hu": "Expedíció és felfedezés", "ca": "Expedició i descobriment", "sl": "Ekspedicija in odkrivanje"}'::jsonb, descriptions = descriptions || '{"tr": "Bilinmeyene yolculuk ve yeni bir şey keşfetmek", "bg": "Пътуване в неизвестното за откриване на нещо ново", "ro": "O călătorie în necunoscut pentru a descoperi ceva nou", "pl": "Podróż w nieznane, by odkryć coś nowego", "lt": "Kelionė į nežinomą, kad atrastų ką nors naujo", "hu": "Utazás az ismeretlenbe valami új felfedezéséért", "ca": "Viatge a l''desconegut per descobrir alguna cosa nova", "sl": "Potovanje v neznano, da odkrijemo nekaj novega"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'expedition_discovery';

UPDATE story_subtypes SET labels = labels || '{"tr": "Yarış ve Rekabet", "bg": "Надпревара и състезание", "ro": "Cursă și competiție", "pl": "Wyścig i zawody", "lt": "Lenktynės ir varžybos", "hu": "Verseny és versengés", "ca": "Cursa i competició", "sl": "Tekma in tekmovanje"}'::jsonb, descriptions = descriptions || '{"tr": "Heyecanlı bir yarış veya sürpriz dönüşlerle dolu bir yarışma", "bg": "Вълнуваща надпревара или състезание с изненадващи обрати", "ro": "O cursă palpitantă sau competiție cu întorsături surprinzătoare", "pl": "Ekscytujący wyścig lub zawody z zaskakującymi zwrotami", "lt": "Įdomios lenktynės arba varžybos su netikėtais posūkiais", "hu": "Izgalmas verseny vagy versengés meglepő fordulatokkal", "ca": "Una cursa emocionant o una competició amb girs sorprenents", "sl": "Razburljiva tekma ali tekmovanje s presenečanji"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'race_competition';

UPDATE story_subtypes SET labels = labels || '{"tr": "Gece Macerası", "bg": "Нощно приключение", "ro": "Aventură de noapte", "pl": "Nocna przygoda", "lt": "Naktinis nuotykis", "hu": "Éjszakai kaland", "ca": "Aventura nocturna", "sl": "Nočna pustolovščina"}'::jsonb, descriptions = descriptions || '{"tr": "Gece beklenmedik bir şey olur — ve bir macera başlar", "bg": "През нощта се случва нещо неочаквано — и започва приключение", "ro": "Noaptea se întâmplă ceva neașteptat — și începe o aventură", "pl": "W nocy dzieje się coś nieoczekiwanego — i zaczyna się przygoda", "lt": "Naktį nutinka kažkas netikėto — ir prasideda nuotykis", "hu": "Éjjel valami váratlan történik — és egy kaland kezdődik", "ca": "De nit passa alguna cosa inesperada — i comença una aventura", "sl": "Ponoči se zgodi nekaj nepričakovanega — in začne se pustolovščina"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'night_adventure';

UPDATE story_subtypes SET labels = labels || '{"tr": "Gemi Kazası ve Ada", "bg": "Корабокрушение и остров", "ro": "Naufragiu și insulă", "pl": "Rozbicie i wyspa", "lt": "Laivo sudužimas ir sala", "hu": "Hajótörés és sziget", "ca": "Naufragi i illa", "sl": "Brodolom in otok"}'::jsonb, descriptions = descriptions || '{"tr": "Issız bir adada kalmak ve orada macera yaşamak", "bg": "Да останеш на пуст остров и да преживееш приключение там", "ro": "Să ești blocat pe o insulă pustie și să ai o aventură acolo", "pl": "Osiąść na bezludnej wyspie i przeżyć tam przygodę", "lt": "Būti užstrigusiam dykumoje saloje ir ten patirti nuotykius", "hu": "Egy lakatlan szigeten rekedni és ott kalandot élni", "ca": "Quedar encallat en una illa deserta i viure una aventura allà", "sl": "Obiti na pustem otoku in tam doživeti pustolovščino"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'shipwreck_island';

UPDATE story_subtypes SET labels = labels || '{"tr": "Yeraltı Keşif", "bg": "Подземно проучване", "ro": "Explorare subterană", "pl": "Podziemna eksploracja", "lt": "Pogrindžio tyrinėjimas", "hu": "Földalatti felfedezés", "ca": "Exploració subterrània", "sl": "Podzemna raziskava"}'::jsonb, descriptions = descriptions || '{"tr": "Gizli tüneller, gizli odalar ve yeraltı dünyalar keşfetmek", "bg": "Да откриеш тайни тунели, скрити стаи и подземни светове", "ro": "Să descoperi tuneluri secrete, camere ascunse și lumi subterane", "pl": "Odkrywanie tajnych tuneli, ukrytych komnat i podziemnych światów", "lt": "Atrasti slaptus tunelius, paslėptas patalpas ir požeminius pasaulius", "hu": "Titkos alagutak, rejtett szobák és földalatti világok felfedezése", "ca": "Descobrir túnels secrets, sales amagades i mons subterranis", "sl": "Odkriti skrivne predore, skrite sobe in podzemne svetove"}'::jsonb WHERE theme_key = 'adventure_action' AND subtype_key = 'underground_exploration';

-- real_life (10)
UPDATE story_subtypes SET labels = labels || '{"tr": "Sınıfta Yeni Çocuk", "bg": "Новото дете в класа", "ro": "Copilul nou la școală", "pl": "Nowy w klasie", "lt": "Naujas vaikas klasėje", "hu": "Új gyerek az osztályban", "ca": "El nen nou a la classe", "sl": "Nov otrok v razredu"}'::jsonb, descriptions = descriptions || '{"tr": "Sınıfa yeni biri gelir — ve her şey değişir", "bg": "Някой нов идва в класа — и всичко се променя", "ro": "Cineva nou vine în clasă — și totul se schimbă", "pl": "Ktoś nowy dołącza do klasy — i wszystko się zmienia", "lt": "Kažkas naujas atsiranda klasėje — ir viskas pasikeičia", "hu": "Valaki új jön az osztályba — és minden megváltozik", "ca": "Algú nou s''incorpora a la classe — i tot canvia", "sl": "Nekdo nov pride v razred — in vse se spremeni"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'new_kid_school';

UPDATE story_subtypes SET labels = labels || '{"tr": "Hayvan Kurtarma", "bg": "Спасяване на животно", "ro": "Salvare animal", "pl": "Ratowanie zwierzęcia", "lt": "Gyvūno gelbėjimas", "hu": "Állatmentés", "ca": "Rescat d''animal", "sl": "Reševanje živali"}'::jsonb, descriptions = descriptions || '{"tr": "Yaralı veya kayıp bir hayvan bulup ona yardım etmek", "bg": "Да намериш ранено или изгубено животно и да му помогнеш", "ro": "Să găsești un animal rănit sau pierdut și să-l ajuți", "pl": "Znaleźć ranne lub zagubione zwierzę i mu pomóc", "lt": "Rasti sužeistą arba pasiklyusį gyvūną ir jam padėti", "hu": "Egy sérült vagy elveszett állatot találni és megmenteni", "ca": "Trobar un animal ferit o perdut i ajudar-lo", "sl": "Najti ranjeno ali izgubljeno žival in ji pomagati"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'animal_rescue';

UPDATE story_subtypes SET labels = labels || '{"tr": "Aile Macerası", "bg": "Семейно приключение", "ro": "Aventură în familie", "pl": "Rodzinna przygoda", "lt": "Šeimos nuotykis", "hu": "Családi kaland", "ca": "Aventura en família", "sl": "Družinska pustolovščina"}'::jsonb, descriptions = descriptions || '{"tr": "Aileyle özel bir gün veya gezi — sürprizlerle", "bg": "Специален ден или излет с семейството — с изненади", "ro": "O zi sau excursie specială cu familia — cu surprize", "pl": "Specjalny dzień lub wycieczka z rodziną — z niespodziankami", "lt": "Ypatinga diena arba kelionė su šeima — su siurprizais", "hu": "Különleges nap vagy kirándulás a családdal — meglepetésekkel", "ca": "Un dia especial o viatge en família — amb sorpreses", "sl": "Poseben dan ali izlet z družino — s presenečenji"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'family_adventure';

UPDATE story_subtypes SET labels = labels || '{"tr": "Yemek ve Fırın Macerası", "bg": "Кулинарно приключение", "ro": "Aventură culinară", "pl": "Kulinarna przygoda", "lt": "Kulinarinis nuotykis", "hu": "Főzős-sütős kaland", "ca": "Aventura de cuina i forneria", "sl": "Kuharska in pekovska pustolovščina"}'::jsonb, descriptions = descriptions || '{"tr": "Mutfağda beklenmedik bir şey olur — tarif ters gider ya da hit olur", "bg": "В кухнята се случва нещо неочаквано — рецептата се обърква или става хит", "ro": "Ceva neașteptat se întâmplă în bucătărie — o rețetă dă greș sau devine hit", "pl": "W kuchni dzieje się coś nieoczekiwanego — przepis się nie udaje lub staje hitem", "lt": "Virtuvėje nutinka kažkas netikėto — receptas nepavyksta arba tampa hitų", "hu": "Valami váratlan történik a konyhában — a recept félresikerül vagy sikeres lesz", "ca": "Passa alguna cosa inesperada a la cuina — una recepta surt mal o és un èxit", "sl": "V kuhinji se zgodi nekaj nepričakovanega — recept ne uspe ali postane hit"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'cooking_baking';

UPDATE story_subtypes SET labels = labels || '{"tr": "Mahalle Gizemi", "bg": "Загадка в квартала", "ro": "Mister din cartier", "pl": "Tajemnica sąsiedztwa", "lt": "Kaimynystės mįslė", "hu": "A környék rejtélye", "ca": "Misteri del barri", "sl": "Soseska skrivnost"}'::jsonb, descriptions = descriptions || '{"tr": "Mahallede tuhaf bir şey oluyor — arkasında kim var?", "bg": "В квартала се случва нещо странно — кой стои зад това?", "ro": "În cartier se întâmplă ceva ciudat — cine e de vină?", "pl": "W sąsiedztwie dzieje się coś dziwnego — kto za tym stoi?", "lt": "Kaimynystėje vyksta kažkas keisto — kas už to stovi?", "hu": "A környéken valami furcsa történik — ki áll mögötte?", "ca": "Al barri passa alguna cosa estranya — qui hi ha darrere?", "sl": "V soseski se dogaja nekaj čudnega — kdo stoji za tem?"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'neighborhood_mystery';

UPDATE story_subtypes SET labels = labels || '{"tr": "Büyük Maç / Büyük Sahne", "bg": "Голямият мач / изпълнение", "ro": "Marele meci / spectacol", "pl": "Wielki mecz / występ", "lt": "Didžiosios varžybos / pasirodymas", "hu": "A nagy meccs / előadás", "ca": "El gran partit / actuació", "sl": "Velika tekma / nastop"}'::jsonb, descriptions = descriptions || '{"tr": "Önemli bir maç, konser veya okul oyunu için hazırlanmak", "bg": "Подготовка за важен мач, концерт или училищна постановка", "ro": "Pregătire pentru un meci, concert sau piesă de teatru important", "pl": "Przygotowanie do ważnego meczu, koncertu lub szkolnego przedstawienia", "lt": "Pasiruošimas svarbioms varžyboms, koncertui ar mokyklos spektakliui", "hu": "Felkészülés egy fontos meccsre, koncertre vagy iskolai előadásra", "ca": "Preparar-se per un partit, concert o obra d''escola important", "sl": "Priprava na pomembno tekmo, koncert ali šolsko predstavo"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'big_game_performance';

UPDATE story_subtypes SET labels = labels || '{"tr": "Yeni Eve Taşınmak", "bg": "Преместване в нов дом", "ro": "Mutare în casă nouă", "pl": "Przeprowadzka", "lt": "Persikraustymas į naujus namus", "hu": "Új otthonba költözés", "ca": "Mudança a casa nova", "sl": "Selitev v nov dom"}'::jsonb, descriptions = descriptions || '{"tr": "Yeni bir eve, şehre veya ülkeye taşınmak", "bg": "Да се преместиш в нов дом, град или държава", "ro": "Să te muți într-o casă, oraș sau țară nouă", "pl": "Przeprowadzka do nowego domu, miasta lub kraju", "lt": "Persikraustyti į naujus namus, miestą ar šalį", "hu": "Új házba, városba vagy országba költözni", "ca": "Mudar-se a una casa, ciutat o país nous", "sl": "Preselitev v nov dom, mesto ali državo"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'moving_new_home';

UPDATE story_subtypes SET labels = labels || '{"tr": "Gizli Hobi", "bg": "Тайното хоби", "ro": "Hobby-ul secret", "pl": "Sekretne hobby", "lt": "Slaptas pomėgis", "hu": "A titkos hobby", "ca": "El hobby secret", "sl": "Skriti hobi"}'::jsonb, descriptions = descriptions || '{"tr": "Bir çocuk başkalarının anlamadığı bir tutku keşfeder — ta ki herkesi şaşırtana kadar", "bg": "Детето открива страст която другите не разбират — докато не изненада всички", "ro": "Un copil descoperă o pasiune pe care alții nu o înțeleg — până când îi surprinde pe toți", "pl": "Dziecko odkrywa pasję, której inni nie rozumieją — aż zaskakuje wszystkich", "lt": "Vaikas atranda aistrą, kurios kiti nesupranta — kol nustebina visus", "hu": "Egy gyerek olyan szenvedélyt fedez fel, amit mások nem értenek — míg mindenkit meg nem lep", "ca": "Un nen descobreix una passió que els altres no entenen — fins que sorprèn tothom", "sl": "Otrok odkrije strast, ki je drugi ne razumejo — dokler ne preseneti vse"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'secret_hobby';

UPDATE story_subtypes SET labels = labels || '{"tr": "Büyükanne/Büyükbaba Hikayesi", "bg": "Историята на дядо/баба", "ro": "Povestea bunicilor", "pl": "Opowieść dziadków", "lt": "Senelių istorija", "hu": "Nagyszülők meséje", "ca": "La història dels avis", "sl": "Zgodba starih staršev"}'::jsonb, descriptions = descriptions || '{"tr": "Büyükanneler geçmişi anlatır — ve birden geçmiş canlanır", "bg": "Дядо и баба разказват за миналото — и изведнъж миналото оживява", "ro": "Bunicii povestesc despre trecut — și dintr-o dată trecutul prinde viață", "pl": "Dziadkowie opowiadają o przeszłości — i nagle przeszłość ożywa", "lt": "Seneliai pasakoja apie praeitį — ir staiga praeitis atgyja", "hu": "A nagyszülők a múltról mesélnek — és hirtelen a múlt életre kel", "ca": "Els avis expliquen el passat — i de cop el passat cobra vida", "sl": "Stari starši pripovedujejo o preteklosti — in nenadoma preteklost oživi"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'grandparent_story';

UPDATE story_subtypes SET labels = labels || '{"tr": "Çevre Macerası", "bg": "Еко приключение", "ro": "Aventură ecologică", "pl": "Eko przygoda", "lt": "Eko nuotykis", "hu": "Öko kaland", "ca": "Aventura ecològica", "sl": "Eko pustolovščina"}'::jsonb, descriptions = descriptions || '{"tr": "Doğanın yardıma ihtiyacı var — ve çocuklar harekete geçer", "bg": "Природата има нужда от помощ — и децата предприемат действие", "ro": "Natura are nevoie de ajutor — și copiii acționează", "pl": "Natura potrzebuje pomocy — i dzieci biorą sprawy w swoje ręce", "lt": "Gamtai reikia pagalbos — ir vaikai imasi veiksmų", "hu": "A természetnek segítségre van szüksége — és a gyerekek cselekednek", "ca": "La natura necessita ajuda — i els nens passen a l''acció", "sl": "Narava potrebuje pomoč — in otroci ukrepajo"}'::jsonb WHERE theme_key = 'real_life' AND subtype_key = 'eco_adventure';

-- surprise (10)
UPDATE story_subtypes SET labels = labels || '{"tr": "Kaos Komedisi", "bg": "Хаотична комедия", "ro": "Comedie haotică", "pl": "Komedia chaosu", "lt": "Chaoso komedija", "hu": "Káosz komédia", "ca": "Comèdia del caos", "sl": "Kaosna komedija"}'::jsonb, descriptions = descriptions || '{"tr": "Her şey ters gider — ve gittikçe daha komik olur", "bg": "Всичко се обърква — и става все по-забавно", "ro": "Totul merge greșit — și devine din ce în ce mai amuzant", "pl": "Wszystko idzie nie tak — i robi się coraz zabawniej", "lt": "Viskas eina ne taip — ir tampa vis juokingiau", "hu": "Minden félresikerül — és egyre viccesebb lesz", "ca": "Tot surt malament — i es torna més i més divertit", "sl": "Vse gre narobe — in postaja vse bolj smešno"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'chaos_comedy';

UPDATE story_subtypes SET labels = labels || '{"tr": "Rol Değişimi", "bg": "Размяна на роли", "ro": "Schimb de roluri", "pl": "Zamiana ról", "lt": "Vaidmenų apkeitimas", "hu": "Szerepcsere", "ca": "Intercanvi de rols", "sl": "Zamenjava vlog"}'::jsonb, descriptions = descriptions || '{"tr": "Çocuk ve yetişkin rollerini değiştirir — çocuk patron olur", "bg": "Дете и възрастен сменят ролите — детето е начело", "ro": "Copilul și adultul schimbă rolurile — copilul e șeful", "pl": "Dziecko i dorosły zamieniają się rolami — dziecko rządzi", "lt": "Vaikas ir suaugęs keičia vaidmenis — vaikas vadovauja", "hu": "A gyerek és a felnőtt felcseréli a szerepeket — a gyerek a főnök", "ca": "El nen i l''adult intercanvien els rols — el nen mana", "sl": "Otrok in odrasel zamenjata vlogi — otrok je glavni"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'role_reversal';

UPDATE story_subtypes SET labels = labels || '{"tr": "Beklenmedik Yetenek", "bg": "Неочакван талант", "ro": "Talent neașteptat", "pl": "Niespodziany talent", "lt": "Netikėtas talentas", "hu": "Váratlan tehetség", "ca": "Talent inesperat", "sl": "Nepričakovani talent"}'::jsonb, descriptions = descriptions || '{"tr": "Biri tamamen beklenmedik bir yetenek keşfeder", "bg": "Някой внезапно открива напълно неочаквана способност", "ro": "Cineva descoperă brusc o abilitate complet neașteptată", "pl": "Ktoś nagle odkrywa zupełnie nieoczekiwany talent", "lt": "Kažkas staiga atranda visiškai netikėtą gebėjimą", "hu": "Valaki hirtelen teljesen váratlan képességet fedez fel", "ca": "Algú descobreix de cop un talent completament inesperat", "sl": "Nekdo nenadoma odkrije popolnoma nepričakovan sposobnost"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'unexpected_talent';

UPDATE story_subtypes SET labels = labels || '{"tr": "Yanlış Giden Dilek", "bg": "Желание с последици", "ro": "Dorință care dă greș", "pl": "Życzenie, które się nie spełnia", "lt": "Nepavykęs noras", "hu": "Félresikerült kívánság", "ca": "Desig que surt malament", "sl": "Želja, ki gre narobe"}'::jsonb, descriptions = descriptions || '{"tr": "Bir dilek gerçekleşir — ama beklediğin gibi değil", "bg": "Желанието се сбъдва — но не както очакваш", "ro": "O dorință se îndeplinește — dar nu cum te aștepți", "pl": "Życzenie się spełnia — ale nie tak, jak myślisz", "lt": "Noras išsipildo — bet ne taip, kaip tikėjaisi", "hu": "Egy kívánság teljesül — de nem úgy, ahogy várod", "ca": "Un desig es compleix — però no com t''esperes", "sl": "Želja se uresniči — a ne tako, kot pričakuješ"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'wish_gone_wrong';

UPDATE story_subtypes SET labels = labels || '{"tr": "Konuşan Eşyalar", "bg": "Говорещи предмети", "ro": "Obiecte vorbitoare", "pl": "Mówiące przedmioty", "lt": "Kalbantys daiktai", "hu": "Beszélő tárgyak", "ca": "Objectes parlants", "sl": "Govoreči predmeti"}'::jsonb, descriptions = descriptions || '{"tr": "Günlük eşyalar canlanır ve kendi iradeleri olur", "bg": "Всекидневните предмети оживяват и имат собствена воля", "ro": "Obiectele zilnice prind viață și au voință proprie", "pl": "Codzienne przedmioty ożywają i mają własną wolę", "lt": "Kasdieniai daiktai atgyja ir turi savo valią", "hu": "A mindennapi tárgyak életre kelnek és saját akaratuk van", "ca": "Els objectes quotidians cobren vida i tenen voluntat pròpia", "sl": "Vsakodnevni predmeti oživijo in imajo lastno voljo"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'talking_objects';

UPDATE story_subtypes SET labels = labels || '{"tr": "Ters Gün", "bg": "Ден наопаки", "ro": "Ziua cu susul în jos", "pl": "Dzień na opak", "lt": "Atvirkštinė diena", "hu": "Fordított nap", "ca": "Dia al revés", "sl": "Dan naopako"}'::jsonb, descriptions = descriptions || '{"tr": "Her şeyin tersine döndüğü bir gün — yağmur yukarı düşer, okul gece başlar", "bg": "Ден, в който всичко е наопаки — дъждът пада нагоре, училището започва нощем", "ro": "O zi în care totul e cu susul în jos — ploaia cade în sus, școala începe noaptea", "pl": "Dzień, gdy wszystko jest na opak — deszcz leci w górę, szkoła zaczyna się nocą", "lt": "Diena, kai viskas atvirkščiai — lietus krenta aukštyn, mokykla prasideda naktį", "hu": "Egy nap, amikor minden fordítva van — az eső felfelé esik, az iskola éjjel kezdődik", "ca": "Un dia en què tot va al revés — la pluja puja, l''escola comença de nit", "sl": "Dan, ko je vse narobe — dež pada navzgor, šola se začne ponoči"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'backwards_day';

UPDATE story_subtypes SET labels = labels || '{"tr": "Büyük Karışıklık", "bg": "Голямото объркване", "ro": "Marea încurcătură", "pl": "Wielkie zamieszanie", "lt": "Didelė painiava", "hu": "A nagy kavarodás", "ca": "La gran barreja", "sl": "Velika zmešnjava"}'::jsonb, descriptions = descriptions || '{"tr": "Bir karışıklık zincirleme tepkime başlatır", "bg": "Една объркване предизвиква верижна реакция", "ro": "O încurcătură declanșează o reacție în lanț", "pl": "Jedno pomylenie wywołuje reakcję łańcuchową", "lt": "Viena painiava sukuria grandininę reakciją", "hu": "Egy összekeveredés láncreakciót indít el", "ca": "Una barreja desencadena una reacció en cadena", "sl": "Zmešnjava sproži verižno reakcijo"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'mix_up_confusion';

UPDATE story_subtypes SET labels = labels || '{"tr": "Sıradan Kahraman", "bg": "Обикновеният герой", "ro": "Eroul obișnuit", "pl": "Zwykły bohater", "lt": "Paprastas herojus", "hu": "A hétköznapi hős", "ca": "L''heroi ordinari", "sl": "Običajni junak"}'::jsonb, descriptions = descriptions || '{"tr": "Süper güç yok, sihir yok — sıradan bir çocuk doğru olanı yapar", "bg": "Без суперсила, без магия — обикновено дете прави правилното", "ro": "Fără superputere, fără magie — un copil obișnuit face ce e corect", "pl": "Bez supermocy, bez magii — zwykłe dziecko robi to, co słuszne", "lt": "Be supergalios, be magijos — paprastas vaikas daro teisingai", "hu": "Nincs szupererő, nincs varázslat — egy átlagos gyerek teszi a helyeset", "ca": "Sense superpoder, sense màgia — un nen ordinari fa el correcte", "sl": "Brez supermoči, brez magije — navaden otrok naredi pravo stvar"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'super_ordinary_hero';

UPDATE story_subtypes SET labels = labels || '{"tr": "Minik Dünya", "bg": "Миниатюрен свят", "ro": "Lumea în miniatură", "pl": "Miniaturowy świat", "lt": "Miniatūrinis pasaulis", "hu": "Miniatűr világ", "ca": "Món en miniatura", "sl": "Miniaturni svet"}'::jsonb, descriptions = descriptions || '{"tr": "Bir çekmecede, taşın altında veya duvarın arkasında minik bir uygarlık yaşar", "bg": "В чекмеджето, под камъка или зад стената живее миниатюрна цивилизация", "ro": "Într-un sertar, sub o piatră sau în spatele peretelui trăiește o civilizație minusculă", "pl": "W szufladzie, pod kamieniem lub za ścianą żyje miniaturowa cywilizacja", "lt": "Skirtyje, po akmeniu arba už sienos gyvena mažyčė civilizacija", "hu": "Egy fiókban, egy kő alatt vagy a fal mögött egy minuszcula civilizáció él", "ca": "En un calaix, sota una pedra o darrere la paret viu una civilització minúscula", "sl": "V predalu, pod kamnom ali za steno živi miniaturna civilizacija"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'miniature_world';

UPDATE story_subtypes SET labels = labels || '{"tr": "Yabancıdan Mektup", "bg": "Писмо от непознат", "ro": "Scrisoare de la un străin", "pl": "List od nieznajomego", "lt": "Laiškas nuo nepažįstamo", "hu": "Levél egy idegentől", "ca": "Carta d''un desconegut", "sl": "Pismo od neznanca"}'::jsonb, descriptions = descriptions || '{"tr": "Gizemli bir mektup gelir — ve beklenmedik bir yolculuğa götürür", "bg": "Пристига мистериозно писмо — и води до неочаквано пътуване", "ro": "Sosea o scrisoare misterioasă — și duce la o călătorie neașteptată", "pl": "Przychodzi tajemniczy list — i prowadzi do nieoczekiwanej podróży", "lt": "Ateina paslaptingas laiškas — ir veda į netikėtą kelionę", "hu": "Egy rejtélyes levél érkezik — és váratlan utazáshoz vezet", "ca": "Arriba una carta misteriosa — i condueix a un viatge inesperat", "sl": "Prispe skrivnostno pismo — in vodi do nepričakovane poti"}'::jsonb WHERE theme_key = 'surprise' AND subtype_key = 'letter_from_stranger';
