-- ============================================================
-- Add Ukrainian (uk) and Russian (ru) to DB translation JSONB
-- learning_themes, content_themes_by_level, image_styles
-- ============================================================

-- learning_themes (15 rows)
UPDATE learning_themes SET labels = labels || '{"uk": "Ділитися та щедрість", "ru": "Делиться и щедрость"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться, що ділитися — це радість і міцні звʼязки.", "ru": "Ребёнок учится, что делиться приносит радость и укрепляет связи."}'::jsonb WHERE theme_key = 'sharing';
UPDATE learning_themes SET labels = labels || '{"uk": "Емпатія та зміна перспективи", "ru": "Эмпатия и смена перспективы"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться ставити себе на місце інших і розуміти їхні почуття.", "ru": "Ребёнок учится ставить себя на место других и понимать их чувства."}'::jsonb WHERE theme_key = 'empathy';
UPDATE learning_themes SET labels = labels || '{"uk": "Підтримка дружби", "ru": "Поддержка дружбы"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться будувати і підтримувати добрі дружні стосунки.", "ru": "Ребёнок учится строить и поддерживать хорошую дружбу."}'::jsonb WHERE theme_key = 'friendship';
UPDATE learning_themes SET labels = labels || '{"uk": "Співпраця", "ru": "Сотрудничество"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться, що разом можна досягти більшого.", "ru": "Ребёнок учится, что вместе можно достичь большего."}'::jsonb WHERE theme_key = 'cooperation';
UPDATE learning_themes SET labels = labels || '{"uk": "Терпіння та вміння чекати", "ru": "Терпение и умение ждать"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться, що добрі речі іноді потребують часу.", "ru": "Ребёнок учится, что хорошее иногда требует времени."}'::jsonb WHERE theme_key = 'patience';
UPDATE learning_themes SET labels = labels || '{"uk": "Вміння справлятися з фрустрацією", "ru": "Умение справляться с фрустрацией"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться справлятися з розчаруваннями та невдачами.", "ru": "Ребёнок учится справляться с разочарованиями и неудачами."}'::jsonb WHERE theme_key = 'frustration';
UPDATE learning_themes SET labels = labels || '{"uk": "Сміливість і подолання соромʼязливості", "ru": "Смелость и преодоление застенчивости"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться бути сміливою і пробувати нове.", "ru": "Ребёнок учится быть смелым и пробовать новое."}'::jsonb WHERE theme_key = 'courage';
UPDATE learning_themes SET labels = labels || '{"uk": "Вміння керувати гнівом", "ru": "Управление гневом"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться розпізнавати гнів і конструктивно з ним поводитися.", "ru": "Ребёнок учится распознавать гнев и справляться с ним конструктивно."}'::jsonb WHERE theme_key = 'anger_management';
UPDATE learning_themes SET labels = labels || '{"uk": "Чесність", "ru": "Честность"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться цінувати правду та щирість.", "ru": "Ребёнок учится ценить правду и искренность."}'::jsonb WHERE theme_key = 'honesty';
UPDATE learning_themes SET labels = labels || '{"uk": "Самостійність", "ru": "Самостоятельность"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться пробувати сама і приймати рішення.", "ru": "Ребёнок учится пробовать сам и принимать решения."}'::jsonb WHERE theme_key = 'independence';
UPDATE learning_themes SET labels = labels || '{"uk": "Відповідальність", "ru": "Ответственность"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться відповідати за вчинки та обіцянки.", "ru": "Ребёнок учится отвечать за поступки и обещания."}'::jsonb WHERE theme_key = 'responsibility';
UPDATE learning_themes SET labels = labels || '{"uk": "Визнання помилок", "ru": "Признание ошибок"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться, що помилятися нормально і з помилок вчаться.", "ru": "Ребёнок учится, что ошибаться нормально и на ошибках учатся."}'::jsonb WHERE theme_key = 'admitting_mistakes';
UPDATE learning_themes SET labels = labels || '{"uk": "Цікавість і ставлення питань", "ru": "Любознательность и вопросы"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться, що ставити питання — перший крок до розуміння.", "ru": "Ребёнок учится, что задавать вопросы — первый шаг к пониманию."}'::jsonb WHERE theme_key = 'curiosity';
UPDATE learning_themes SET labels = labels || '{"uk": "Розвʼязання проблем", "ru": "Решение проблем"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться системно підходити до складних ситуацій.", "ru": "Ребёнок учится системно подходить к трудностям."}'::jsonb WHERE theme_key = 'problem_solving';
UPDATE learning_themes SET labels = labels || '{"uk": "Креативність і нестандартне мислення", "ru": "Креативность и нестандартное мышление"}'::jsonb, descriptions = descriptions || '{"uk": "Дитина вчиться розвивати ідеї та знаходити творчі рішення.", "ru": "Ребёнок учится развивать идеи и находить творческие решения."}'::jsonb WHERE theme_key = 'creativity';

-- content_themes_by_level (14 rows) — labels + example_texts
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Конфлікт між друзями", "ru": "Конфликт между друзьями"}'::jsonb, example_texts = example_texts || '{"uk": "Мія й Том сперечалися за останнє печиво, але потім знайшли рішення.", "ru": "Миа и Том поссорились из-за последнего печенья, но потом нашли решение."}'::jsonb WHERE theme_key = 'friend_conflict';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Легка сумність", "ru": "Лёгкая грусть"}'::jsonb, example_texts = example_texts || '{"uk": "Коли повітряна кулька влетіла, Лео засумував — але потім побачив веселку.", "ru": "Когда шарик улетел, Лео грустил — но потом увидел радугу."}'::jsonb WHERE theme_key = 'minor_sadness';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Короткі моменти страху", "ru": "Короткие моменты страха"}'::jsonb, example_texts = example_texts || '{"uk": "У темному лісі він почув шум — це була лише маленька білка!", "ru": "В тёмном лесу он услышал шум — это была всего лишь маленькая белочка!"}'::jsonb WHERE theme_key = 'minor_fear';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Розчарування", "ru": "Разочарование"}'::jsonb, example_texts = example_texts || '{"uk": "Пікнік скасували через дощ, але вдома збудували фортецю з ковдр.", "ru": "Пикник отменили из-за дождя, но дома построили крепость из одеял."}'::jsonb WHERE theme_key = 'disappointment';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Розлучення / Розставання", "ru": "Развод / Разлука"}'::jsonb, example_texts = example_texts || '{"uk": "Батьки Ліни тепер живуть у двох будинках — але обидва її люблять.", "ru": "Родители Лины теперь живут в двух домах — но оба её любят."}'::jsonb WHERE theme_key = 'divorce';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Переїзд / Зміни", "ru": "Переезд / Перемены"}'::jsonb, example_texts = example_texts || '{"uk": "Нове місто було чужим, але в школі хтось посміхнувся їй.", "ru": "Новый город был чужим, но в школе кто-то улыбнулся ей."}'::jsonb WHERE theme_key = 'moving';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Знущання", "ru": "Травля"}'::jsonb, example_texts = example_texts || '{"uk": "Ніхто не хотів сидіти поруч — поки новий хлопчик не запитав: Можна?", "ru": "Никто не хотел сидеть рядом — пока новый мальчик не спросил: Можно?"}'::jsonb WHERE theme_key = 'bullying';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Самотність", "ru": "Одиночество"}'::jsonb, example_texts = example_texts || '{"uk": "Він стояв один на краю майданчика — поки не помітив, що їжачок теж один.", "ru": "Он стоял один на краю площадки — пока не заметил, что ёжик тоже один."}'::jsonb WHERE theme_key = 'loneliness';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Смерть улюбленця", "ru": "Смерть питомца"}'::jsonb, example_texts = example_texts || '{"uk": "Рибка Бульба більше не плавала — але спогади залишились назавжди.", "ru": "Рыбка Пузырёк больше не плавала — но воспоминания остались навсегда."}'::jsonb WHERE theme_key = 'pet_death';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Ревнощі", "ru": "Ревность"}'::jsonb, example_texts = example_texts || '{"uk": "Коли зʼявилась дитина, Макс почувався непомітним — поки тато не взяв його у пригоду.", "ru": "Когда появился малыш, Макс чувствовал себя невидимым — пока папа не взял его в приключение."}'::jsonb WHERE theme_key = 'jealousy';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Смерть (відповідно для дітей)", "ru": "Смерть (подходяще для детей)"}'::jsonb, example_texts = example_texts || '{"uk": "Бабусі вже не було, але коли вітер крутив листя, Мія завжди думала про неї.", "ru": "Бабушки уже не было, но когда ветер кружил листья, Миа всегда думала о ней."}'::jsonb WHERE theme_key = 'death';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Війна / Втеча", "ru": "Война / Бегство"}'::jsonb, example_texts = example_texts || '{"uk": "Їм довелося покинути дім, але в рюкзаку була улюблена книга — частка дому.", "ru": "Им пришлось покинуть дом, но в рюкзаке была любимая книга — частичка дома."}'::jsonb WHERE theme_key = 'war_flight';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Серйозна хвороба", "ru": "Серьёзная болезнь"}'::jsonb, example_texts = example_texts || '{"uk": "Тато довго був у лікарні, але кожного дня йому малювали малюнок.", "ru": "Папа долго был в больнице, но каждый день ему рисовали картинку."}'::jsonb WHERE theme_key = 'serious_illness';
UPDATE content_themes_by_level SET labels = labels || '{"uk": "Складні сімейні структури", "ru": "Сложные семейные структуры"}'::jsonb, example_texts = example_texts || '{"uk": "Дві мами, тато далеко — але любові було стільки ж.", "ru": "Две мамы, папа далеко — но любви было столько же."}'::jsonb WHERE theme_key = 'complex_families';

-- image_styles (6 rows)
UPDATE image_styles SET labels = labels || '{"uk": "Книжка-картинка (мʼяка)", "ru": "Книжка-картинка (мягкая)"}'::jsonb, description = description || '{"uk": "Мʼякі, теплі кольори як у класичній книжці. Заокруглені форми, мʼякі переходи.", "ru": "Мягкие, тёплые цвета как в классической книжке. Округлые формы, мягкие переходы."}'::jsonb WHERE style_key = 'storybook_soft';
UPDATE image_styles SET labels = labels || '{"uk": "Книжка-картинка (яскрава)", "ru": "Книжка-картинка (яркая)"}'::jsonb, description = description || '{"uk": "Яскраві, теплі кольори. Чіткі лінії, виразні персонажі.", "ru": "Яркие, тёплые цвета. Чёткие линии, выразительные персонажи."}'::jsonb WHERE style_key = 'storybook_vibrant';
UPDATE image_styles SET labels = labels || '{"uk": "Манга / Аніме", "ru": "Манга / Аниме"}'::jsonb, description = description || '{"uk": "Стиль аніме: великі очі, динаміка, яскраві кольори. Дружній для дітей.", "ru": "Стиль аниме: большие глаза, динамика, яркие цвета. Подходит для детей."}'::jsonb WHERE style_key = 'manga_anime';
UPDATE image_styles SET labels = labels || '{"uk": "Пригодницький мультик", "ru": "Приключенческий мультик"}'::jsonb, description = description || '{"uk": "Веселий, динамічний стиль. Сміливі персонажі та яскравий світ.", "ru": "Весёлый, динамичный стиль. Смелые персонажи и яркий мир."}'::jsonb WHERE style_key = 'adventure_cartoon';
UPDATE image_styles SET labels = labels || '{"uk": "Графічний роман", "ru": "Графический роман"}'::jsonb, description = description || '{"uk": "Кіношний стиль графічного роману, драматичне світло.", "ru": "Кинематографичный стиль графического романа, драматичный свет."}'::jsonb WHERE style_key = 'graphic_novel';
UPDATE image_styles SET labels = labels || '{"uk": "Напівреалістичний", "ru": "Полуреалистичный"}'::jsonb, description = description || '{"uk": "Майже реалістична ілюстрація з художнім відтінком. Детально й атмосферно.", "ru": "Почти реалистичная иллюстрация с художественным оттенком. Детально и атмосферно."}'::jsonb WHERE style_key = 'semi_realistic';
