-- ============================================================
-- T-C1: DB-Übersetzungen — theme_rules
-- Adds: tr, bg, ro, pl, lt, hu, ca, sl to labels only
-- Key: theme_key, language (18 rows: 6 themes x de, en, fr)
-- ============================================================

UPDATE theme_rules SET labels = labels || '{"tr": "Masal ve Fantezi", "bg": "Приказки и фантазия", "ro": "Basm și fantezie", "pl": "Baśnie i fantastyka", "lt": "Pasakos ir fantastika", "hu": "Tündérmesék és fantázia", "ca": "Contes i fantasia", "sl": "Pravljice in fantazija"}'::jsonb WHERE theme_key = 'fantasy' AND language = 'fr';
UPDATE theme_rules SET labels = labels || '{"tr": "Masal ve Fantezi", "bg": "Приказки и фантазия", "ro": "Basm și fantezie", "pl": "Baśnie i fantastyka", "lt": "Pasakos ir fantastika", "hu": "Tündérmesék és fantázia", "ca": "Contes i fantasia", "sl": "Pravljice in fantazija"}'::jsonb WHERE theme_key = 'fantasy' AND language = 'de';
UPDATE theme_rules SET labels = labels || '{"tr": "Masal ve Fantezi", "bg": "Приказки и фантазия", "ro": "Basm și fantezie", "pl": "Baśnie i fantastyka", "lt": "Pasakos ir fantastika", "hu": "Tündérmesék és fantázia", "ca": "Contes i fantasia", "sl": "Pravljice in fantazija"}'::jsonb WHERE theme_key = 'fantasy' AND language = 'en';

UPDATE theme_rules SET labels = labels || '{"tr": "Macera ve Aksiyon", "bg": "Приключение и екшън", "ro": "Aventură și acțiune", "pl": "Przygoda i akcja", "lt": "Nuotykiai ir veiksmas", "hu": "Kaland és akció", "ca": "Aventura i acció", "sl": "Pustolovščina in akcija"}'::jsonb WHERE theme_key = 'action' AND language = 'fr';
UPDATE theme_rules SET labels = labels || '{"tr": "Macera ve Aksiyon", "bg": "Приключение и екшън", "ro": "Aventură și acțiune", "pl": "Przygoda i akcja", "lt": "Nuotykiai ir veiksmas", "hu": "Kaland és akció", "ca": "Aventura i acció", "sl": "Pustolovščina in akcija"}'::jsonb WHERE theme_key = 'action' AND language = 'de';
UPDATE theme_rules SET labels = labels || '{"tr": "Macera ve Aksiyon", "bg": "Приключение и екшън", "ro": "Aventură și acțiune", "pl": "Przygoda i akcja", "lt": "Nuotykiai ir veiksmas", "hu": "Kaland és akció", "ca": "Aventura i acció", "sl": "Pustolovščina in akcija"}'::jsonb WHERE theme_key = 'action' AND language = 'en';

UPDATE theme_rules SET labels = labels || '{"tr": "Hayvan Hikayeleri", "bg": "Истории с животни", "ro": "Povești cu animale", "pl": "Opowieści o zwierzętach", "lt": "Gyvūnų istorijos", "hu": "Állatos történetek", "ca": "Històries d''animals", "sl": "Zgodbe o živalih"}'::jsonb WHERE theme_key = 'animals' AND language = 'fr';
UPDATE theme_rules SET labels = labels || '{"tr": "Hayvan Hikayeleri", "bg": "Истории с животни", "ro": "Povești cu animale", "pl": "Opowieści o zwierzętach", "lt": "Gyvūnų istorijos", "hu": "Állatos történetek", "ca": "Històries d''animals", "sl": "Zgodbe o živalih"}'::jsonb WHERE theme_key = 'animals' AND language = 'de';
UPDATE theme_rules SET labels = labels || '{"tr": "Hayvan Hikayeleri", "bg": "Истории с животни", "ro": "Povești cu animale", "pl": "Opowieści o zwierzętach", "lt": "Gyvūnų istorijos", "hu": "Állatos történetek", "ca": "Històries d''animals", "sl": "Zgodbe o živalih"}'::jsonb WHERE theme_key = 'animals' AND language = 'en';

UPDATE theme_rules SET labels = labels || '{"tr": "Günlük Hayat ve Duygular", "bg": "Всекидневие и емоции", "ro": "Cotidian și emoții", "pl": "Codzienność i uczucia", "lt": "Kasdienybė ir jausmai", "hu": "Mindennapok és érzések", "ca": "Quotidà i emocions", "sl": "Vsakdan in čustva"}'::jsonb WHERE theme_key = 'everyday' AND language = 'fr';
UPDATE theme_rules SET labels = labels || '{"tr": "Günlük Hayat ve Duygular", "bg": "Всекидневие и емоции", "ro": "Cotidian și emoții", "pl": "Codzienność i uczucia", "lt": "Kasdienybė ir jausmai", "hu": "Mindennapok és érzések", "ca": "Quotidà i emocions", "sl": "Vsakdan in čustva"}'::jsonb WHERE theme_key = 'everyday' AND language = 'de';
UPDATE theme_rules SET labels = labels || '{"tr": "Günlük Hayat ve Duygular", "bg": "Всекидневие и емоции", "ro": "Cotidian și emoții", "pl": "Codzienność i uczucia", "lt": "Kasdienybė ir jausmai", "hu": "Mindennapok és érzések", "ca": "Quotidà i emocions", "sl": "Vsakdan in čustva"}'::jsonb WHERE theme_key = 'everyday' AND language = 'en';

UPDATE theme_rules SET labels = labels || '{"tr": "Mizah ve Kaos", "bg": "Хумор и хаос", "ro": "Umor și haos", "pl": "Humor i chaos", "lt": "Humoras ir chaosas", "hu": "Humor és káosz", "ca": "Humor i caos", "sl": "Humor in kaos"}'::jsonb WHERE theme_key = 'humor' AND language = 'fr';
UPDATE theme_rules SET labels = labels || '{"tr": "Mizah ve Kaos", "bg": "Хумор и хаос", "ro": "Umor și haos", "pl": "Humor i chaos", "lt": "Humoras ir chaosas", "hu": "Humor és káosz", "ca": "Humor i caos", "sl": "Humor in kaos"}'::jsonb WHERE theme_key = 'humor' AND language = 'de';
UPDATE theme_rules SET labels = labels || '{"tr": "Mizah ve Kaos", "bg": "Хумор и хаос", "ro": "Umor și haos", "pl": "Humor i chaos", "lt": "Humoras ir chaosas", "hu": "Humor és káosz", "ca": "Humor i caos", "sl": "Humor in kaos"}'::jsonb WHERE theme_key = 'humor' AND language = 'en';

UPDATE theme_rules SET labels = labels || '{"tr": "Öğrenme ve Keşfetme", "bg": "Знание и открития", "ro": "Învățare și descoperire", "pl": "Wiedza i odkrywanie", "lt": "Mokymasis ir atradimai", "hu": "Tanulás és felfedezés", "ca": "Aprenentatge i descobriment", "sl": "Učenje in odkrivanje"}'::jsonb WHERE theme_key = 'educational' AND language = 'fr';
UPDATE theme_rules SET labels = labels || '{"tr": "Öğrenme ve Keşfetme", "bg": "Знание и открития", "ro": "Învățare și descoperire", "pl": "Wiedza i odkrywanie", "lt": "Mokymasis ir atradimai", "hu": "Tanulás és felfedezés", "ca": "Aprenentatge i descobriment", "sl": "Učenje in odkrivanje"}'::jsonb WHERE theme_key = 'educational' AND language = 'de';
UPDATE theme_rules SET labels = labels || '{"tr": "Öğrenme ve Keşfetme", "bg": "Знание и открития", "ro": "Învățare și descoperire", "pl": "Wiedza i odkrywanie", "lt": "Mokymasis ir atradimai", "hu": "Tanulás és felfedezés", "ca": "Aprenentatge i descobriment", "sl": "Učenje in odkrivanje"}'::jsonb WHERE theme_key = 'educational' AND language = 'en';
